// Code generated by protoc-gen-go. DO NOT EDIT.
// source: AccessControl.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Permission_Action int32

const (
	Permission_READ   Permission_Action = 0
	Permission_WRITE  Permission_Action = 1
	Permission_EXEC   Permission_Action = 2
	Permission_CREATE Permission_Action = 3
	Permission_ADMIN  Permission_Action = 4
)

var Permission_Action_name = map[int32]string{
	0: "READ",
	1: "WRITE",
	2: "EXEC",
	3: "CREATE",
	4: "ADMIN",
}

var Permission_Action_value = map[string]int32{
	"READ":   0,
	"WRITE":  1,
	"EXEC":   2,
	"CREATE": 3,
	"ADMIN":  4,
}

func (x Permission_Action) Enum() *Permission_Action {
	p := new(Permission_Action)
	*p = x
	return p
}

func (x Permission_Action) String() string {
	return proto.EnumName(Permission_Action_name, int32(x))
}

func (x *Permission_Action) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Permission_Action_value, data, "Permission_Action")
	if err != nil {
		return err
	}
	*x = Permission_Action(value)
	return nil
}

func (Permission_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1aad9199c29ee89f, []int{0, 0}
}

type Permission_Type int32

const (
	Permission_Global    Permission_Type = 1
	Permission_Namespace Permission_Type = 2
	Permission_Table     Permission_Type = 3
)

var Permission_Type_name = map[int32]string{
	1: "Global",
	2: "Namespace",
	3: "Table",
}

var Permission_Type_value = map[string]int32{
	"Global":    1,
	"Namespace": 2,
	"Table":     3,
}

func (x Permission_Type) Enum() *Permission_Type {
	p := new(Permission_Type)
	*p = x
	return p
}

func (x Permission_Type) String() string {
	return proto.EnumName(Permission_Type_name, int32(x))
}

func (x *Permission_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Permission_Type_value, data, "Permission_Type")
	if err != nil {
		return err
	}
	*x = Permission_Type(value)
	return nil
}

func (Permission_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1aad9199c29ee89f, []int{0, 1}
}

type Permission struct {
	Type                 *Permission_Type     `protobuf:"varint,1,req,name=type,enum=hbase.pb.Permission_Type" json:"type,omitempty"`
	GlobalPermission     *GlobalPermission    `protobuf:"bytes,2,opt,name=global_permission,json=globalPermission" json:"global_permission,omitempty"`
	NamespacePermission  *NamespacePermission `protobuf:"bytes,3,opt,name=namespace_permission,json=namespacePermission" json:"namespace_permission,omitempty"`
	TablePermission      *TablePermission     `protobuf:"bytes,4,opt,name=table_permission,json=tablePermission" json:"table_permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Permission) Reset()         { *m = Permission{} }
func (m *Permission) String() string { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()    {}
func (*Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad9199c29ee89f, []int{0}
}

func (m *Permission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permission.Unmarshal(m, b)
}
func (m *Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permission.Marshal(b, m, deterministic)
}
func (m *Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permission.Merge(m, src)
}
func (m *Permission) XXX_Size() int {
	return xxx_messageInfo_Permission.Size(m)
}
func (m *Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Permission proto.InternalMessageInfo

func (m *Permission) GetType() Permission_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Permission_Global
}

func (m *Permission) GetGlobalPermission() *GlobalPermission {
	if m != nil {
		return m.GlobalPermission
	}
	return nil
}

func (m *Permission) GetNamespacePermission() *NamespacePermission {
	if m != nil {
		return m.NamespacePermission
	}
	return nil
}

func (m *Permission) GetTablePermission() *TablePermission {
	if m != nil {
		return m.TablePermission
	}
	return nil
}

type TablePermission struct {
	TableName            *TableName          `protobuf:"bytes,1,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	Family               []byte              `protobuf:"bytes,2,opt,name=family" json:"family,omitempty"`
	Qualifier            []byte              `protobuf:"bytes,3,opt,name=qualifier" json:"qualifier,omitempty"`
	Action               []Permission_Action `protobuf:"varint,4,rep,name=action,enum=hbase.pb.Permission_Action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TablePermission) Reset()         { *m = TablePermission{} }
func (m *TablePermission) String() string { return proto.CompactTextString(m) }
func (*TablePermission) ProtoMessage()    {}
func (*TablePermission) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad9199c29ee89f, []int{1}
}

func (m *TablePermission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TablePermission.Unmarshal(m, b)
}
func (m *TablePermission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TablePermission.Marshal(b, m, deterministic)
}
func (m *TablePermission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TablePermission.Merge(m, src)
}
func (m *TablePermission) XXX_Size() int {
	return xxx_messageInfo_TablePermission.Size(m)
}
func (m *TablePermission) XXX_DiscardUnknown() {
	xxx_messageInfo_TablePermission.DiscardUnknown(m)
}

var xxx_messageInfo_TablePermission proto.InternalMessageInfo

func (m *TablePermission) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *TablePermission) GetFamily() []byte {
	if m != nil {
		return m.Family
	}
	return nil
}

func (m *TablePermission) GetQualifier() []byte {
	if m != nil {
		return m.Qualifier
	}
	return nil
}

func (m *TablePermission) GetAction() []Permission_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type NamespacePermission struct {
	NamespaceName        []byte              `protobuf:"bytes,1,opt,name=namespace_name,json=namespaceName" json:"namespace_name,omitempty"`
	Action               []Permission_Action `protobuf:"varint,2,rep,name=action,enum=hbase.pb.Permission_Action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NamespacePermission) Reset()         { *m = NamespacePermission{} }
func (m *NamespacePermission) String() string { return proto.CompactTextString(m) }
func (*NamespacePermission) ProtoMessage()    {}
func (*NamespacePermission) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad9199c29ee89f, []int{2}
}

func (m *NamespacePermission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespacePermission.Unmarshal(m, b)
}
func (m *NamespacePermission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespacePermission.Marshal(b, m, deterministic)
}
func (m *NamespacePermission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespacePermission.Merge(m, src)
}
func (m *NamespacePermission) XXX_Size() int {
	return xxx_messageInfo_NamespacePermission.Size(m)
}
func (m *NamespacePermission) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespacePermission.DiscardUnknown(m)
}

var xxx_messageInfo_NamespacePermission proto.InternalMessageInfo

func (m *NamespacePermission) GetNamespaceName() []byte {
	if m != nil {
		return m.NamespaceName
	}
	return nil
}

func (m *NamespacePermission) GetAction() []Permission_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type GlobalPermission struct {
	Action               []Permission_Action `protobuf:"varint,1,rep,name=action,enum=hbase.pb.Permission_Action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GlobalPermission) Reset()         { *m = GlobalPermission{} }
func (m *GlobalPermission) String() string { return proto.CompactTextString(m) }
func (*GlobalPermission) ProtoMessage()    {}
func (*GlobalPermission) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad9199c29ee89f, []int{3}
}

func (m *GlobalPermission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalPermission.Unmarshal(m, b)
}
func (m *GlobalPermission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalPermission.Marshal(b, m, deterministic)
}
func (m *GlobalPermission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalPermission.Merge(m, src)
}
func (m *GlobalPermission) XXX_Size() int {
	return xxx_messageInfo_GlobalPermission.Size(m)
}
func (m *GlobalPermission) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalPermission.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalPermission proto.InternalMessageInfo

func (m *GlobalPermission) GetAction() []Permission_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type UserPermission struct {
	User                 []byte      `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	Permission           *Permission `protobuf:"bytes,3,req,name=permission" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserPermission) Reset()         { *m = UserPermission{} }
func (m *UserPermission) String() string { return proto.CompactTextString(m) }
func (*UserPermission) ProtoMessage()    {}
func (*UserPermission) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad9199c29ee89f, []int{4}
}

func (m *UserPermission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPermission.Unmarshal(m, b)
}
func (m *UserPermission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPermission.Marshal(b, m, deterministic)
}
func (m *UserPermission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPermission.Merge(m, src)
}
func (m *UserPermission) XXX_Size() int {
	return xxx_messageInfo_UserPermission.Size(m)
}
func (m *UserPermission) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPermission.DiscardUnknown(m)
}

var xxx_messageInfo_UserPermission proto.InternalMessageInfo

func (m *UserPermission) GetUser() []byte {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserPermission) GetPermission() *Permission {
	if m != nil {
		return m.Permission
	}
	return nil
}

//*
// Content of the /hbase/acl/<table or namespace> znode.
type UsersAndPermissions struct {
	UserPermissions      []*UsersAndPermissions_UserPermissions `protobuf:"bytes,1,rep,name=user_permissions,json=userPermissions" json:"user_permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *UsersAndPermissions) Reset()         { *m = UsersAndPermissions{} }
func (m *UsersAndPermissions) String() string { return proto.CompactTextString(m) }
func (*UsersAndPermissions) ProtoMessage()    {}
func (*UsersAndPermissions) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad9199c29ee89f, []int{5}
}

func (m *UsersAndPermissions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersAndPermissions.Unmarshal(m, b)
}
func (m *UsersAndPermissions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersAndPermissions.Marshal(b, m, deterministic)
}
func (m *UsersAndPermissions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersAndPermissions.Merge(m, src)
}
func (m *UsersAndPermissions) XXX_Size() int {
	return xxx_messageInfo_UsersAndPermissions.Size(m)
}
func (m *UsersAndPermissions) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersAndPermissions.DiscardUnknown(m)
}

var xxx_messageInfo_UsersAndPermissions proto.InternalMessageInfo

func (m *UsersAndPermissions) GetUserPermissions() []*UsersAndPermissions_UserPermissions {
	if m != nil {
		return m.UserPermissions
	}
	return nil
}

type UsersAndPermissions_UserPermissions struct {
	User                 []byte        `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	Permissions          []*Permission `protobuf:"bytes,2,rep,name=permissions" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UsersAndPermissions_UserPermissions) Reset()         { *m = UsersAndPermissions_UserPermissions{} }
func (m *UsersAndPermissions_UserPermissions) String() string { return proto.CompactTextString(m) }
func (*UsersAndPermissions_UserPermissions) ProtoMessage()    {}
func (*UsersAndPermissions_UserPermissions) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad9199c29ee89f, []int{5, 0}
}

func (m *UsersAndPermissions_UserPermissions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersAndPermissions_UserPermissions.Unmarshal(m, b)
}
func (m *UsersAndPermissions_UserPermissions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersAndPermissions_UserPermissions.Marshal(b, m, deterministic)
}
func (m *UsersAndPermissions_UserPermissions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersAndPermissions_UserPermissions.Merge(m, src)
}
func (m *UsersAndPermissions_UserPermissions) XXX_Size() int {
	return xxx_messageInfo_UsersAndPermissions_UserPermissions.Size(m)
}
func (m *UsersAndPermissions_UserPermissions) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersAndPermissions_UserPermissions.DiscardUnknown(m)
}

var xxx_messageInfo_UsersAndPermissions_UserPermissions proto.InternalMessageInfo

func (m *UsersAndPermissions_UserPermissions) GetUser() []byte {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UsersAndPermissions_UserPermissions) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type GrantRequest struct {
	UserPermission           *UserPermission `protobuf:"bytes,1,req,name=user_permission,json=userPermission" json:"user_permission,omitempty"`
	MergeExistingPermissions *bool           `protobuf:"varint,2,opt,name=merge_existing_permissions,json=mergeExistingPermissions,def=0" json:"merge_existing_permissions,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}        `json:"-"`
	XXX_unrecognized         []byte          `json:"-"`
	XXX_sizecache            int32           `json:"-"`
}

func (m *GrantRequest) Reset()         { *m = GrantRequest{} }
func (m *GrantRequest) String() string { return proto.CompactTextString(m) }
func (*GrantRequest) ProtoMessage()    {}
func (*GrantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad9199c29ee89f, []int{6}
}

func (m *GrantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrantRequest.Unmarshal(m, b)
}
func (m *GrantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrantRequest.Marshal(b, m, deterministic)
}
func (m *GrantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantRequest.Merge(m, src)
}
func (m *GrantRequest) XXX_Size() int {
	return xxx_messageInfo_GrantRequest.Size(m)
}
func (m *GrantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GrantRequest proto.InternalMessageInfo

const Default_GrantRequest_MergeExistingPermissions bool = false

func (m *GrantRequest) GetUserPermission() *UserPermission {
	if m != nil {
		return m.UserPermission
	}
	return nil
}

func (m *GrantRequest) GetMergeExistingPermissions() bool {
	if m != nil && m.MergeExistingPermissions != nil {
		return *m.MergeExistingPermissions
	}
	return Default_GrantRequest_MergeExistingPermissions
}

type GrantResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrantResponse) Reset()         { *m = GrantResponse{} }
func (m *GrantResponse) String() string { return proto.CompactTextString(m) }
func (*GrantResponse) ProtoMessage()    {}
func (*GrantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad9199c29ee89f, []int{7}
}

func (m *GrantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrantResponse.Unmarshal(m, b)
}
func (m *GrantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrantResponse.Marshal(b, m, deterministic)
}
func (m *GrantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantResponse.Merge(m, src)
}
func (m *GrantResponse) XXX_Size() int {
	return xxx_messageInfo_GrantResponse.Size(m)
}
func (m *GrantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GrantResponse proto.InternalMessageInfo

type RevokeRequest struct {
	UserPermission       *UserPermission `protobuf:"bytes,1,req,name=user_permission,json=userPermission" json:"user_permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RevokeRequest) Reset()         { *m = RevokeRequest{} }
func (m *RevokeRequest) String() string { return proto.CompactTextString(m) }
func (*RevokeRequest) ProtoMessage()    {}
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad9199c29ee89f, []int{8}
}

func (m *RevokeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeRequest.Unmarshal(m, b)
}
func (m *RevokeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeRequest.Marshal(b, m, deterministic)
}
func (m *RevokeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeRequest.Merge(m, src)
}
func (m *RevokeRequest) XXX_Size() int {
	return xxx_messageInfo_RevokeRequest.Size(m)
}
func (m *RevokeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeRequest proto.InternalMessageInfo

func (m *RevokeRequest) GetUserPermission() *UserPermission {
	if m != nil {
		return m.UserPermission
	}
	return nil
}

type RevokeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeResponse) Reset()         { *m = RevokeResponse{} }
func (m *RevokeResponse) String() string { return proto.CompactTextString(m) }
func (*RevokeResponse) ProtoMessage()    {}
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad9199c29ee89f, []int{9}
}

func (m *RevokeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeResponse.Unmarshal(m, b)
}
func (m *RevokeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeResponse.Marshal(b, m, deterministic)
}
func (m *RevokeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeResponse.Merge(m, src)
}
func (m *RevokeResponse) XXX_Size() int {
	return xxx_messageInfo_RevokeResponse.Size(m)
}
func (m *RevokeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeResponse proto.InternalMessageInfo

type GetUserPermissionsRequest struct {
	Type                 *Permission_Type `protobuf:"varint,1,opt,name=type,enum=hbase.pb.Permission_Type" json:"type,omitempty"`
	TableName            *TableName       `protobuf:"bytes,2,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	NamespaceName        []byte           `protobuf:"bytes,3,opt,name=namespace_name,json=namespaceName" json:"namespace_name,omitempty"`
	ColumnFamily         []byte           `protobuf:"bytes,4,opt,name=column_family,json=columnFamily" json:"column_family,omitempty"`
	ColumnQualifier      []byte           `protobuf:"bytes,5,opt,name=column_qualifier,json=columnQualifier" json:"column_qualifier,omitempty"`
	UserName             []byte           `protobuf:"bytes,6,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetUserPermissionsRequest) Reset()         { *m = GetUserPermissionsRequest{} }
func (m *GetUserPermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserPermissionsRequest) ProtoMessage()    {}
func (*GetUserPermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad9199c29ee89f, []int{10}
}

func (m *GetUserPermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserPermissionsRequest.Unmarshal(m, b)
}
func (m *GetUserPermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserPermissionsRequest.Marshal(b, m, deterministic)
}
func (m *GetUserPermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserPermissionsRequest.Merge(m, src)
}
func (m *GetUserPermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserPermissionsRequest.Size(m)
}
func (m *GetUserPermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserPermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserPermissionsRequest proto.InternalMessageInfo

func (m *GetUserPermissionsRequest) GetType() Permission_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Permission_Global
}

func (m *GetUserPermissionsRequest) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *GetUserPermissionsRequest) GetNamespaceName() []byte {
	if m != nil {
		return m.NamespaceName
	}
	return nil
}

func (m *GetUserPermissionsRequest) GetColumnFamily() []byte {
	if m != nil {
		return m.ColumnFamily
	}
	return nil
}

func (m *GetUserPermissionsRequest) GetColumnQualifier() []byte {
	if m != nil {
		return m.ColumnQualifier
	}
	return nil
}

func (m *GetUserPermissionsRequest) GetUserName() []byte {
	if m != nil {
		return m.UserName
	}
	return nil
}

type GetUserPermissionsResponse struct {
	UserPermission       []*UserPermission `protobuf:"bytes,1,rep,name=user_permission,json=userPermission" json:"user_permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetUserPermissionsResponse) Reset()         { *m = GetUserPermissionsResponse{} }
func (m *GetUserPermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserPermissionsResponse) ProtoMessage()    {}
func (*GetUserPermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad9199c29ee89f, []int{11}
}

func (m *GetUserPermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserPermissionsResponse.Unmarshal(m, b)
}
func (m *GetUserPermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserPermissionsResponse.Marshal(b, m, deterministic)
}
func (m *GetUserPermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserPermissionsResponse.Merge(m, src)
}
func (m *GetUserPermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserPermissionsResponse.Size(m)
}
func (m *GetUserPermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserPermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserPermissionsResponse proto.InternalMessageInfo

func (m *GetUserPermissionsResponse) GetUserPermission() []*UserPermission {
	if m != nil {
		return m.UserPermission
	}
	return nil
}

type CheckPermissionsRequest struct {
	Permission           []*Permission `protobuf:"bytes,1,rep,name=permission" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CheckPermissionsRequest) Reset()         { *m = CheckPermissionsRequest{} }
func (m *CheckPermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*CheckPermissionsRequest) ProtoMessage()    {}
func (*CheckPermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad9199c29ee89f, []int{12}
}

func (m *CheckPermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPermissionsRequest.Unmarshal(m, b)
}
func (m *CheckPermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPermissionsRequest.Marshal(b, m, deterministic)
}
func (m *CheckPermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPermissionsRequest.Merge(m, src)
}
func (m *CheckPermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_CheckPermissionsRequest.Size(m)
}
func (m *CheckPermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPermissionsRequest proto.InternalMessageInfo

func (m *CheckPermissionsRequest) GetPermission() []*Permission {
	if m != nil {
		return m.Permission
	}
	return nil
}

type CheckPermissionsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPermissionsResponse) Reset()         { *m = CheckPermissionsResponse{} }
func (m *CheckPermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*CheckPermissionsResponse) ProtoMessage()    {}
func (*CheckPermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad9199c29ee89f, []int{13}
}

func (m *CheckPermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPermissionsResponse.Unmarshal(m, b)
}
func (m *CheckPermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPermissionsResponse.Marshal(b, m, deterministic)
}
func (m *CheckPermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPermissionsResponse.Merge(m, src)
}
func (m *CheckPermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_CheckPermissionsResponse.Size(m)
}
func (m *CheckPermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPermissionsResponse proto.InternalMessageInfo

type HasUserPermissionsRequest struct {
	UserName             []byte        `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	Permission           []*Permission `protobuf:"bytes,2,rep,name=permission" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HasUserPermissionsRequest) Reset()         { *m = HasUserPermissionsRequest{} }
func (m *HasUserPermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*HasUserPermissionsRequest) ProtoMessage()    {}
func (*HasUserPermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad9199c29ee89f, []int{14}
}

func (m *HasUserPermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasUserPermissionsRequest.Unmarshal(m, b)
}
func (m *HasUserPermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasUserPermissionsRequest.Marshal(b, m, deterministic)
}
func (m *HasUserPermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasUserPermissionsRequest.Merge(m, src)
}
func (m *HasUserPermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_HasUserPermissionsRequest.Size(m)
}
func (m *HasUserPermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HasUserPermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HasUserPermissionsRequest proto.InternalMessageInfo

func (m *HasUserPermissionsRequest) GetUserName() []byte {
	if m != nil {
		return m.UserName
	}
	return nil
}

func (m *HasUserPermissionsRequest) GetPermission() []*Permission {
	if m != nil {
		return m.Permission
	}
	return nil
}

type HasUserPermissionsResponse struct {
	HasUserPermission    []bool   `protobuf:"varint,1,rep,name=has_user_permission,json=hasUserPermission" json:"has_user_permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasUserPermissionsResponse) Reset()         { *m = HasUserPermissionsResponse{} }
func (m *HasUserPermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*HasUserPermissionsResponse) ProtoMessage()    {}
func (*HasUserPermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aad9199c29ee89f, []int{15}
}

func (m *HasUserPermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasUserPermissionsResponse.Unmarshal(m, b)
}
func (m *HasUserPermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasUserPermissionsResponse.Marshal(b, m, deterministic)
}
func (m *HasUserPermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasUserPermissionsResponse.Merge(m, src)
}
func (m *HasUserPermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_HasUserPermissionsResponse.Size(m)
}
func (m *HasUserPermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HasUserPermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HasUserPermissionsResponse proto.InternalMessageInfo

func (m *HasUserPermissionsResponse) GetHasUserPermission() []bool {
	if m != nil {
		return m.HasUserPermission
	}
	return nil
}

func init() {
	proto.RegisterEnum("hbase.pb.Permission_Action", Permission_Action_name, Permission_Action_value)
	proto.RegisterEnum("hbase.pb.Permission_Type", Permission_Type_name, Permission_Type_value)
	proto.RegisterType((*Permission)(nil), "hbase.pb.Permission")
	proto.RegisterType((*TablePermission)(nil), "hbase.pb.TablePermission")
	proto.RegisterType((*NamespacePermission)(nil), "hbase.pb.NamespacePermission")
	proto.RegisterType((*GlobalPermission)(nil), "hbase.pb.GlobalPermission")
	proto.RegisterType((*UserPermission)(nil), "hbase.pb.UserPermission")
	proto.RegisterType((*UsersAndPermissions)(nil), "hbase.pb.UsersAndPermissions")
	proto.RegisterType((*UsersAndPermissions_UserPermissions)(nil), "hbase.pb.UsersAndPermissions.UserPermissions")
	proto.RegisterType((*GrantRequest)(nil), "hbase.pb.GrantRequest")
	proto.RegisterType((*GrantResponse)(nil), "hbase.pb.GrantResponse")
	proto.RegisterType((*RevokeRequest)(nil), "hbase.pb.RevokeRequest")
	proto.RegisterType((*RevokeResponse)(nil), "hbase.pb.RevokeResponse")
	proto.RegisterType((*GetUserPermissionsRequest)(nil), "hbase.pb.GetUserPermissionsRequest")
	proto.RegisterType((*GetUserPermissionsResponse)(nil), "hbase.pb.GetUserPermissionsResponse")
	proto.RegisterType((*CheckPermissionsRequest)(nil), "hbase.pb.CheckPermissionsRequest")
	proto.RegisterType((*CheckPermissionsResponse)(nil), "hbase.pb.CheckPermissionsResponse")
	proto.RegisterType((*HasUserPermissionsRequest)(nil), "hbase.pb.HasUserPermissionsRequest")
	proto.RegisterType((*HasUserPermissionsResponse)(nil), "hbase.pb.HasUserPermissionsResponse")
}

func init() { proto.RegisterFile("AccessControl.proto", fileDescriptor_1aad9199c29ee89f) }

var fileDescriptor_1aad9199c29ee89f = []byte{
	// 866 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5f, 0x8b, 0xe3, 0x54,
	0x14, 0xf7, 0xa6, 0x99, 0xd2, 0x9e, 0xfe, 0xcb, 0xde, 0x0e, 0xbb, 0x99, 0xac, 0xc2, 0x98, 0x55,
	0xa8, 0xe0, 0x06, 0x8c, 0x22, 0xa2, 0x20, 0x74, 0x3a, 0xb5, 0xb3, 0xa0, 0xeb, 0x78, 0xad, 0xb8,
	0x0a, 0x52, 0x6e, 0xd3, 0xdb, 0x36, 0x6c, 0x9a, 0x64, 0x72, 0xd3, 0xc1, 0xf9, 0x06, 0xe2, 0xa3,
	0x0f, 0x3e, 0xfb, 0x11, 0xfc, 0x1a, 0xbe, 0xf8, 0x99, 0x24, 0x37, 0x69, 0x73, 0x93, 0x66, 0x86,
	0x0a, 0xfb, 0x96, 0x9e, 0xfc, 0xce, 0xef, 0xfc, 0xce, 0xdf, 0x06, 0xfa, 0x43, 0xc7, 0x61, 0x9c,
	0x8f, 0x02, 0x3f, 0x8e, 0x02, 0xcf, 0x0a, 0xa3, 0x20, 0x0e, 0x70, 0x63, 0x3d, 0xa7, 0x9c, 0x59,
	0xe1, 0xdc, 0x68, 0x5d, 0x5d, 0x88, 0xa7, 0xc4, 0x6c, 0xfe, 0x5e, 0x03, 0xb8, 0x66, 0xd1, 0xc6,
	0xe5, 0xdc, 0x0d, 0x7c, 0xfc, 0x1c, 0xd4, 0xf8, 0x2e, 0x64, 0x3a, 0x3a, 0x57, 0x06, 0x5d, 0xfb,
	0xcc, 0xda, 0x39, 0x59, 0x39, 0xc6, 0x9a, 0xde, 0x85, 0x8c, 0x08, 0x18, 0x9e, 0xc0, 0xa3, 0x95,
	0x17, 0xcc, 0xa9, 0x37, 0x0b, 0xf7, 0xef, 0x75, 0xe5, 0x1c, 0x0d, 0x5a, 0xb6, 0x91, 0xfb, 0x4e,
	0x04, 0x24, 0x67, 0x20, 0xda, 0xaa, 0x64, 0xc1, 0xd7, 0x70, 0xea, 0xd3, 0x0d, 0xe3, 0x21, 0x75,
	0x98, 0xcc, 0x55, 0x13, 0x5c, 0xef, 0xe4, 0x5c, 0x2f, 0x77, 0x28, 0x89, 0xae, 0xef, 0x1f, 0x1a,
	0xf1, 0x25, 0x68, 0x31, 0x9d, 0x7b, 0x05, 0x36, 0x55, 0xb0, 0x49, 0x59, 0x4d, 0x13, 0x84, 0xc4,
	0xd4, 0x8b, 0x8b, 0x06, 0xf3, 0x4b, 0xa8, 0x0f, 0x9d, 0x38, 0xe1, 0x6b, 0x80, 0x4a, 0xc6, 0xc3,
	0x4b, 0xed, 0x2d, 0xdc, 0x84, 0x93, 0x1f, 0xc9, 0x8b, 0xe9, 0x58, 0x43, 0x89, 0x71, 0xfc, 0x6a,
	0x3c, 0xd2, 0x14, 0x0c, 0x50, 0x1f, 0x91, 0xf1, 0x70, 0x3a, 0xd6, 0x6a, 0x09, 0x60, 0x78, 0xf9,
	0xcd, 0x8b, 0x97, 0x9a, 0x6a, 0x7e, 0x08, 0x6a, 0x52, 0xae, 0xe4, 0x75, 0x5a, 0x05, 0x0d, 0xe1,
	0x0e, 0x34, 0xf7, 0x59, 0x68, 0x4a, 0x82, 0x16, 0x32, 0xb4, 0x9a, 0xf9, 0x37, 0x82, 0x5e, 0x49,
	0x12, 0xb6, 0x01, 0xd2, 0x3c, 0x92, 0x24, 0x75, 0x24, 0x32, 0xe8, 0x97, 0x32, 0x48, 0xe8, 0x48,
	0x33, 0xde, 0x3d, 0xe2, 0xc7, 0x50, 0x5f, 0xd2, 0x8d, 0xeb, 0xdd, 0x89, 0x5e, 0xb4, 0x49, 0xf6,
	0x0b, 0xbf, 0x0d, 0xcd, 0x9b, 0x2d, 0xf5, 0xdc, 0xa5, 0xcb, 0x22, 0x51, 0xda, 0x36, 0xc9, 0x0d,
	0xf8, 0x63, 0xa8, 0x53, 0x91, 0xab, 0xae, 0x9e, 0xd7, 0x06, 0x5d, 0xfb, 0x69, 0x65, 0xf7, 0xd3,
	0x72, 0x90, 0x0c, 0x6a, 0xde, 0x40, 0xbf, 0xa2, 0x25, 0xf8, 0x7d, 0xe8, 0xe6, 0xfd, 0xdc, 0x2b,
	0x6f, 0x93, 0xce, 0xde, 0x2a, 0x84, 0xe6, 0x21, 0x95, 0xe3, 0x43, 0x4e, 0x40, 0x2b, 0x4f, 0x94,
	0x44, 0x84, 0x8e, 0x27, 0xfa, 0x19, 0xba, 0x3f, 0x70, 0x16, 0x49, 0x34, 0x18, 0xd4, 0x2d, 0x67,
	0x91, 0x18, 0xff, 0x36, 0x11, 0xcf, 0xf8, 0x13, 0x80, 0xc2, 0x40, 0x2a, 0x83, 0x96, 0x7d, 0x5a,
	0x45, 0x4f, 0x24, 0x9c, 0xf9, 0x2f, 0x82, 0x7e, 0x42, 0xce, 0x87, 0xfe, 0x22, 0x87, 0x70, 0xfc,
	0x0a, 0xb4, 0x84, 0x55, 0x9a, 0x4a, 0x2e, 0x24, 0xb7, 0xec, 0xe7, 0x39, 0x67, 0x85, 0xa3, 0x55,
	0x54, 0xca, 0x49, 0x6f, 0x5b, 0x34, 0x18, 0xbf, 0x40, 0xaf, 0x84, 0xa9, 0x4c, 0xe7, 0x53, 0x68,
	0xc9, 0xb1, 0x15, 0x11, 0xbb, 0x3a, 0x1f, 0x19, 0x68, 0xfe, 0x89, 0xa0, 0x3d, 0x89, 0xa8, 0x1f,
	0x13, 0x76, 0xb3, 0x65, 0x3c, 0xc6, 0x43, 0xe8, 0x95, 0x32, 0x11, 0x71, 0x5a, 0xb6, 0x5e, 0x4c,
	0x44, 0x22, 0xec, 0x16, 0x35, 0xe3, 0x11, 0x18, 0x1b, 0x16, 0xad, 0xd8, 0x8c, 0xfd, 0xea, 0xf2,
	0xd8, 0xf5, 0x57, 0xb3, 0xa2, 0x34, 0x34, 0x68, 0x7c, 0x7e, 0xb2, 0xa4, 0x1e, 0x67, 0x44, 0x17,
	0xc0, 0x71, 0x86, 0x93, 0x92, 0x34, 0x7b, 0xd0, 0xc9, 0x74, 0xf1, 0x30, 0xf0, 0x39, 0x33, 0x09,
	0x74, 0x08, 0xbb, 0x0d, 0x5e, 0xb3, 0x37, 0xa7, 0xd4, 0xd4, 0xa0, 0xbb, 0xe3, 0xcc, 0xa2, 0xfc,
	0xa1, 0xc0, 0xd9, 0x84, 0xc5, 0xe5, 0xb6, 0x64, 0x21, 0xf3, 0x3b, 0x8a, 0x8e, 0xb9, 0xa3, 0xc5,
	0x25, 0x57, 0x8e, 0x5a, 0xf2, 0xc3, 0x15, 0xab, 0x55, 0xad, 0xd8, 0x33, 0xe8, 0x38, 0x81, 0xb7,
	0xdd, 0xf8, 0xb3, 0xec, 0x24, 0xa8, 0x02, 0xd5, 0x4e, 0x8d, 0x5f, 0xa5, 0x87, 0xe1, 0x03, 0xd0,
	0x32, 0x50, 0x7e, 0x1f, 0x4e, 0x04, 0xae, 0x97, 0xda, 0xbf, 0xdb, 0x5f, 0x89, 0xa7, 0xd0, 0x14,
	0xc5, 0x14, 0x11, 0xeb, 0x02, 0xd3, 0x48, 0x0c, 0x49, 0x30, 0x73, 0x06, 0x46, 0x55, 0x4d, 0xd2,
	0x92, 0x55, 0xf7, 0xa1, 0xf6, 0xbf, 0xfa, 0xf0, 0x2d, 0x3c, 0x19, 0xad, 0x99, 0xf3, 0xba, 0xa2,
	0xe4, 0xc5, 0x3d, 0x45, 0x0f, 0xcc, 0xb5, 0xbc, 0xa7, 0x06, 0xe8, 0x87, 0x84, 0x59, 0x8b, 0x7d,
	0x38, 0xbb, 0xa2, 0xfc, 0x9e, 0x0e, 0x17, 0xea, 0x80, 0x8a, 0x75, 0x28, 0x69, 0x51, 0x8e, 0xd4,
	0xf2, 0x35, 0x18, 0x55, 0xf1, 0xb2, 0xea, 0x59, 0xd0, 0x5f, 0x53, 0x3e, 0xab, 0xaa, 0x60, 0x83,
	0x3c, 0x5a, 0x97, 0x1d, 0xed, 0x7f, 0x14, 0x38, 0x2d, 0x7c, 0x08, 0x7c, 0xcf, 0xa2, 0x5b, 0xd7,
	0x61, 0xf8, 0x33, 0x38, 0x11, 0x0b, 0x83, 0x1f, 0x4b, 0x7f, 0xd1, 0xd2, 0x66, 0x1b, 0x4f, 0x0e,
	0xec, 0x99, 0x84, 0x2f, 0xa0, 0x9e, 0x6e, 0x01, 0x96, 0x20, 0x85, 0x5d, 0x33, 0xf4, 0xc3, 0x17,
	0x99, 0xf3, 0x0c, 0xf0, 0xe1, 0x6c, 0xe0, 0x67, 0x52, 0xac, 0xfb, 0xb6, 0xc9, 0x78, 0xef, 0x61,
	0x50, 0x16, 0xe0, 0x27, 0xd0, 0xca, 0xad, 0xc4, 0xef, 0xe6, 0x9e, 0xf7, 0xcc, 0x8d, 0x61, 0x3e,
	0x04, 0x49, 0xa9, 0x2f, 0xae, 0xe1, 0xa3, 0x20, 0x5a, 0x59, 0x34, 0xa4, 0xce, 0x9a, 0x59, 0x6b,
	0xba, 0x08, 0x82, 0x30, 0x73, 0xe3, 0x6b, 0xba, 0x60, 0x8b, 0xf4, 0x6b, 0x6a, 0xbe, 0x5d, 0x5a,
	0x2b, 0xe6, 0xb3, 0x88, 0xc6, 0x6c, 0x71, 0x51, 0xfc, 0x0c, 0xbb, 0x4e, 0x00, 0xfc, 0x0a, 0xfd,
	0x86, 0xd0, 0x5f, 0x08, 0xfd, 0x17, 0x00, 0x00, 0xff, 0xff, 0x99, 0x30, 0x36, 0x12, 0xa4, 0x09,
	0x00, 0x00,
}
