// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ClusterId.proto

// This file contains protocol buffers that are shared throughout HBase

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// Content of the '/hbase/hbaseid', cluster id, znode.
// Also cluster of the ${HBASE_ROOTDIR}/hbase.id file.
type ClusterId struct {
	// This is the cluster id, a uuid as a String
	ClusterId            *string  `protobuf:"bytes,1,req,name=cluster_id,json=clusterId" json:"cluster_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterId) Reset()         { *m = ClusterId{} }
func (m *ClusterId) String() string { return proto.CompactTextString(m) }
func (*ClusterId) ProtoMessage()    {}
func (*ClusterId) Descriptor() ([]byte, []int) {
	return fileDescriptor_949894e29270459f, []int{0}
}

func (m *ClusterId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterId.Unmarshal(m, b)
}
func (m *ClusterId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterId.Marshal(b, m, deterministic)
}
func (m *ClusterId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterId.Merge(m, src)
}
func (m *ClusterId) XXX_Size() int {
	return xxx_messageInfo_ClusterId.Size(m)
}
func (m *ClusterId) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterId.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterId proto.InternalMessageInfo

func (m *ClusterId) GetClusterId() string {
	if m != nil && m.ClusterId != nil {
		return *m.ClusterId
	}
	return ""
}

func init() {
	proto.RegisterType((*ClusterId)(nil), "hbase.pb.ClusterId")
}

func init() { proto.RegisterFile("ClusterId.proto", fileDescriptor_949894e29270459f) }

var fileDescriptor_949894e29270459f = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x77, 0xce, 0x29, 0x2d,
	0x2e, 0x49, 0x2d, 0xf2, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0x48, 0x4a,
	0x2c, 0x4e, 0xd5, 0x2b, 0x48, 0x52, 0xd2, 0xe2, 0xe2, 0x84, 0x4b, 0x0a, 0xc9, 0x72, 0x71, 0x25,
	0x43, 0x38, 0xf1, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x9c, 0x41, 0x9c, 0xc9, 0x30, 0x69,
	0x27, 0x4f, 0x2e, 0xc3, 0xfc, 0xa2, 0x74, 0xbd, 0xc4, 0x82, 0xc4, 0xe4, 0x8c, 0x54, 0xbd, 0x8c,
	0xc4, 0x94, 0xfc, 0xfc, 0x02, 0x3d, 0x88, 0x49, 0xc5, 0x19, 0x89, 0x29, 0xa9, 0x50, 0xd3, 0x93,
	0x4a, 0xd3, 0xf4, 0xd2, 0x53, 0xf3, 0x52, 0x8b, 0x12, 0x4b, 0x52, 0x53, 0x9c, 0x10, 0x76, 0x07,
	0x80, 0x24, 0x8b, 0x3d, 0x18, 0x17, 0x30, 0x32, 0x02, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x65,
	0xd1, 0xbf, 0x92, 0x00, 0x00, 0x00,
}
