// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ErrorHandling.proto

// This file contains protocol buffers that are used for error handling

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// Protobuf version of a java.lang.StackTraceElement
// so we can serialize exceptions.
type StackTraceElementMessage struct {
	DeclaringClass       *string  `protobuf:"bytes,1,opt,name=declaring_class,json=declaringClass" json:"declaring_class,omitempty"`
	MethodName           *string  `protobuf:"bytes,2,opt,name=method_name,json=methodName" json:"method_name,omitempty"`
	FileName             *string  `protobuf:"bytes,3,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
	LineNumber           *int32   `protobuf:"varint,4,opt,name=line_number,json=lineNumber" json:"line_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StackTraceElementMessage) Reset()         { *m = StackTraceElementMessage{} }
func (m *StackTraceElementMessage) String() string { return proto.CompactTextString(m) }
func (*StackTraceElementMessage) ProtoMessage()    {}
func (*StackTraceElementMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_22ed3b342e4552c1, []int{0}
}

func (m *StackTraceElementMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StackTraceElementMessage.Unmarshal(m, b)
}
func (m *StackTraceElementMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StackTraceElementMessage.Marshal(b, m, deterministic)
}
func (m *StackTraceElementMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StackTraceElementMessage.Merge(m, src)
}
func (m *StackTraceElementMessage) XXX_Size() int {
	return xxx_messageInfo_StackTraceElementMessage.Size(m)
}
func (m *StackTraceElementMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StackTraceElementMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StackTraceElementMessage proto.InternalMessageInfo

func (m *StackTraceElementMessage) GetDeclaringClass() string {
	if m != nil && m.DeclaringClass != nil {
		return *m.DeclaringClass
	}
	return ""
}

func (m *StackTraceElementMessage) GetMethodName() string {
	if m != nil && m.MethodName != nil {
		return *m.MethodName
	}
	return ""
}

func (m *StackTraceElementMessage) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *StackTraceElementMessage) GetLineNumber() int32 {
	if m != nil && m.LineNumber != nil {
		return *m.LineNumber
	}
	return 0
}

//*
// Cause of a remote failure for a generic exception. Contains
// all the information for a generic exception as well as
// optional info about the error for generic info passing
// (which should be another protobuffed class).
type GenericExceptionMessage struct {
	ClassName            *string                     `protobuf:"bytes,1,opt,name=class_name,json=className" json:"class_name,omitempty"`
	Message              *string                     `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	ErrorInfo            []byte                      `protobuf:"bytes,3,opt,name=error_info,json=errorInfo" json:"error_info,omitempty"`
	Trace                []*StackTraceElementMessage `protobuf:"bytes,4,rep,name=trace" json:"trace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GenericExceptionMessage) Reset()         { *m = GenericExceptionMessage{} }
func (m *GenericExceptionMessage) String() string { return proto.CompactTextString(m) }
func (*GenericExceptionMessage) ProtoMessage()    {}
func (*GenericExceptionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_22ed3b342e4552c1, []int{1}
}

func (m *GenericExceptionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericExceptionMessage.Unmarshal(m, b)
}
func (m *GenericExceptionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericExceptionMessage.Marshal(b, m, deterministic)
}
func (m *GenericExceptionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericExceptionMessage.Merge(m, src)
}
func (m *GenericExceptionMessage) XXX_Size() int {
	return xxx_messageInfo_GenericExceptionMessage.Size(m)
}
func (m *GenericExceptionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericExceptionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GenericExceptionMessage proto.InternalMessageInfo

func (m *GenericExceptionMessage) GetClassName() string {
	if m != nil && m.ClassName != nil {
		return *m.ClassName
	}
	return ""
}

func (m *GenericExceptionMessage) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *GenericExceptionMessage) GetErrorInfo() []byte {
	if m != nil {
		return m.ErrorInfo
	}
	return nil
}

func (m *GenericExceptionMessage) GetTrace() []*StackTraceElementMessage {
	if m != nil {
		return m.Trace
	}
	return nil
}

//*
// Exception sent across the wire when a remote task needs
// to notify other tasks that it failed and why
type ForeignExceptionMessage struct {
	Source               *string                  `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	GenericException     *GenericExceptionMessage `protobuf:"bytes,2,opt,name=generic_exception,json=genericException" json:"generic_exception,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ForeignExceptionMessage) Reset()         { *m = ForeignExceptionMessage{} }
func (m *ForeignExceptionMessage) String() string { return proto.CompactTextString(m) }
func (*ForeignExceptionMessage) ProtoMessage()    {}
func (*ForeignExceptionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_22ed3b342e4552c1, []int{2}
}

func (m *ForeignExceptionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForeignExceptionMessage.Unmarshal(m, b)
}
func (m *ForeignExceptionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForeignExceptionMessage.Marshal(b, m, deterministic)
}
func (m *ForeignExceptionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForeignExceptionMessage.Merge(m, src)
}
func (m *ForeignExceptionMessage) XXX_Size() int {
	return xxx_messageInfo_ForeignExceptionMessage.Size(m)
}
func (m *ForeignExceptionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ForeignExceptionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ForeignExceptionMessage proto.InternalMessageInfo

func (m *ForeignExceptionMessage) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *ForeignExceptionMessage) GetGenericException() *GenericExceptionMessage {
	if m != nil {
		return m.GenericException
	}
	return nil
}

func init() {
	proto.RegisterType((*StackTraceElementMessage)(nil), "hbase.pb.StackTraceElementMessage")
	proto.RegisterType((*GenericExceptionMessage)(nil), "hbase.pb.GenericExceptionMessage")
	proto.RegisterType((*ForeignExceptionMessage)(nil), "hbase.pb.ForeignExceptionMessage")
}

func init() { proto.RegisterFile("ErrorHandling.proto", fileDescriptor_22ed3b342e4552c1) }

var fileDescriptor_22ed3b342e4552c1 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x86, 0x99, 0xaf, 0xed, 0x67, 0x73, 0x22, 0xfe, 0x44, 0xb0, 0x01, 0x91, 0xd6, 0x6c, 0xec,
	0x2a, 0x60, 0x57, 0xae, 0x2b, 0xd5, 0xba, 0x68, 0x91, 0xe8, 0x3e, 0x4c, 0x26, 0x27, 0xc9, 0x60,
	0x32, 0x13, 0x66, 0x52, 0x70, 0xeb, 0x9d, 0x88, 0x5b, 0x6f, 0x52, 0x32, 0xd3, 0x28, 0x2a, 0x5d,
	0xce, 0x73, 0x7e, 0xf2, 0xe4, 0xe5, 0xc0, 0xc9, 0x42, 0x29, 0xa9, 0x96, 0x54, 0xa4, 0x25, 0x17,
	0x79, 0x58, 0x2b, 0xd9, 0x48, 0x6f, 0x58, 0x24, 0x54, 0x63, 0x58, 0x27, 0xc1, 0x3b, 0x01, 0xff,
	0xb1, 0xa1, 0xec, 0xf9, 0x49, 0x51, 0x86, 0x8b, 0x12, 0x2b, 0x14, 0xcd, 0x0a, 0xb5, 0xa6, 0x39,
	0x7a, 0x97, 0x70, 0x98, 0x22, 0x2b, 0xa9, 0xe2, 0x22, 0x8f, 0x59, 0x49, 0xb5, 0xf6, 0xc9, 0x84,
	0x4c, 0x9d, 0xe8, 0xe0, 0x0b, 0xdf, 0xb4, 0xd4, 0x1b, 0x83, 0x5b, 0x61, 0x53, 0xc8, 0x34, 0x16,
	0xb4, 0x42, 0xff, 0x9f, 0x69, 0x02, 0x8b, 0xd6, 0xb4, 0x42, 0xef, 0x0c, 0x9c, 0x8c, 0x97, 0x68,
	0xcb, 0x3d, 0x53, 0x1e, 0xb6, 0xc0, 0x14, 0xc7, 0xe0, 0x96, 0x5c, 0x60, 0x2c, 0x36, 0x55, 0x82,
	0xca, 0xef, 0x4f, 0xc8, 0x74, 0x10, 0x41, 0x8b, 0xd6, 0x86, 0x04, 0x1f, 0x04, 0x46, 0x77, 0x28,
	0x50, 0x71, 0xb6, 0x78, 0x61, 0x58, 0x37, 0x5c, 0x8a, 0xce, 0xf1, 0x1c, 0xc0, 0x98, 0xd9, 0xd5,
	0x56, 0xcf, 0x31, 0xc4, 0xec, 0xf6, 0x61, 0xaf, 0xb2, 0x9d, 0x5b, 0xab, 0xee, 0xd9, 0x0e, 0x62,
	0x1b, 0x4d, 0xcc, 0x45, 0x26, 0x8d, 0xd3, 0x7e, 0xe4, 0x18, 0x72, 0x2f, 0x32, 0xe9, 0x5d, 0xc3,
	0xa0, 0x69, 0x23, 0xf1, 0xfb, 0x93, 0xde, 0xd4, 0x9d, 0x05, 0x61, 0x17, 0x59, 0xb8, 0x2b, 0xae,
	0xc8, 0x0e, 0x04, 0xaf, 0x04, 0x46, 0xb7, 0x52, 0x21, 0xcf, 0xc5, 0x1f, 0xdb, 0x53, 0xf8, 0xaf,
	0xe5, 0x46, 0xb1, 0xce, 0x74, 0xfb, 0xf2, 0xd6, 0x70, 0x9c, 0xdb, 0x1f, 0x8c, 0xb1, 0x9b, 0x31,
	0xc2, 0xee, 0xec, 0xe2, 0xfb, 0xcb, 0x3b, 0x32, 0x88, 0x8e, 0xf2, 0x5f, 0x85, 0xf9, 0x0a, 0xae,
	0xa4, 0xca, 0x43, 0x5a, 0x53, 0x56, 0x60, 0x58, 0xd0, 0x54, 0xca, 0x7a, 0xbb, 0x47, 0x17, 0x34,
	0xc5, 0xd4, 0x1e, 0x42, 0xb2, 0xc9, 0x42, 0x33, 0x4b, 0x1b, 0x4c, 0xe7, 0x3f, 0x4f, 0xe5, 0xa1,
	0x6d, 0xd0, 0x4b, 0xf2, 0x46, 0xc8, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xab, 0x52, 0xbc,
	0x45, 0x02, 0x00, 0x00,
}
