// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Hbase.proto

// This file contains protocol buffers that are shared throughout HBase

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Comparison operators
type CompareType int32

const (
	CompareType_LESS             CompareType = 0
	CompareType_LESS_OR_EQUAL    CompareType = 1
	CompareType_EQUAL            CompareType = 2
	CompareType_NOT_EQUAL        CompareType = 3
	CompareType_GREATER_OR_EQUAL CompareType = 4
	CompareType_GREATER          CompareType = 5
	CompareType_NO_OP            CompareType = 6
)

var CompareType_name = map[int32]string{
	0: "LESS",
	1: "LESS_OR_EQUAL",
	2: "EQUAL",
	3: "NOT_EQUAL",
	4: "GREATER_OR_EQUAL",
	5: "GREATER",
	6: "NO_OP",
}

var CompareType_value = map[string]int32{
	"LESS":             0,
	"LESS_OR_EQUAL":    1,
	"EQUAL":            2,
	"NOT_EQUAL":        3,
	"GREATER_OR_EQUAL": 4,
	"GREATER":          5,
	"NO_OP":            6,
}

func (x CompareType) Enum() *CompareType {
	p := new(CompareType)
	*p = x
	return p
}

func (x CompareType) String() string {
	return proto.EnumName(CompareType_name, int32(x))
}

func (x *CompareType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CompareType_value, data, "CompareType")
	if err != nil {
		return err
	}
	*x = CompareType(value)
	return nil
}

func (CompareType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{0}
}

type TimeUnit int32

const (
	TimeUnit_NANOSECONDS  TimeUnit = 1
	TimeUnit_MICROSECONDS TimeUnit = 2
	TimeUnit_MILLISECONDS TimeUnit = 3
	TimeUnit_SECONDS      TimeUnit = 4
	TimeUnit_MINUTES      TimeUnit = 5
	TimeUnit_HOURS        TimeUnit = 6
	TimeUnit_DAYS         TimeUnit = 7
)

var TimeUnit_name = map[int32]string{
	1: "NANOSECONDS",
	2: "MICROSECONDS",
	3: "MILLISECONDS",
	4: "SECONDS",
	5: "MINUTES",
	6: "HOURS",
	7: "DAYS",
}

var TimeUnit_value = map[string]int32{
	"NANOSECONDS":  1,
	"MICROSECONDS": 2,
	"MILLISECONDS": 3,
	"SECONDS":      4,
	"MINUTES":      5,
	"HOURS":        6,
	"DAYS":         7,
}

func (x TimeUnit) Enum() *TimeUnit {
	p := new(TimeUnit)
	*p = x
	return p
}

func (x TimeUnit) String() string {
	return proto.EnumName(TimeUnit_name, int32(x))
}

func (x *TimeUnit) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TimeUnit_value, data, "TimeUnit")
	if err != nil {
		return err
	}
	*x = TimeUnit(value)
	return nil
}

func (TimeUnit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{1}
}

// Table's current state
type TableState_State int32

const (
	TableState_ENABLED   TableState_State = 0
	TableState_DISABLED  TableState_State = 1
	TableState_DISABLING TableState_State = 2
	TableState_ENABLING  TableState_State = 3
)

var TableState_State_name = map[int32]string{
	0: "ENABLED",
	1: "DISABLED",
	2: "DISABLING",
	3: "ENABLING",
}

var TableState_State_value = map[string]int32{
	"ENABLED":   0,
	"DISABLED":  1,
	"DISABLING": 2,
	"ENABLING":  3,
}

func (x TableState_State) Enum() *TableState_State {
	p := new(TableState_State)
	*p = x
	return p
}

func (x TableState_State) String() string {
	return proto.EnumName(TableState_State_name, int32(x))
}

func (x *TableState_State) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TableState_State_value, data, "TableState_State")
	if err != nil {
		return err
	}
	*x = TableState_State(value)
	return nil
}

func (TableState_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{2, 0}
}

type RegionSpecifier_RegionSpecifierType int32

const (
	// <tablename>,<startkey>,<regionId>.<encodedName>
	RegionSpecifier_REGION_NAME RegionSpecifier_RegionSpecifierType = 1
	// hash of <tablename>,<startkey>,<regionId>
	RegionSpecifier_ENCODED_REGION_NAME RegionSpecifier_RegionSpecifierType = 2
)

var RegionSpecifier_RegionSpecifierType_name = map[int32]string{
	1: "REGION_NAME",
	2: "ENCODED_REGION_NAME",
}

var RegionSpecifier_RegionSpecifierType_value = map[string]int32{
	"REGION_NAME":         1,
	"ENCODED_REGION_NAME": 2,
}

func (x RegionSpecifier_RegionSpecifierType) Enum() *RegionSpecifier_RegionSpecifierType {
	p := new(RegionSpecifier_RegionSpecifierType)
	*p = x
	return p
}

func (x RegionSpecifier_RegionSpecifierType) String() string {
	return proto.EnumName(RegionSpecifier_RegionSpecifierType_name, int32(x))
}

func (x *RegionSpecifier_RegionSpecifierType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RegionSpecifier_RegionSpecifierType_value, data, "RegionSpecifier_RegionSpecifierType")
	if err != nil {
		return err
	}
	*x = RegionSpecifier_RegionSpecifierType(value)
	return nil
}

func (RegionSpecifier_RegionSpecifierType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{6, 0}
}

//*
// Table Name
type TableName struct {
	Namespace            []byte   `protobuf:"bytes,1,req,name=namespace" json:"namespace,omitempty"`
	Qualifier            []byte   `protobuf:"bytes,2,req,name=qualifier" json:"qualifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableName) Reset()         { *m = TableName{} }
func (m *TableName) String() string { return proto.CompactTextString(m) }
func (*TableName) ProtoMessage()    {}
func (*TableName) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{0}
}

func (m *TableName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableName.Unmarshal(m, b)
}
func (m *TableName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableName.Marshal(b, m, deterministic)
}
func (m *TableName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableName.Merge(m, src)
}
func (m *TableName) XXX_Size() int {
	return xxx_messageInfo_TableName.Size(m)
}
func (m *TableName) XXX_DiscardUnknown() {
	xxx_messageInfo_TableName.DiscardUnknown(m)
}

var xxx_messageInfo_TableName proto.InternalMessageInfo

func (m *TableName) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *TableName) GetQualifier() []byte {
	if m != nil {
		return m.Qualifier
	}
	return nil
}

//*
// Table Schema
// Inspired by the rest TableSchema
type TableSchema struct {
	TableName            *TableName            `protobuf:"bytes,1,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	Attributes           []*BytesBytesPair     `protobuf:"bytes,2,rep,name=attributes" json:"attributes,omitempty"`
	ColumnFamilies       []*ColumnFamilySchema `protobuf:"bytes,3,rep,name=column_families,json=columnFamilies" json:"column_families,omitempty"`
	Configuration        []*NameStringPair     `protobuf:"bytes,4,rep,name=configuration" json:"configuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TableSchema) Reset()         { *m = TableSchema{} }
func (m *TableSchema) String() string { return proto.CompactTextString(m) }
func (*TableSchema) ProtoMessage()    {}
func (*TableSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{1}
}

func (m *TableSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableSchema.Unmarshal(m, b)
}
func (m *TableSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableSchema.Marshal(b, m, deterministic)
}
func (m *TableSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableSchema.Merge(m, src)
}
func (m *TableSchema) XXX_Size() int {
	return xxx_messageInfo_TableSchema.Size(m)
}
func (m *TableSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_TableSchema.DiscardUnknown(m)
}

var xxx_messageInfo_TableSchema proto.InternalMessageInfo

func (m *TableSchema) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *TableSchema) GetAttributes() []*BytesBytesPair {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *TableSchema) GetColumnFamilies() []*ColumnFamilySchema {
	if m != nil {
		return m.ColumnFamilies
	}
	return nil
}

func (m *TableSchema) GetConfiguration() []*NameStringPair {
	if m != nil {
		return m.Configuration
	}
	return nil
}

//* Denotes state of the table
type TableState struct {
	// This is the table's state.
	State                *TableState_State `protobuf:"varint,1,req,name=state,enum=hbase.pb.TableState_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TableState) Reset()         { *m = TableState{} }
func (m *TableState) String() string { return proto.CompactTextString(m) }
func (*TableState) ProtoMessage()    {}
func (*TableState) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{2}
}

func (m *TableState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableState.Unmarshal(m, b)
}
func (m *TableState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableState.Marshal(b, m, deterministic)
}
func (m *TableState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableState.Merge(m, src)
}
func (m *TableState) XXX_Size() int {
	return xxx_messageInfo_TableState.Size(m)
}
func (m *TableState) XXX_DiscardUnknown() {
	xxx_messageInfo_TableState.DiscardUnknown(m)
}

var xxx_messageInfo_TableState proto.InternalMessageInfo

func (m *TableState) GetState() TableState_State {
	if m != nil && m.State != nil {
		return *m.State
	}
	return TableState_ENABLED
}

//*
// Column Family Schema
// Inspired by the rest ColumSchemaMessage
type ColumnFamilySchema struct {
	Name                 []byte            `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Attributes           []*BytesBytesPair `protobuf:"bytes,2,rep,name=attributes" json:"attributes,omitempty"`
	Configuration        []*NameStringPair `protobuf:"bytes,3,rep,name=configuration" json:"configuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ColumnFamilySchema) Reset()         { *m = ColumnFamilySchema{} }
func (m *ColumnFamilySchema) String() string { return proto.CompactTextString(m) }
func (*ColumnFamilySchema) ProtoMessage()    {}
func (*ColumnFamilySchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{3}
}

func (m *ColumnFamilySchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColumnFamilySchema.Unmarshal(m, b)
}
func (m *ColumnFamilySchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColumnFamilySchema.Marshal(b, m, deterministic)
}
func (m *ColumnFamilySchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColumnFamilySchema.Merge(m, src)
}
func (m *ColumnFamilySchema) XXX_Size() int {
	return xxx_messageInfo_ColumnFamilySchema.Size(m)
}
func (m *ColumnFamilySchema) XXX_DiscardUnknown() {
	xxx_messageInfo_ColumnFamilySchema.DiscardUnknown(m)
}

var xxx_messageInfo_ColumnFamilySchema proto.InternalMessageInfo

func (m *ColumnFamilySchema) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ColumnFamilySchema) GetAttributes() []*BytesBytesPair {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *ColumnFamilySchema) GetConfiguration() []*NameStringPair {
	if m != nil {
		return m.Configuration
	}
	return nil
}

//*
// Protocol buffer version of HRegionInfo.
type RegionInfo struct {
	RegionId             *uint64    `protobuf:"varint,1,req,name=region_id,json=regionId" json:"region_id,omitempty"`
	TableName            *TableName `protobuf:"bytes,2,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	StartKey             []byte     `protobuf:"bytes,3,opt,name=start_key,json=startKey" json:"start_key,omitempty"`
	EndKey               []byte     `protobuf:"bytes,4,opt,name=end_key,json=endKey" json:"end_key,omitempty"`
	Offline              *bool      `protobuf:"varint,5,opt,name=offline" json:"offline,omitempty"`
	Split                *bool      `protobuf:"varint,6,opt,name=split" json:"split,omitempty"`
	ReplicaId            *int32     `protobuf:"varint,7,opt,name=replica_id,json=replicaId,def=0" json:"replica_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RegionInfo) Reset()         { *m = RegionInfo{} }
func (m *RegionInfo) String() string { return proto.CompactTextString(m) }
func (*RegionInfo) ProtoMessage()    {}
func (*RegionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{4}
}

func (m *RegionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegionInfo.Unmarshal(m, b)
}
func (m *RegionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegionInfo.Marshal(b, m, deterministic)
}
func (m *RegionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegionInfo.Merge(m, src)
}
func (m *RegionInfo) XXX_Size() int {
	return xxx_messageInfo_RegionInfo.Size(m)
}
func (m *RegionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RegionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RegionInfo proto.InternalMessageInfo

const Default_RegionInfo_ReplicaId int32 = 0

func (m *RegionInfo) GetRegionId() uint64 {
	if m != nil && m.RegionId != nil {
		return *m.RegionId
	}
	return 0
}

func (m *RegionInfo) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *RegionInfo) GetStartKey() []byte {
	if m != nil {
		return m.StartKey
	}
	return nil
}

func (m *RegionInfo) GetEndKey() []byte {
	if m != nil {
		return m.EndKey
	}
	return nil
}

func (m *RegionInfo) GetOffline() bool {
	if m != nil && m.Offline != nil {
		return *m.Offline
	}
	return false
}

func (m *RegionInfo) GetSplit() bool {
	if m != nil && m.Split != nil {
		return *m.Split
	}
	return false
}

func (m *RegionInfo) GetReplicaId() int32 {
	if m != nil && m.ReplicaId != nil {
		return *m.ReplicaId
	}
	return Default_RegionInfo_ReplicaId
}

//*
// Protocol buffer for favored nodes
type FavoredNodes struct {
	FavoredNode          []*ServerName `protobuf:"bytes,1,rep,name=favored_node,json=favoredNode" json:"favored_node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FavoredNodes) Reset()         { *m = FavoredNodes{} }
func (m *FavoredNodes) String() string { return proto.CompactTextString(m) }
func (*FavoredNodes) ProtoMessage()    {}
func (*FavoredNodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{5}
}

func (m *FavoredNodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FavoredNodes.Unmarshal(m, b)
}
func (m *FavoredNodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FavoredNodes.Marshal(b, m, deterministic)
}
func (m *FavoredNodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FavoredNodes.Merge(m, src)
}
func (m *FavoredNodes) XXX_Size() int {
	return xxx_messageInfo_FavoredNodes.Size(m)
}
func (m *FavoredNodes) XXX_DiscardUnknown() {
	xxx_messageInfo_FavoredNodes.DiscardUnknown(m)
}

var xxx_messageInfo_FavoredNodes proto.InternalMessageInfo

func (m *FavoredNodes) GetFavoredNode() []*ServerName {
	if m != nil {
		return m.FavoredNode
	}
	return nil
}

//*
// Container protocol buffer to specify a region.
// You can specify region by region name, or the hash
// of the region name, which is known as encoded
// region name.
type RegionSpecifier struct {
	Type                 *RegionSpecifier_RegionSpecifierType `protobuf:"varint,1,req,name=type,enum=hbase.pb.RegionSpecifier_RegionSpecifierType" json:"type,omitempty"`
	Value                []byte                               `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *RegionSpecifier) Reset()         { *m = RegionSpecifier{} }
func (m *RegionSpecifier) String() string { return proto.CompactTextString(m) }
func (*RegionSpecifier) ProtoMessage()    {}
func (*RegionSpecifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{6}
}

func (m *RegionSpecifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegionSpecifier.Unmarshal(m, b)
}
func (m *RegionSpecifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegionSpecifier.Marshal(b, m, deterministic)
}
func (m *RegionSpecifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegionSpecifier.Merge(m, src)
}
func (m *RegionSpecifier) XXX_Size() int {
	return xxx_messageInfo_RegionSpecifier.Size(m)
}
func (m *RegionSpecifier) XXX_DiscardUnknown() {
	xxx_messageInfo_RegionSpecifier.DiscardUnknown(m)
}

var xxx_messageInfo_RegionSpecifier proto.InternalMessageInfo

func (m *RegionSpecifier) GetType() RegionSpecifier_RegionSpecifierType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return RegionSpecifier_REGION_NAME
}

func (m *RegionSpecifier) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

//*
// A range of time. Both from and to are Java time
// stamp in milliseconds. If you don't specify a time
// range, it means all time.  By default, if not
// specified, from = 0, and to = Long.MAX_VALUE
type TimeRange struct {
	From                 *uint64  `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	To                   *uint64  `protobuf:"varint,2,opt,name=to" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeRange) Reset()         { *m = TimeRange{} }
func (m *TimeRange) String() string { return proto.CompactTextString(m) }
func (*TimeRange) ProtoMessage()    {}
func (*TimeRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{7}
}

func (m *TimeRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeRange.Unmarshal(m, b)
}
func (m *TimeRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeRange.Marshal(b, m, deterministic)
}
func (m *TimeRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeRange.Merge(m, src)
}
func (m *TimeRange) XXX_Size() int {
	return xxx_messageInfo_TimeRange.Size(m)
}
func (m *TimeRange) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeRange.DiscardUnknown(m)
}

var xxx_messageInfo_TimeRange proto.InternalMessageInfo

func (m *TimeRange) GetFrom() uint64 {
	if m != nil && m.From != nil {
		return *m.From
	}
	return 0
}

func (m *TimeRange) GetTo() uint64 {
	if m != nil && m.To != nil {
		return *m.To
	}
	return 0
}

type TimeRangeTracker struct {
	From                 *uint64  `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	To                   *uint64  `protobuf:"varint,2,opt,name=to" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeRangeTracker) Reset()         { *m = TimeRangeTracker{} }
func (m *TimeRangeTracker) String() string { return proto.CompactTextString(m) }
func (*TimeRangeTracker) ProtoMessage()    {}
func (*TimeRangeTracker) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{8}
}

func (m *TimeRangeTracker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeRangeTracker.Unmarshal(m, b)
}
func (m *TimeRangeTracker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeRangeTracker.Marshal(b, m, deterministic)
}
func (m *TimeRangeTracker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeRangeTracker.Merge(m, src)
}
func (m *TimeRangeTracker) XXX_Size() int {
	return xxx_messageInfo_TimeRangeTracker.Size(m)
}
func (m *TimeRangeTracker) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeRangeTracker.DiscardUnknown(m)
}

var xxx_messageInfo_TimeRangeTracker proto.InternalMessageInfo

func (m *TimeRangeTracker) GetFrom() uint64 {
	if m != nil && m.From != nil {
		return *m.From
	}
	return 0
}

func (m *TimeRangeTracker) GetTo() uint64 {
	if m != nil && m.To != nil {
		return *m.To
	}
	return 0
}

// ColumnFamily Specific TimeRange
type ColumnFamilyTimeRange struct {
	ColumnFamily         []byte     `protobuf:"bytes,1,req,name=column_family,json=columnFamily" json:"column_family,omitempty"`
	TimeRange            *TimeRange `protobuf:"bytes,2,req,name=time_range,json=timeRange" json:"time_range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ColumnFamilyTimeRange) Reset()         { *m = ColumnFamilyTimeRange{} }
func (m *ColumnFamilyTimeRange) String() string { return proto.CompactTextString(m) }
func (*ColumnFamilyTimeRange) ProtoMessage()    {}
func (*ColumnFamilyTimeRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{9}
}

func (m *ColumnFamilyTimeRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColumnFamilyTimeRange.Unmarshal(m, b)
}
func (m *ColumnFamilyTimeRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColumnFamilyTimeRange.Marshal(b, m, deterministic)
}
func (m *ColumnFamilyTimeRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColumnFamilyTimeRange.Merge(m, src)
}
func (m *ColumnFamilyTimeRange) XXX_Size() int {
	return xxx_messageInfo_ColumnFamilyTimeRange.Size(m)
}
func (m *ColumnFamilyTimeRange) XXX_DiscardUnknown() {
	xxx_messageInfo_ColumnFamilyTimeRange.DiscardUnknown(m)
}

var xxx_messageInfo_ColumnFamilyTimeRange proto.InternalMessageInfo

func (m *ColumnFamilyTimeRange) GetColumnFamily() []byte {
	if m != nil {
		return m.ColumnFamily
	}
	return nil
}

func (m *ColumnFamilyTimeRange) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

//*
// Protocol buffer version of ServerName
type ServerName struct {
	HostName             *string  `protobuf:"bytes,1,req,name=host_name,json=hostName" json:"host_name,omitempty"`
	Port                 *uint32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	StartCode            *uint64  `protobuf:"varint,3,opt,name=start_code,json=startCode" json:"start_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerName) Reset()         { *m = ServerName{} }
func (m *ServerName) String() string { return proto.CompactTextString(m) }
func (*ServerName) ProtoMessage()    {}
func (*ServerName) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{10}
}

func (m *ServerName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerName.Unmarshal(m, b)
}
func (m *ServerName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerName.Marshal(b, m, deterministic)
}
func (m *ServerName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerName.Merge(m, src)
}
func (m *ServerName) XXX_Size() int {
	return xxx_messageInfo_ServerName.Size(m)
}
func (m *ServerName) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerName.DiscardUnknown(m)
}

var xxx_messageInfo_ServerName proto.InternalMessageInfo

func (m *ServerName) GetHostName() string {
	if m != nil && m.HostName != nil {
		return *m.HostName
	}
	return ""
}

func (m *ServerName) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *ServerName) GetStartCode() uint64 {
	if m != nil && m.StartCode != nil {
		return *m.StartCode
	}
	return 0
}

type Coprocessor struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coprocessor) Reset()         { *m = Coprocessor{} }
func (m *Coprocessor) String() string { return proto.CompactTextString(m) }
func (*Coprocessor) ProtoMessage()    {}
func (*Coprocessor) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{11}
}

func (m *Coprocessor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coprocessor.Unmarshal(m, b)
}
func (m *Coprocessor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coprocessor.Marshal(b, m, deterministic)
}
func (m *Coprocessor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coprocessor.Merge(m, src)
}
func (m *Coprocessor) XXX_Size() int {
	return xxx_messageInfo_Coprocessor.Size(m)
}
func (m *Coprocessor) XXX_DiscardUnknown() {
	xxx_messageInfo_Coprocessor.DiscardUnknown(m)
}

var xxx_messageInfo_Coprocessor proto.InternalMessageInfo

func (m *Coprocessor) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type NameStringPair struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameStringPair) Reset()         { *m = NameStringPair{} }
func (m *NameStringPair) String() string { return proto.CompactTextString(m) }
func (*NameStringPair) ProtoMessage()    {}
func (*NameStringPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{12}
}

func (m *NameStringPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameStringPair.Unmarshal(m, b)
}
func (m *NameStringPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameStringPair.Marshal(b, m, deterministic)
}
func (m *NameStringPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameStringPair.Merge(m, src)
}
func (m *NameStringPair) XXX_Size() int {
	return xxx_messageInfo_NameStringPair.Size(m)
}
func (m *NameStringPair) XXX_DiscardUnknown() {
	xxx_messageInfo_NameStringPair.DiscardUnknown(m)
}

var xxx_messageInfo_NameStringPair proto.InternalMessageInfo

func (m *NameStringPair) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *NameStringPair) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type NameBytesPair struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameBytesPair) Reset()         { *m = NameBytesPair{} }
func (m *NameBytesPair) String() string { return proto.CompactTextString(m) }
func (*NameBytesPair) ProtoMessage()    {}
func (*NameBytesPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{13}
}

func (m *NameBytesPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameBytesPair.Unmarshal(m, b)
}
func (m *NameBytesPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameBytesPair.Marshal(b, m, deterministic)
}
func (m *NameBytesPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameBytesPair.Merge(m, src)
}
func (m *NameBytesPair) XXX_Size() int {
	return xxx_messageInfo_NameBytesPair.Size(m)
}
func (m *NameBytesPair) XXX_DiscardUnknown() {
	xxx_messageInfo_NameBytesPair.DiscardUnknown(m)
}

var xxx_messageInfo_NameBytesPair proto.InternalMessageInfo

func (m *NameBytesPair) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *NameBytesPair) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type BytesBytesPair struct {
	First                []byte   `protobuf:"bytes,1,req,name=first" json:"first,omitempty"`
	Second               []byte   `protobuf:"bytes,2,req,name=second" json:"second,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BytesBytesPair) Reset()         { *m = BytesBytesPair{} }
func (m *BytesBytesPair) String() string { return proto.CompactTextString(m) }
func (*BytesBytesPair) ProtoMessage()    {}
func (*BytesBytesPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{14}
}

func (m *BytesBytesPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BytesBytesPair.Unmarshal(m, b)
}
func (m *BytesBytesPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BytesBytesPair.Marshal(b, m, deterministic)
}
func (m *BytesBytesPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BytesBytesPair.Merge(m, src)
}
func (m *BytesBytesPair) XXX_Size() int {
	return xxx_messageInfo_BytesBytesPair.Size(m)
}
func (m *BytesBytesPair) XXX_DiscardUnknown() {
	xxx_messageInfo_BytesBytesPair.DiscardUnknown(m)
}

var xxx_messageInfo_BytesBytesPair proto.InternalMessageInfo

func (m *BytesBytesPair) GetFirst() []byte {
	if m != nil {
		return m.First
	}
	return nil
}

func (m *BytesBytesPair) GetSecond() []byte {
	if m != nil {
		return m.Second
	}
	return nil
}

type NameInt64Pair struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value                *int64   `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameInt64Pair) Reset()         { *m = NameInt64Pair{} }
func (m *NameInt64Pair) String() string { return proto.CompactTextString(m) }
func (*NameInt64Pair) ProtoMessage()    {}
func (*NameInt64Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{15}
}

func (m *NameInt64Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameInt64Pair.Unmarshal(m, b)
}
func (m *NameInt64Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameInt64Pair.Marshal(b, m, deterministic)
}
func (m *NameInt64Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameInt64Pair.Merge(m, src)
}
func (m *NameInt64Pair) XXX_Size() int {
	return xxx_messageInfo_NameInt64Pair.Size(m)
}
func (m *NameInt64Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_NameInt64Pair.DiscardUnknown(m)
}

var xxx_messageInfo_NameInt64Pair proto.InternalMessageInfo

func (m *NameInt64Pair) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *NameInt64Pair) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

//*
// Description of the distributed procedure to take
type ProcedureDescription struct {
	Signature            *string           `protobuf:"bytes,1,req,name=signature" json:"signature,omitempty"`
	Instance             *string           `protobuf:"bytes,2,opt,name=instance" json:"instance,omitempty"`
	CreationTime         *int64            `protobuf:"varint,3,opt,name=creation_time,json=creationTime,def=0" json:"creation_time,omitempty"`
	Configuration        []*NameStringPair `protobuf:"bytes,4,rep,name=configuration" json:"configuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProcedureDescription) Reset()         { *m = ProcedureDescription{} }
func (m *ProcedureDescription) String() string { return proto.CompactTextString(m) }
func (*ProcedureDescription) ProtoMessage()    {}
func (*ProcedureDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{16}
}

func (m *ProcedureDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcedureDescription.Unmarshal(m, b)
}
func (m *ProcedureDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcedureDescription.Marshal(b, m, deterministic)
}
func (m *ProcedureDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcedureDescription.Merge(m, src)
}
func (m *ProcedureDescription) XXX_Size() int {
	return xxx_messageInfo_ProcedureDescription.Size(m)
}
func (m *ProcedureDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcedureDescription.DiscardUnknown(m)
}

var xxx_messageInfo_ProcedureDescription proto.InternalMessageInfo

const Default_ProcedureDescription_CreationTime int64 = 0

func (m *ProcedureDescription) GetSignature() string {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return ""
}

func (m *ProcedureDescription) GetInstance() string {
	if m != nil && m.Instance != nil {
		return *m.Instance
	}
	return ""
}

func (m *ProcedureDescription) GetCreationTime() int64 {
	if m != nil && m.CreationTime != nil {
		return *m.CreationTime
	}
	return Default_ProcedureDescription_CreationTime
}

func (m *ProcedureDescription) GetConfiguration() []*NameStringPair {
	if m != nil {
		return m.Configuration
	}
	return nil
}

type EmptyMsg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyMsg) Reset()         { *m = EmptyMsg{} }
func (m *EmptyMsg) String() string { return proto.CompactTextString(m) }
func (*EmptyMsg) ProtoMessage()    {}
func (*EmptyMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{17}
}

func (m *EmptyMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyMsg.Unmarshal(m, b)
}
func (m *EmptyMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyMsg.Marshal(b, m, deterministic)
}
func (m *EmptyMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyMsg.Merge(m, src)
}
func (m *EmptyMsg) XXX_Size() int {
	return xxx_messageInfo_EmptyMsg.Size(m)
}
func (m *EmptyMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyMsg proto.InternalMessageInfo

type LongMsg struct {
	LongMsg              *int64   `protobuf:"varint,1,req,name=long_msg,json=longMsg" json:"long_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongMsg) Reset()         { *m = LongMsg{} }
func (m *LongMsg) String() string { return proto.CompactTextString(m) }
func (*LongMsg) ProtoMessage()    {}
func (*LongMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{18}
}

func (m *LongMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongMsg.Unmarshal(m, b)
}
func (m *LongMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongMsg.Marshal(b, m, deterministic)
}
func (m *LongMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongMsg.Merge(m, src)
}
func (m *LongMsg) XXX_Size() int {
	return xxx_messageInfo_LongMsg.Size(m)
}
func (m *LongMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_LongMsg.DiscardUnknown(m)
}

var xxx_messageInfo_LongMsg proto.InternalMessageInfo

func (m *LongMsg) GetLongMsg() int64 {
	if m != nil && m.LongMsg != nil {
		return *m.LongMsg
	}
	return 0
}

type DoubleMsg struct {
	DoubleMsg            *float64 `protobuf:"fixed64,1,req,name=double_msg,json=doubleMsg" json:"double_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoubleMsg) Reset()         { *m = DoubleMsg{} }
func (m *DoubleMsg) String() string { return proto.CompactTextString(m) }
func (*DoubleMsg) ProtoMessage()    {}
func (*DoubleMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{19}
}

func (m *DoubleMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoubleMsg.Unmarshal(m, b)
}
func (m *DoubleMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoubleMsg.Marshal(b, m, deterministic)
}
func (m *DoubleMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoubleMsg.Merge(m, src)
}
func (m *DoubleMsg) XXX_Size() int {
	return xxx_messageInfo_DoubleMsg.Size(m)
}
func (m *DoubleMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_DoubleMsg.DiscardUnknown(m)
}

var xxx_messageInfo_DoubleMsg proto.InternalMessageInfo

func (m *DoubleMsg) GetDoubleMsg() float64 {
	if m != nil && m.DoubleMsg != nil {
		return *m.DoubleMsg
	}
	return 0
}

type BigDecimalMsg struct {
	BigdecimalMsg        []byte   `protobuf:"bytes,1,req,name=bigdecimal_msg,json=bigdecimalMsg" json:"bigdecimal_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigDecimalMsg) Reset()         { *m = BigDecimalMsg{} }
func (m *BigDecimalMsg) String() string { return proto.CompactTextString(m) }
func (*BigDecimalMsg) ProtoMessage()    {}
func (*BigDecimalMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{20}
}

func (m *BigDecimalMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigDecimalMsg.Unmarshal(m, b)
}
func (m *BigDecimalMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigDecimalMsg.Marshal(b, m, deterministic)
}
func (m *BigDecimalMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigDecimalMsg.Merge(m, src)
}
func (m *BigDecimalMsg) XXX_Size() int {
	return xxx_messageInfo_BigDecimalMsg.Size(m)
}
func (m *BigDecimalMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BigDecimalMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BigDecimalMsg proto.InternalMessageInfo

func (m *BigDecimalMsg) GetBigdecimalMsg() []byte {
	if m != nil {
		return m.BigdecimalMsg
	}
	return nil
}

type UUID struct {
	LeastSigBits         *uint64  `protobuf:"varint,1,req,name=least_sig_bits,json=leastSigBits" json:"least_sig_bits,omitempty"`
	MostSigBits          *uint64  `protobuf:"varint,2,req,name=most_sig_bits,json=mostSigBits" json:"most_sig_bits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UUID) Reset()         { *m = UUID{} }
func (m *UUID) String() string { return proto.CompactTextString(m) }
func (*UUID) ProtoMessage()    {}
func (*UUID) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{21}
}

func (m *UUID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UUID.Unmarshal(m, b)
}
func (m *UUID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UUID.Marshal(b, m, deterministic)
}
func (m *UUID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UUID.Merge(m, src)
}
func (m *UUID) XXX_Size() int {
	return xxx_messageInfo_UUID.Size(m)
}
func (m *UUID) XXX_DiscardUnknown() {
	xxx_messageInfo_UUID.DiscardUnknown(m)
}

var xxx_messageInfo_UUID proto.InternalMessageInfo

func (m *UUID) GetLeastSigBits() uint64 {
	if m != nil && m.LeastSigBits != nil {
		return *m.LeastSigBits
	}
	return 0
}

func (m *UUID) GetMostSigBits() uint64 {
	if m != nil && m.MostSigBits != nil {
		return *m.MostSigBits
	}
	return 0
}

type NamespaceDescriptor struct {
	Name                 []byte            `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Configuration        []*NameStringPair `protobuf:"bytes,2,rep,name=configuration" json:"configuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NamespaceDescriptor) Reset()         { *m = NamespaceDescriptor{} }
func (m *NamespaceDescriptor) String() string { return proto.CompactTextString(m) }
func (*NamespaceDescriptor) ProtoMessage()    {}
func (*NamespaceDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{22}
}

func (m *NamespaceDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceDescriptor.Unmarshal(m, b)
}
func (m *NamespaceDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceDescriptor.Marshal(b, m, deterministic)
}
func (m *NamespaceDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceDescriptor.Merge(m, src)
}
func (m *NamespaceDescriptor) XXX_Size() int {
	return xxx_messageInfo_NamespaceDescriptor.Size(m)
}
func (m *NamespaceDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceDescriptor proto.InternalMessageInfo

func (m *NamespaceDescriptor) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *NamespaceDescriptor) GetConfiguration() []*NameStringPair {
	if m != nil {
		return m.Configuration
	}
	return nil
}

// Rpc client version info proto. Included in ConnectionHeader on connection setup
type VersionInfo struct {
	Version              *string  `protobuf:"bytes,1,req,name=version" json:"version,omitempty"`
	Url                  *string  `protobuf:"bytes,2,req,name=url" json:"url,omitempty"`
	Revision             *string  `protobuf:"bytes,3,req,name=revision" json:"revision,omitempty"`
	User                 *string  `protobuf:"bytes,4,req,name=user" json:"user,omitempty"`
	Date                 *string  `protobuf:"bytes,5,req,name=date" json:"date,omitempty"`
	SrcChecksum          *string  `protobuf:"bytes,6,req,name=src_checksum,json=srcChecksum" json:"src_checksum,omitempty"`
	VersionMajor         *uint32  `protobuf:"varint,7,opt,name=version_major,json=versionMajor" json:"version_major,omitempty"`
	VersionMinor         *uint32  `protobuf:"varint,8,opt,name=version_minor,json=versionMinor" json:"version_minor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionInfo) Reset()         { *m = VersionInfo{} }
func (m *VersionInfo) String() string { return proto.CompactTextString(m) }
func (*VersionInfo) ProtoMessage()    {}
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{23}
}

func (m *VersionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionInfo.Unmarshal(m, b)
}
func (m *VersionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionInfo.Marshal(b, m, deterministic)
}
func (m *VersionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionInfo.Merge(m, src)
}
func (m *VersionInfo) XXX_Size() int {
	return xxx_messageInfo_VersionInfo.Size(m)
}
func (m *VersionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VersionInfo proto.InternalMessageInfo

func (m *VersionInfo) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *VersionInfo) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *VersionInfo) GetRevision() string {
	if m != nil && m.Revision != nil {
		return *m.Revision
	}
	return ""
}

func (m *VersionInfo) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *VersionInfo) GetDate() string {
	if m != nil && m.Date != nil {
		return *m.Date
	}
	return ""
}

func (m *VersionInfo) GetSrcChecksum() string {
	if m != nil && m.SrcChecksum != nil {
		return *m.SrcChecksum
	}
	return ""
}

func (m *VersionInfo) GetVersionMajor() uint32 {
	if m != nil && m.VersionMajor != nil {
		return *m.VersionMajor
	}
	return 0
}

func (m *VersionInfo) GetVersionMinor() uint32 {
	if m != nil && m.VersionMinor != nil {
		return *m.VersionMinor
	}
	return 0
}

//*
// Description of the region server info
type RegionServerInfo struct {
	InfoPort             *int32       `protobuf:"varint,1,opt,name=infoPort" json:"infoPort,omitempty"`
	VersionInfo          *VersionInfo `protobuf:"bytes,2,opt,name=version_info,json=versionInfo" json:"version_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegionServerInfo) Reset()         { *m = RegionServerInfo{} }
func (m *RegionServerInfo) String() string { return proto.CompactTextString(m) }
func (*RegionServerInfo) ProtoMessage()    {}
func (*RegionServerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{24}
}

func (m *RegionServerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegionServerInfo.Unmarshal(m, b)
}
func (m *RegionServerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegionServerInfo.Marshal(b, m, deterministic)
}
func (m *RegionServerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegionServerInfo.Merge(m, src)
}
func (m *RegionServerInfo) XXX_Size() int {
	return xxx_messageInfo_RegionServerInfo.Size(m)
}
func (m *RegionServerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RegionServerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RegionServerInfo proto.InternalMessageInfo

func (m *RegionServerInfo) GetInfoPort() int32 {
	if m != nil && m.InfoPort != nil {
		return *m.InfoPort
	}
	return 0
}

func (m *RegionServerInfo) GetVersionInfo() *VersionInfo {
	if m != nil {
		return m.VersionInfo
	}
	return nil
}

type RegionExceptionMessage struct {
	Region               *RegionSpecifier `protobuf:"bytes,1,req,name=region" json:"region,omitempty"`
	Exception            *NameBytesPair   `protobuf:"bytes,2,req,name=exception" json:"exception,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RegionExceptionMessage) Reset()         { *m = RegionExceptionMessage{} }
func (m *RegionExceptionMessage) String() string { return proto.CompactTextString(m) }
func (*RegionExceptionMessage) ProtoMessage()    {}
func (*RegionExceptionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{25}
}

func (m *RegionExceptionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegionExceptionMessage.Unmarshal(m, b)
}
func (m *RegionExceptionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegionExceptionMessage.Marshal(b, m, deterministic)
}
func (m *RegionExceptionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegionExceptionMessage.Merge(m, src)
}
func (m *RegionExceptionMessage) XXX_Size() int {
	return xxx_messageInfo_RegionExceptionMessage.Size(m)
}
func (m *RegionExceptionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RegionExceptionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RegionExceptionMessage proto.InternalMessageInfo

func (m *RegionExceptionMessage) GetRegion() *RegionSpecifier {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *RegionExceptionMessage) GetException() *NameBytesPair {
	if m != nil {
		return m.Exception
	}
	return nil
}

type CacheEvictionStats struct {
	EvictedBlocks        *int64                    `protobuf:"varint,1,opt,name=evicted_blocks,json=evictedBlocks" json:"evicted_blocks,omitempty"`
	BytesEvicted         *int64                    `protobuf:"varint,2,opt,name=bytes_evicted,json=bytesEvicted" json:"bytes_evicted,omitempty"`
	MaxCacheSize         *int64                    `protobuf:"varint,3,opt,name=max_cache_size,json=maxCacheSize" json:"max_cache_size,omitempty"`
	Exception            []*RegionExceptionMessage `protobuf:"bytes,4,rep,name=exception" json:"exception,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *CacheEvictionStats) Reset()         { *m = CacheEvictionStats{} }
func (m *CacheEvictionStats) String() string { return proto.CompactTextString(m) }
func (*CacheEvictionStats) ProtoMessage()    {}
func (*CacheEvictionStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{26}
}

func (m *CacheEvictionStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheEvictionStats.Unmarshal(m, b)
}
func (m *CacheEvictionStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheEvictionStats.Marshal(b, m, deterministic)
}
func (m *CacheEvictionStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheEvictionStats.Merge(m, src)
}
func (m *CacheEvictionStats) XXX_Size() int {
	return xxx_messageInfo_CacheEvictionStats.Size(m)
}
func (m *CacheEvictionStats) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheEvictionStats.DiscardUnknown(m)
}

var xxx_messageInfo_CacheEvictionStats proto.InternalMessageInfo

func (m *CacheEvictionStats) GetEvictedBlocks() int64 {
	if m != nil && m.EvictedBlocks != nil {
		return *m.EvictedBlocks
	}
	return 0
}

func (m *CacheEvictionStats) GetBytesEvicted() int64 {
	if m != nil && m.BytesEvicted != nil {
		return *m.BytesEvicted
	}
	return 0
}

func (m *CacheEvictionStats) GetMaxCacheSize() int64 {
	if m != nil && m.MaxCacheSize != nil {
		return *m.MaxCacheSize
	}
	return 0
}

func (m *CacheEvictionStats) GetException() []*RegionExceptionMessage {
	if m != nil {
		return m.Exception
	}
	return nil
}

type RegionLocation struct {
	RegionInfo           *RegionInfo `protobuf:"bytes,1,req,name=region_info,json=regionInfo" json:"region_info,omitempty"`
	ServerName           *ServerName `protobuf:"bytes,2,opt,name=server_name,json=serverName" json:"server_name,omitempty"`
	SeqNum               *int64      `protobuf:"varint,3,req,name=seq_num,json=seqNum" json:"seq_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RegionLocation) Reset()         { *m = RegionLocation{} }
func (m *RegionLocation) String() string { return proto.CompactTextString(m) }
func (*RegionLocation) ProtoMessage()    {}
func (*RegionLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f11dfa70e726da0, []int{27}
}

func (m *RegionLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegionLocation.Unmarshal(m, b)
}
func (m *RegionLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegionLocation.Marshal(b, m, deterministic)
}
func (m *RegionLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegionLocation.Merge(m, src)
}
func (m *RegionLocation) XXX_Size() int {
	return xxx_messageInfo_RegionLocation.Size(m)
}
func (m *RegionLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_RegionLocation.DiscardUnknown(m)
}

var xxx_messageInfo_RegionLocation proto.InternalMessageInfo

func (m *RegionLocation) GetRegionInfo() *RegionInfo {
	if m != nil {
		return m.RegionInfo
	}
	return nil
}

func (m *RegionLocation) GetServerName() *ServerName {
	if m != nil {
		return m.ServerName
	}
	return nil
}

func (m *RegionLocation) GetSeqNum() int64 {
	if m != nil && m.SeqNum != nil {
		return *m.SeqNum
	}
	return 0
}

func init() {
	proto.RegisterEnum("hbase.pb.CompareType", CompareType_name, CompareType_value)
	proto.RegisterEnum("hbase.pb.TimeUnit", TimeUnit_name, TimeUnit_value)
	proto.RegisterEnum("hbase.pb.TableState_State", TableState_State_name, TableState_State_value)
	proto.RegisterEnum("hbase.pb.RegionSpecifier_RegionSpecifierType", RegionSpecifier_RegionSpecifierType_name, RegionSpecifier_RegionSpecifierType_value)
	proto.RegisterType((*TableName)(nil), "hbase.pb.TableName")
	proto.RegisterType((*TableSchema)(nil), "hbase.pb.TableSchema")
	proto.RegisterType((*TableState)(nil), "hbase.pb.TableState")
	proto.RegisterType((*ColumnFamilySchema)(nil), "hbase.pb.ColumnFamilySchema")
	proto.RegisterType((*RegionInfo)(nil), "hbase.pb.RegionInfo")
	proto.RegisterType((*FavoredNodes)(nil), "hbase.pb.FavoredNodes")
	proto.RegisterType((*RegionSpecifier)(nil), "hbase.pb.RegionSpecifier")
	proto.RegisterType((*TimeRange)(nil), "hbase.pb.TimeRange")
	proto.RegisterType((*TimeRangeTracker)(nil), "hbase.pb.TimeRangeTracker")
	proto.RegisterType((*ColumnFamilyTimeRange)(nil), "hbase.pb.ColumnFamilyTimeRange")
	proto.RegisterType((*ServerName)(nil), "hbase.pb.ServerName")
	proto.RegisterType((*Coprocessor)(nil), "hbase.pb.Coprocessor")
	proto.RegisterType((*NameStringPair)(nil), "hbase.pb.NameStringPair")
	proto.RegisterType((*NameBytesPair)(nil), "hbase.pb.NameBytesPair")
	proto.RegisterType((*BytesBytesPair)(nil), "hbase.pb.BytesBytesPair")
	proto.RegisterType((*NameInt64Pair)(nil), "hbase.pb.NameInt64Pair")
	proto.RegisterType((*ProcedureDescription)(nil), "hbase.pb.ProcedureDescription")
	proto.RegisterType((*EmptyMsg)(nil), "hbase.pb.EmptyMsg")
	proto.RegisterType((*LongMsg)(nil), "hbase.pb.LongMsg")
	proto.RegisterType((*DoubleMsg)(nil), "hbase.pb.DoubleMsg")
	proto.RegisterType((*BigDecimalMsg)(nil), "hbase.pb.BigDecimalMsg")
	proto.RegisterType((*UUID)(nil), "hbase.pb.UUID")
	proto.RegisterType((*NamespaceDescriptor)(nil), "hbase.pb.NamespaceDescriptor")
	proto.RegisterType((*VersionInfo)(nil), "hbase.pb.VersionInfo")
	proto.RegisterType((*RegionServerInfo)(nil), "hbase.pb.RegionServerInfo")
	proto.RegisterType((*RegionExceptionMessage)(nil), "hbase.pb.RegionExceptionMessage")
	proto.RegisterType((*CacheEvictionStats)(nil), "hbase.pb.CacheEvictionStats")
	proto.RegisterType((*RegionLocation)(nil), "hbase.pb.RegionLocation")
}

func init() { proto.RegisterFile("Hbase.proto", fileDescriptor_0f11dfa70e726da0) }

var fileDescriptor_0f11dfa70e726da0 = []byte{
	// 1536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x5f, 0x6f, 0xe3, 0xc6,
	0x11, 0x0f, 0xf5, 0xc7, 0x12, 0x87, 0x92, 0x4f, 0xdd, 0x73, 0x72, 0xcc, 0x3f, 0xc0, 0x61, 0xd3,
	0xc2, 0x38, 0xa0, 0x6e, 0x62, 0xf4, 0xae, 0x69, 0x1e, 0x12, 0xd8, 0x16, 0xe3, 0x13, 0x6a, 0x4b,
	0xee, 0xca, 0x2e, 0x50, 0xa0, 0x00, 0xb1, 0x22, 0x57, 0xf4, 0xf6, 0x44, 0xae, 0x6e, 0x97, 0x32,
	0x4e, 0x79, 0x29, 0x90, 0x2f, 0xd1, 0xd7, 0xa2, 0xaf, 0xfd, 0x02, 0xfd, 0x04, 0xfd, 0x26, 0x7d,
	0xe9, 0xa7, 0x28, 0x66, 0x97, 0x14, 0x2d, 0xdd, 0x05, 0x69, 0x90, 0x17, 0x61, 0xe7, 0x37, 0x33,
	0x9c, 0xdd, 0x99, 0xdf, 0xcc, 0xae, 0xc0, 0x7b, 0x31, 0x63, 0x9a, 0x1f, 0x2f, 0x95, 0x2c, 0x24,
	0xe9, 0xde, 0x59, 0x61, 0x16, 0x5c, 0x80, 0x7b, 0xc3, 0x66, 0x0b, 0x3e, 0x66, 0x19, 0x27, 0x1f,
	0x81, 0x9b, 0xb3, 0x8c, 0xeb, 0x25, 0x8b, 0xb9, 0xef, 0x1c, 0x36, 0x8e, 0x7a, 0xb4, 0x06, 0x50,
	0xfb, 0x6a, 0xc5, 0x16, 0x62, 0x2e, 0xb8, 0xf2, 0x1b, 0x56, 0xbb, 0x01, 0x82, 0xef, 0x1a, 0xe0,
	0x99, 0x2f, 0x4d, 0xe3, 0x3b, 0x9e, 0x31, 0x72, 0x02, 0x50, 0xa0, 0x18, 0xe1, 0x07, 0x7c, 0xe7,
	0xd0, 0x39, 0xf2, 0x4e, 0x1e, 0x1f, 0x57, 0x71, 0x8f, 0x37, 0x41, 0xa9, 0x5b, 0x6c, 0xe2, 0x7f,
	0x01, 0xc0, 0x8a, 0x42, 0x89, 0xd9, 0xaa, 0xe0, 0xda, 0x6f, 0x1c, 0x36, 0x8f, 0xbc, 0x13, 0xbf,
	0xf6, 0x39, 0x5b, 0x17, 0x5c, 0x9b, 0x9f, 0x6b, 0x26, 0x14, 0x7d, 0x60, 0x4b, 0x42, 0x78, 0x14,
	0xcb, 0xc5, 0x2a, 0xcb, 0xa3, 0x39, 0xcb, 0xc4, 0x42, 0x70, 0xed, 0x37, 0x8d, 0xfb, 0x47, 0xb5,
	0xfb, 0xb9, 0x31, 0xf8, 0x06, 0xf5, 0x6b, 0xbb, 0x49, 0xba, 0x1f, 0xd7, 0x98, 0xe0, 0x9a, 0x7c,
	0x05, 0xfd, 0x58, 0xe6, 0x73, 0x91, 0xae, 0x14, 0x2b, 0x84, 0xcc, 0xfd, 0xd6, 0xee, 0x1e, 0x70,
	0x9f, 0xd3, 0x42, 0x89, 0x3c, 0x35, 0x7b, 0xd8, 0x36, 0x0f, 0xfe, 0x0a, 0x60, 0x73, 0x50, 0xb0,
	0x82, 0x93, 0xcf, 0xa0, 0xad, 0x71, 0x61, 0x52, 0xb9, 0x7f, 0xf2, 0xc1, 0xce, 0xe9, 0x8d, 0xd1,
	0xb1, 0xf9, 0xa5, 0xd6, 0x30, 0xf8, 0x1a, 0xda, 0xd6, 0xd5, 0x83, 0x4e, 0x38, 0x3e, 0x3d, 0xbb,
	0x0c, 0x87, 0x83, 0x77, 0x48, 0x0f, 0xba, 0xc3, 0xd1, 0xd4, 0x4a, 0x0e, 0xe9, 0x83, 0x6b, 0xa5,
	0xd1, 0xf8, 0x62, 0xd0, 0x40, 0xa5, 0xb1, 0x44, 0xa9, 0x19, 0xfc, 0xc3, 0x01, 0xf2, 0xe6, 0x39,
	0x09, 0x81, 0x56, 0x59, 0x06, 0xac, 0x9a, 0x59, 0xff, 0x84, 0x64, 0xbf, 0x91, 0xa5, 0xe6, 0x8f,
	0xcb, 0xd2, 0x7f, 0x1c, 0x00, 0xca, 0x53, 0x21, 0xf3, 0x51, 0x3e, 0x97, 0xe4, 0x43, 0x70, 0x95,
	0x91, 0x22, 0x91, 0x98, 0x1d, 0xb6, 0x68, 0xd7, 0x02, 0xa3, 0x64, 0x87, 0x46, 0xc8, 0xba, 0x1f,
	0xa6, 0xd1, 0x87, 0xe0, 0xea, 0x82, 0xa9, 0x22, 0x7a, 0xc9, 0xd7, 0x7e, 0xf3, 0xd0, 0x39, 0xea,
	0xd1, 0xae, 0x01, 0x7e, 0xcf, 0xd7, 0xe4, 0x09, 0x74, 0x78, 0x9e, 0x18, 0x55, 0xcb, 0xa8, 0xf6,
	0x78, 0x9e, 0xa0, 0xc2, 0x87, 0x8e, 0x9c, 0xcf, 0x17, 0x22, 0xe7, 0x7e, 0xfb, 0xd0, 0x39, 0xea,
	0xd2, 0x4a, 0x24, 0x07, 0xd0, 0xd6, 0xcb, 0x85, 0x28, 0xfc, 0x3d, 0x83, 0x5b, 0x81, 0x1c, 0x02,
	0x28, 0xbe, 0x5c, 0x88, 0x98, 0xe1, 0xbe, 0x3b, 0x87, 0xce, 0x51, 0xfb, 0x4b, 0xe7, 0x33, 0xea,
	0x96, 0xe0, 0x28, 0x09, 0x2e, 0xa0, 0xf7, 0x0d, 0xbb, 0x97, 0x8a, 0x27, 0x63, 0x99, 0x70, 0x4d,
	0x7e, 0x0b, 0xbd, 0xb9, 0x95, 0xa3, 0x5c, 0x26, 0x58, 0x0d, 0x4c, 0xdb, 0x41, 0x7d, 0x9a, 0x29,
	0x57, 0xf7, 0x5c, 0x99, 0xe3, 0x78, 0xf3, 0xda, 0x33, 0xf8, 0xa7, 0x03, 0x8f, 0x6c, 0xc2, 0xa6,
	0x4b, 0x1e, 0x9b, 0x7e, 0x23, 0xa7, 0xd0, 0x2a, 0xd6, 0xcb, 0x8a, 0x5b, 0xbf, 0xaa, 0x3f, 0xb2,
	0x63, 0xb8, 0x2b, 0xdf, 0xac, 0x97, 0x9c, 0x1a, 0x57, 0x3c, 0xd7, 0x3d, 0x5b, 0xac, 0x78, 0xd9,
	0xcc, 0x56, 0x08, 0xbe, 0x86, 0xc7, 0x6f, 0x71, 0x21, 0x8f, 0xc0, 0xa3, 0xe1, 0xc5, 0x68, 0x32,
	0x8e, 0xc6, 0xa7, 0x57, 0xe1, 0xc0, 0x21, 0x4f, 0xe0, 0x71, 0x38, 0x3e, 0x9f, 0x0c, 0xc3, 0x61,
	0xf4, 0x50, 0xd1, 0x08, 0x7e, 0x0d, 0xee, 0x8d, 0xc8, 0x38, 0x65, 0x79, 0xca, 0x91, 0x79, 0x73,
	0x25, 0x33, 0x33, 0x00, 0x5a, 0xd4, 0xac, 0xc9, 0x3e, 0x34, 0x0a, 0xe9, 0x37, 0x0c, 0xd2, 0x28,
	0x64, 0xf0, 0x1c, 0x06, 0x1b, 0x87, 0x1b, 0xc5, 0xe2, 0x97, 0x5c, 0xfd, 0x5f, 0x7e, 0x4b, 0x78,
	0xf7, 0x21, 0xd7, 0xeb, 0xa0, 0x3f, 0x47, 0x82, 0xd6, 0xd3, 0x60, 0x5d, 0xf2, 0xbe, 0xf7, 0xa0,
	0xdb, 0xd7, 0x86, 0x59, 0x22, 0xe3, 0x91, 0x42, 0x97, 0xb7, 0x30, 0xab, 0xfa, 0x1a, 0x75, 0x8b,
	0x6a, 0x19, 0xfc, 0x19, 0xa0, 0xae, 0x11, 0xf2, 0xec, 0x4e, 0xea, 0x22, 0xda, 0xb4, 0x96, 0x4b,
	0xbb, 0x08, 0x18, 0x25, 0x81, 0xd6, 0x52, 0xaa, 0xc2, 0x6c, 0xb7, 0x4f, 0xcd, 0x9a, 0x7c, 0x0c,
	0x60, 0x89, 0x19, 0x63, 0xf9, 0x9b, 0xe6, 0x20, 0x96, 0xaa, 0xe7, 0x58, 0xe6, 0x4f, 0xc0, 0x3b,
	0x97, 0x4b, 0x25, 0x63, 0xae, 0xb5, 0x54, 0x5b, 0x4d, 0xeb, 0xda, 0xa6, 0x0d, 0xbe, 0x84, 0xfd,
	0xed, 0xde, 0x7a, 0x9b, 0xd5, 0x76, 0x61, 0xdd, 0xaa, 0xb0, 0xbf, 0x83, 0x3e, 0xfa, 0x6e, 0x7a,
	0xfa, 0x87, 0x5c, 0x9d, 0x9a, 0x13, 0x5f, 0xc1, 0xfe, 0xf6, 0x3c, 0x40, 0xbb, 0xb9, 0x50, 0xba,
	0x28, 0x53, 0x6b, 0x05, 0xf2, 0x1e, 0xec, 0x69, 0x1e, 0xcb, 0x3c, 0x29, 0x29, 0x55, 0x4a, 0x55,
	0xe8, 0x51, 0x5e, 0x3c, 0xff, 0xcd, 0x4e, 0x68, 0xe7, 0xed, 0xa1, 0x9b, 0x55, 0xe8, 0x7f, 0x39,
	0x70, 0x70, 0x8d, 0x39, 0x49, 0x56, 0x8a, 0x0f, 0xb9, 0x8e, 0x95, 0x58, 0xe2, 0x14, 0xc1, 0xeb,
	0x48, 0x8b, 0x34, 0x67, 0xc5, 0x4a, 0x55, 0x47, 0xa8, 0x01, 0xf2, 0x01, 0x74, 0x45, 0xae, 0x0b,
	0x96, 0xc7, 0xf6, 0x7b, 0x2e, 0xdd, 0xc8, 0xe4, 0x97, 0xd0, 0x8f, 0x15, 0x37, 0xb3, 0x28, 0xc2,
	0xda, 0x9a, 0x4a, 0x34, 0xb1, 0x79, 0x7b, 0x15, 0x8e, 0xd5, 0xff, 0xc9, 0xb7, 0x01, 0x40, 0x37,
	0xcc, 0x96, 0xc5, 0xfa, 0x4a, 0xa7, 0xc1, 0xa7, 0xd0, 0xb9, 0x94, 0x79, 0x7a, 0xa5, 0x53, 0xf2,
	0x3e, 0x74, 0x17, 0x32, 0x4f, 0xa3, 0x4c, 0xa7, 0x66, 0xdf, 0x4d, 0xda, 0x59, 0x58, 0x55, 0xf0,
	0x14, 0xdc, 0xa1, 0x5c, 0xcd, 0x16, 0x1c, 0xed, 0x3e, 0x06, 0x48, 0x8c, 0xb0, 0xb1, 0x74, 0xa8,
	0x9b, 0x54, 0xea, 0xe0, 0x39, 0xf4, 0xcf, 0x44, 0x3a, 0xe4, 0xb1, 0xc8, 0xd8, 0x02, 0xed, 0x7f,
	0x01, 0xfb, 0x33, 0x91, 0x26, 0x16, 0xd8, 0xf8, 0xf4, 0x68, 0xbf, 0x46, 0xd1, 0xef, 0x1a, 0x5a,
	0xb7, 0xb7, 0xa3, 0x21, 0xf9, 0x14, 0xf6, 0x17, 0x9c, 0xe9, 0x22, 0xd2, 0x22, 0x8d, 0x66, 0xa2,
	0xd0, 0xe5, 0xec, 0xed, 0x19, 0x74, 0x2a, 0xd2, 0x33, 0x51, 0x68, 0x12, 0x40, 0x3f, 0x93, 0x0f,
	0x8d, 0x1a, 0xc6, 0xc8, 0x43, 0xb0, 0xb4, 0x09, 0x04, 0x3c, 0x1e, 0x57, 0xaf, 0x84, 0xaa, 0x42,
	0x3b, 0xfc, 0xad, 0x2e, 0x9d, 0x37, 0x52, 0xda, 0xf8, 0x71, 0x29, 0xfd, 0xaf, 0x03, 0xde, 0x1f,
	0xb9, 0xd2, 0xd5, 0xdd, 0xe1, 0x43, 0xe7, 0xde, 0x8a, 0x25, 0x05, 0x2a, 0x91, 0x0c, 0xa0, 0xb9,
	0x52, 0x8b, 0xb2, 0x03, 0x70, 0x89, 0x94, 0x50, 0xfc, 0x5e, 0x68, 0x7b, 0x63, 0x99, 0x6e, 0xad,
	0x64, 0xdc, 0xeb, 0x4a, 0x73, 0xe5, 0xb7, 0x6c, 0x2b, 0xe0, 0x1a, 0xb1, 0x04, 0x6f, 0xef, 0xb6,
	0xc5, 0x70, 0x4d, 0x3e, 0x81, 0x9e, 0x56, 0x71, 0x14, 0xdf, 0xf1, 0xf8, 0xa5, 0x5e, 0x65, 0xfe,
	0x9e, 0xd1, 0x79, 0x5a, 0xc5, 0xe7, 0x25, 0x84, 0xc3, 0xa7, 0xdc, 0x43, 0x94, 0xb1, 0xbf, 0x48,
	0x65, 0xae, 0x86, 0x3e, 0xed, 0x95, 0xe0, 0x15, 0x62, 0x5b, 0x46, 0x22, 0x97, 0xca, 0xef, 0x6e,
	0x1b, 0x21, 0x16, 0xdc, 0xc1, 0xa0, 0x9c, 0xc4, 0x66, 0xe6, 0x98, 0x03, 0x1b, 0x5e, 0xcf, 0xe5,
	0x35, 0x8e, 0x16, 0x6c, 0x9e, 0x36, 0xdd, 0xc8, 0xe4, 0x0b, 0xa8, 0xfc, 0x23, 0xc4, 0x0c, 0xef,
	0xbd, 0x93, 0x77, 0xeb, 0xdc, 0x3e, 0xc8, 0x1c, 0xf5, 0xee, 0x6b, 0x21, 0xf8, 0xce, 0x81, 0xf7,
	0x6c, 0xa8, 0xf0, 0x75, 0xcc, 0x4d, 0x7f, 0x5d, 0x71, 0xad, 0x59, 0xca, 0xc9, 0xe7, 0xb0, 0x67,
	0x2f, 0x63, 0x93, 0x60, 0xef, 0xe4, 0xfd, 0xef, 0xbd, 0x69, 0x68, 0x69, 0x48, 0x9e, 0x81, 0xcb,
	0xab, 0xcf, 0x94, 0x83, 0xf5, 0xc9, 0x76, 0x81, 0xeb, 0x77, 0x45, 0x6d, 0x19, 0xfc, 0x1b, 0xdf,
	0x2e, 0x2c, 0xbe, 0xe3, 0xe1, 0xbd, 0x88, 0x11, 0xc1, 0xa7, 0x90, 0x46, 0x5a, 0x73, 0x04, 0x78,
	0x12, 0xcd, 0x16, 0x32, 0x7e, 0xa9, 0xcd, 0xb9, 0x9b, 0xb4, 0x5f, 0xa2, 0x67, 0x06, 0xc4, 0x8c,
	0xce, 0xf0, 0xab, 0x51, 0x09, 0x97, 0x53, 0xa4, 0x67, 0xc0, 0xd0, 0x62, 0xc8, 0xf9, 0x8c, 0xbd,
	0x8e, 0x62, 0x8c, 0x12, 0x69, 0xf1, 0x6d, 0xd9, 0xfa, 0xb4, 0x97, 0xb1, 0xd7, 0x26, 0xf4, 0x54,
	0x7c, 0x8b, 0x24, 0x7d, 0xb0, 0x7f, 0xdb, 0xf3, 0x87, 0xbb, 0xa7, 0xde, 0xcd, 0xd3, 0xc3, 0x83,
	0xfc, 0xcd, 0x81, 0x7d, 0x6b, 0x75, 0x29, 0x63, 0xc3, 0x5b, 0xf2, 0x0c, 0xbc, 0xea, 0x8d, 0x83,
	0x95, 0xb1, 0xa9, 0x3c, 0xd8, 0xfd, 0xa8, 0x29, 0x0c, 0xa8, 0xfa, 0x69, 0xf4, 0x0c, 0x3c, 0x6d,
	0x6a, 0x5f, 0x3d, 0x7f, 0x9c, 0xef, 0x7d, 0x30, 0x80, 0xae, 0x2f, 0xa6, 0x27, 0xd0, 0xd1, 0xfc,
	0x55, 0x94, 0xaf, 0x32, 0x43, 0xf4, 0x26, 0xce, 0xe1, 0x57, 0xe3, 0x55, 0xf6, 0x54, 0xe1, 0x0d,
	0x93, 0x2d, 0x99, 0xe2, 0xe6, 0x4e, 0xef, 0x42, 0xeb, 0x32, 0x9c, 0x4e, 0x07, 0xef, 0x90, 0x9f,
	0x41, 0x1f, 0x57, 0xd1, 0x84, 0x46, 0xe1, 0x1f, 0x6e, 0x4f, 0x2f, 0x07, 0x0e, 0x71, 0xa1, 0x6d,
	0x97, 0x0d, 0x7c, 0x72, 0x8e, 0x27, 0x37, 0xa5, 0xa6, 0x49, 0x0e, 0x60, 0x70, 0x41, 0xc3, 0xd3,
	0x9b, 0x90, 0xd6, 0xf6, 0x2d, 0x7c, 0xb2, 0x96, 0xe8, 0xa0, 0x8d, 0xce, 0xe3, 0x49, 0x34, 0xb9,
	0x1e, 0xec, 0x3d, 0xcd, 0xa1, 0x8b, 0xd3, 0xf4, 0x36, 0x17, 0x05, 0x3e, 0x22, 0xc6, 0xa7, 0xe3,
	0xc9, 0x34, 0x3c, 0x9f, 0x8c, 0x87, 0xd3, 0x81, 0x43, 0x06, 0xd0, 0xbb, 0x1a, 0x9d, 0xd3, 0x0d,
	0xd2, 0xb0, 0xc8, 0xe5, 0xe5, 0xa8, 0x42, 0x9a, 0xf8, 0xe1, 0x4a, 0x30, 0x51, 0xae, 0x46, 0xe3,
	0xdb, 0x9b, 0x70, 0x6a, 0xa3, 0xbc, 0x98, 0xdc, 0xd2, 0xe9, 0x60, 0x0f, 0x8f, 0x32, 0x3c, 0xfd,
	0xd3, 0x74, 0xd0, 0x39, 0x0b, 0xe1, 0x73, 0xa9, 0xd2, 0x63, 0xb6, 0xc4, 0x7a, 0x1e, 0xdf, 0xb1,
	0x44, 0xca, 0x65, 0x99, 0x31, 0x7d, 0xc7, 0x12, 0x9e, 0xd8, 0xff, 0x40, 0xb3, 0xd5, 0xfc, 0x38,
	0xe5, 0x39, 0x57, 0x0c, 0x39, 0xe4, 0xbd, 0x38, 0x63, 0x9a, 0x5f, 0xa3, 0x42, 0xbf, 0x70, 0xfe,
	0xee, 0x38, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x9d, 0x21, 0xca, 0x30, 0x0d, 0x00, 0x00,
}
