// Code generated by protoc-gen-go. DO NOT EDIT.
// source: LoadBalancer.proto

// This file contains protocol buffers to represent the state of the load balancer.

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoadBalancerState struct {
	BalancerOn           *bool    `protobuf:"varint,1,opt,name=balancer_on,json=balancerOn" json:"balancer_on,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadBalancerState) Reset()         { *m = LoadBalancerState{} }
func (m *LoadBalancerState) String() string { return proto.CompactTextString(m) }
func (*LoadBalancerState) ProtoMessage()    {}
func (*LoadBalancerState) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb6b392c6564b76b, []int{0}
}

func (m *LoadBalancerState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadBalancerState.Unmarshal(m, b)
}
func (m *LoadBalancerState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadBalancerState.Marshal(b, m, deterministic)
}
func (m *LoadBalancerState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadBalancerState.Merge(m, src)
}
func (m *LoadBalancerState) XXX_Size() int {
	return xxx_messageInfo_LoadBalancerState.Size(m)
}
func (m *LoadBalancerState) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadBalancerState.DiscardUnknown(m)
}

var xxx_messageInfo_LoadBalancerState proto.InternalMessageInfo

func (m *LoadBalancerState) GetBalancerOn() bool {
	if m != nil && m.BalancerOn != nil {
		return *m.BalancerOn
	}
	return false
}

func init() {
	proto.RegisterType((*LoadBalancerState)(nil), "hbase.pb.LoadBalancerState")
}

func init() { proto.RegisterFile("LoadBalancer.proto", fileDescriptor_fb6b392c6564b76b) }

var fileDescriptor_fb6b392c6564b76b = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xf2, 0xc9, 0x4f, 0x4c,
	0x71, 0x4a, 0xcc, 0x49, 0xcc, 0x4b, 0x4e, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0xc8, 0x48, 0x4a, 0x2c, 0x4e, 0xd5, 0x2b, 0x48, 0x52, 0x32, 0xe1, 0x12, 0x44, 0x96, 0x0f, 0x2e,
	0x49, 0x2c, 0x49, 0x15, 0x92, 0xe7, 0xe2, 0x4e, 0x82, 0x0a, 0xc4, 0xe7, 0xe7, 0x49, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x04, 0x71, 0xc1, 0x84, 0xfc, 0xf3, 0x9c, 0x7c, 0xb8, 0x0c, 0xf3, 0x8b, 0xd2,
	0xf5, 0x12, 0x0b, 0x12, 0x93, 0x33, 0x52, 0xf5, 0x32, 0x12, 0x53, 0xf2, 0xf3, 0x0b, 0xf4, 0x20,
	0x66, 0x16, 0x67, 0x24, 0xa6, 0xa4, 0xa6, 0x40, 0xec, 0x49, 0x2a, 0x4d, 0xd3, 0x4b, 0x4f, 0xcd,
	0x4b, 0x2d, 0x4a, 0x2c, 0x49, 0x4d, 0x71, 0x42, 0x71, 0x48, 0x00, 0x48, 0xbe, 0xd8, 0x83, 0x71,
	0x01, 0x23, 0x23, 0x20, 0x00, 0x00, 0xff, 0xff, 0x98, 0x1c, 0x00, 0x0c, 0xa2, 0x00, 0x00, 0x00,
}
