// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MapReduce.proto

//This file includes protocol buffers used in MapReduce only.

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ScanMetrics struct {
	Metrics              []*NameInt64Pair `protobuf:"bytes,1,rep,name=metrics" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ScanMetrics) Reset()         { *m = ScanMetrics{} }
func (m *ScanMetrics) String() string { return proto.CompactTextString(m) }
func (*ScanMetrics) ProtoMessage()    {}
func (*ScanMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_acd66bf8bb80ae11, []int{0}
}

func (m *ScanMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanMetrics.Unmarshal(m, b)
}
func (m *ScanMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanMetrics.Marshal(b, m, deterministic)
}
func (m *ScanMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanMetrics.Merge(m, src)
}
func (m *ScanMetrics) XXX_Size() int {
	return xxx_messageInfo_ScanMetrics.Size(m)
}
func (m *ScanMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_ScanMetrics proto.InternalMessageInfo

func (m *ScanMetrics) GetMetrics() []*NameInt64Pair {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type TableSnapshotRegionSplit struct {
	Locations            []string     `protobuf:"bytes,2,rep,name=locations" json:"locations,omitempty"`
	Table                *TableSchema `protobuf:"bytes,3,opt,name=table" json:"table,omitempty"`
	Region               *RegionInfo  `protobuf:"bytes,4,opt,name=region" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TableSnapshotRegionSplit) Reset()         { *m = TableSnapshotRegionSplit{} }
func (m *TableSnapshotRegionSplit) String() string { return proto.CompactTextString(m) }
func (*TableSnapshotRegionSplit) ProtoMessage()    {}
func (*TableSnapshotRegionSplit) Descriptor() ([]byte, []int) {
	return fileDescriptor_acd66bf8bb80ae11, []int{1}
}

func (m *TableSnapshotRegionSplit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableSnapshotRegionSplit.Unmarshal(m, b)
}
func (m *TableSnapshotRegionSplit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableSnapshotRegionSplit.Marshal(b, m, deterministic)
}
func (m *TableSnapshotRegionSplit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableSnapshotRegionSplit.Merge(m, src)
}
func (m *TableSnapshotRegionSplit) XXX_Size() int {
	return xxx_messageInfo_TableSnapshotRegionSplit.Size(m)
}
func (m *TableSnapshotRegionSplit) XXX_DiscardUnknown() {
	xxx_messageInfo_TableSnapshotRegionSplit.DiscardUnknown(m)
}

var xxx_messageInfo_TableSnapshotRegionSplit proto.InternalMessageInfo

func (m *TableSnapshotRegionSplit) GetLocations() []string {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *TableSnapshotRegionSplit) GetTable() *TableSchema {
	if m != nil {
		return m.Table
	}
	return nil
}

func (m *TableSnapshotRegionSplit) GetRegion() *RegionInfo {
	if m != nil {
		return m.Region
	}
	return nil
}

func init() {
	proto.RegisterType((*ScanMetrics)(nil), "hbase.pb.ScanMetrics")
	proto.RegisterType((*TableSnapshotRegionSplit)(nil), "hbase.pb.TableSnapshotRegionSplit")
}

func init() { proto.RegisterFile("MapReduce.proto", fileDescriptor_acd66bf8bb80ae11) }

var fileDescriptor_acd66bf8bb80ae11 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x4d, 0x6a, 0xc3, 0x30,
	0x14, 0x84, 0x51, 0xdd, 0xbf, 0xc8, 0x8b, 0x82, 0x69, 0xa9, 0x29, 0x5d, 0x98, 0xac, 0x0c, 0x2d,
	0x82, 0x84, 0xd2, 0x75, 0xf1, 0x2a, 0x5e, 0xa4, 0x04, 0xb9, 0x17, 0x78, 0x96, 0x5f, 0x2c, 0x83,
	0xad, 0x27, 0x24, 0xe5, 0x24, 0xbd, 0x40, 0x8f, 0x5a, 0x6c, 0x27, 0x78, 0x37, 0x8c, 0xbe, 0x99,
	0x41, 0x8f, 0x3f, 0xec, 0xc1, 0x4a, 0x6c, 0x4e, 0x0a, 0x85, 0x75, 0x14, 0x28, 0xb9, 0xd7, 0x35,
	0x78, 0x14, 0xb6, 0x7e, 0x89, 0x77, 0xc5, 0xa4, 0x46, 0x7b, 0xfd, 0xc5, 0xe3, 0x4a, 0x81, 0xd9,
	0x63, 0x70, 0x9d, 0xf2, 0xc9, 0x86, 0xdf, 0x0d, 0xb3, 0x4c, 0x59, 0x16, 0xe5, 0xf1, 0xf6, 0x59,
	0x5c, 0x72, 0xe2, 0x1b, 0x06, 0x2c, 0x4d, 0xf8, 0xfc, 0x38, 0x40, 0xe7, 0xe4, 0x85, 0x5b, 0xff,
	0x32, 0x9e, 0xfe, 0x40, 0xdd, 0x63, 0x65, 0xc0, 0x7a, 0x4d, 0x41, 0x62, 0xdb, 0x91, 0xa9, 0x6c,
	0xdf, 0x85, 0xe4, 0x95, 0xaf, 0x7a, 0x52, 0x10, 0x3a, 0x32, 0x3e, 0xbd, 0xca, 0xa2, 0x7c, 0x25,
	0x17, 0x23, 0x79, 0xe3, 0x37, 0x61, 0x4c, 0xa6, 0x51, 0xc6, 0xf2, 0x78, 0xfb, 0xb4, 0x6c, 0xcd,
	0x85, 0x4a, 0xe3, 0x00, 0x72, 0x66, 0x92, 0x77, 0x7e, 0xeb, 0xa6, 0xe6, 0xf4, 0x7a, 0xa2, 0x1f,
	0x17, 0x7a, 0x5e, 0x2c, 0xcd, 0x91, 0xe4, 0x99, 0x29, 0x4a, 0xbe, 0x21, 0xd7, 0x0a, 0xb0, 0xa0,
	0x34, 0x0a, 0x0d, 0x0d, 0x91, 0x3d, 0x07, 0xbc, 0x86, 0x06, 0x9b, 0xf9, 0xff, 0xf5, 0xe9, 0x28,
	0x5a, 0x34, 0xe8, 0x20, 0x60, 0x53, 0x2c, 0x47, 0x3b, 0x8c, 0x8f, 0x7e, 0xc7, 0xfe, 0x18, 0xfb,
	0x0f, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xa0, 0x5c, 0x55, 0x4b, 0x01, 0x00, 0x00,
}
