// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Quota.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QuotaScope int32

const (
	QuotaScope_CLUSTER QuotaScope = 1
	QuotaScope_MACHINE QuotaScope = 2
)

var QuotaScope_name = map[int32]string{
	1: "CLUSTER",
	2: "MACHINE",
}

var QuotaScope_value = map[string]int32{
	"CLUSTER": 1,
	"MACHINE": 2,
}

func (x QuotaScope) Enum() *QuotaScope {
	p := new(QuotaScope)
	*p = x
	return p
}

func (x QuotaScope) String() string {
	return proto.EnumName(QuotaScope_name, int32(x))
}

func (x *QuotaScope) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(QuotaScope_value, data, "QuotaScope")
	if err != nil {
		return err
	}
	*x = QuotaScope(value)
	return nil
}

func (QuotaScope) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{0}
}

type ThrottleType int32

const (
	ThrottleType_REQUEST_NUMBER        ThrottleType = 1
	ThrottleType_REQUEST_SIZE          ThrottleType = 2
	ThrottleType_WRITE_NUMBER          ThrottleType = 3
	ThrottleType_WRITE_SIZE            ThrottleType = 4
	ThrottleType_READ_NUMBER           ThrottleType = 5
	ThrottleType_READ_SIZE             ThrottleType = 6
	ThrottleType_REQUEST_CAPACITY_UNIT ThrottleType = 7
	ThrottleType_WRITE_CAPACITY_UNIT   ThrottleType = 8
	ThrottleType_READ_CAPACITY_UNIT    ThrottleType = 9
)

var ThrottleType_name = map[int32]string{
	1: "REQUEST_NUMBER",
	2: "REQUEST_SIZE",
	3: "WRITE_NUMBER",
	4: "WRITE_SIZE",
	5: "READ_NUMBER",
	6: "READ_SIZE",
	7: "REQUEST_CAPACITY_UNIT",
	8: "WRITE_CAPACITY_UNIT",
	9: "READ_CAPACITY_UNIT",
}

var ThrottleType_value = map[string]int32{
	"REQUEST_NUMBER":        1,
	"REQUEST_SIZE":          2,
	"WRITE_NUMBER":          3,
	"WRITE_SIZE":            4,
	"READ_NUMBER":           5,
	"READ_SIZE":             6,
	"REQUEST_CAPACITY_UNIT": 7,
	"WRITE_CAPACITY_UNIT":   8,
	"READ_CAPACITY_UNIT":    9,
}

func (x ThrottleType) Enum() *ThrottleType {
	p := new(ThrottleType)
	*p = x
	return p
}

func (x ThrottleType) String() string {
	return proto.EnumName(ThrottleType_name, int32(x))
}

func (x *ThrottleType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ThrottleType_value, data, "ThrottleType")
	if err != nil {
		return err
	}
	*x = ThrottleType(value)
	return nil
}

func (ThrottleType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{1}
}

type QuotaType int32

const (
	QuotaType_THROTTLE QuotaType = 1
	QuotaType_SPACE    QuotaType = 2
)

var QuotaType_name = map[int32]string{
	1: "THROTTLE",
	2: "SPACE",
}

var QuotaType_value = map[string]int32{
	"THROTTLE": 1,
	"SPACE":    2,
}

func (x QuotaType) Enum() *QuotaType {
	p := new(QuotaType)
	*p = x
	return p
}

func (x QuotaType) String() string {
	return proto.EnumName(QuotaType_name, int32(x))
}

func (x *QuotaType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(QuotaType_value, data, "QuotaType")
	if err != nil {
		return err
	}
	*x = QuotaType(value)
	return nil
}

func (QuotaType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{2}
}

// Defines what action should be taken when the SpaceQuota is violated
type SpaceViolationPolicy int32

const (
	SpaceViolationPolicy_DISABLE               SpaceViolationPolicy = 1
	SpaceViolationPolicy_NO_WRITES_COMPACTIONS SpaceViolationPolicy = 2
	SpaceViolationPolicy_NO_WRITES             SpaceViolationPolicy = 3
	SpaceViolationPolicy_NO_INSERTS            SpaceViolationPolicy = 4
)

var SpaceViolationPolicy_name = map[int32]string{
	1: "DISABLE",
	2: "NO_WRITES_COMPACTIONS",
	3: "NO_WRITES",
	4: "NO_INSERTS",
}

var SpaceViolationPolicy_value = map[string]int32{
	"DISABLE":               1,
	"NO_WRITES_COMPACTIONS": 2,
	"NO_WRITES":             3,
	"NO_INSERTS":            4,
}

func (x SpaceViolationPolicy) Enum() *SpaceViolationPolicy {
	p := new(SpaceViolationPolicy)
	*p = x
	return p
}

func (x SpaceViolationPolicy) String() string {
	return proto.EnumName(SpaceViolationPolicy_name, int32(x))
}

func (x *SpaceViolationPolicy) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SpaceViolationPolicy_value, data, "SpaceViolationPolicy")
	if err != nil {
		return err
	}
	*x = SpaceViolationPolicy(value)
	return nil
}

func (SpaceViolationPolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{3}
}

type TimedQuota struct {
	TimeUnit             *TimeUnit   `protobuf:"varint,1,req,name=time_unit,json=timeUnit,enum=hbase.pb.TimeUnit" json:"time_unit,omitempty"`
	SoftLimit            *uint64     `protobuf:"varint,2,opt,name=soft_limit,json=softLimit" json:"soft_limit,omitempty"`
	Share                *float32    `protobuf:"fixed32,3,opt,name=share" json:"share,omitempty"`
	Scope                *QuotaScope `protobuf:"varint,4,opt,name=scope,enum=hbase.pb.QuotaScope,def=2" json:"scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TimedQuota) Reset()         { *m = TimedQuota{} }
func (m *TimedQuota) String() string { return proto.CompactTextString(m) }
func (*TimedQuota) ProtoMessage()    {}
func (*TimedQuota) Descriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{0}
}

func (m *TimedQuota) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimedQuota.Unmarshal(m, b)
}
func (m *TimedQuota) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimedQuota.Marshal(b, m, deterministic)
}
func (m *TimedQuota) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimedQuota.Merge(m, src)
}
func (m *TimedQuota) XXX_Size() int {
	return xxx_messageInfo_TimedQuota.Size(m)
}
func (m *TimedQuota) XXX_DiscardUnknown() {
	xxx_messageInfo_TimedQuota.DiscardUnknown(m)
}

var xxx_messageInfo_TimedQuota proto.InternalMessageInfo

const Default_TimedQuota_Scope QuotaScope = QuotaScope_MACHINE

func (m *TimedQuota) GetTimeUnit() TimeUnit {
	if m != nil && m.TimeUnit != nil {
		return *m.TimeUnit
	}
	return TimeUnit_NANOSECONDS
}

func (m *TimedQuota) GetSoftLimit() uint64 {
	if m != nil && m.SoftLimit != nil {
		return *m.SoftLimit
	}
	return 0
}

func (m *TimedQuota) GetShare() float32 {
	if m != nil && m.Share != nil {
		return *m.Share
	}
	return 0
}

func (m *TimedQuota) GetScope() QuotaScope {
	if m != nil && m.Scope != nil {
		return *m.Scope
	}
	return Default_TimedQuota_Scope
}

type Throttle struct {
	ReqNum               *TimedQuota `protobuf:"bytes,1,opt,name=req_num,json=reqNum" json:"req_num,omitempty"`
	ReqSize              *TimedQuota `protobuf:"bytes,2,opt,name=req_size,json=reqSize" json:"req_size,omitempty"`
	WriteNum             *TimedQuota `protobuf:"bytes,3,opt,name=write_num,json=writeNum" json:"write_num,omitempty"`
	WriteSize            *TimedQuota `protobuf:"bytes,4,opt,name=write_size,json=writeSize" json:"write_size,omitempty"`
	ReadNum              *TimedQuota `protobuf:"bytes,5,opt,name=read_num,json=readNum" json:"read_num,omitempty"`
	ReadSize             *TimedQuota `protobuf:"bytes,6,opt,name=read_size,json=readSize" json:"read_size,omitempty"`
	ReqCapacityUnit      *TimedQuota `protobuf:"bytes,7,opt,name=req_capacity_unit,json=reqCapacityUnit" json:"req_capacity_unit,omitempty"`
	WriteCapacityUnit    *TimedQuota `protobuf:"bytes,8,opt,name=write_capacity_unit,json=writeCapacityUnit" json:"write_capacity_unit,omitempty"`
	ReadCapacityUnit     *TimedQuota `protobuf:"bytes,9,opt,name=read_capacity_unit,json=readCapacityUnit" json:"read_capacity_unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Throttle) Reset()         { *m = Throttle{} }
func (m *Throttle) String() string { return proto.CompactTextString(m) }
func (*Throttle) ProtoMessage()    {}
func (*Throttle) Descriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{1}
}

func (m *Throttle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Throttle.Unmarshal(m, b)
}
func (m *Throttle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Throttle.Marshal(b, m, deterministic)
}
func (m *Throttle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Throttle.Merge(m, src)
}
func (m *Throttle) XXX_Size() int {
	return xxx_messageInfo_Throttle.Size(m)
}
func (m *Throttle) XXX_DiscardUnknown() {
	xxx_messageInfo_Throttle.DiscardUnknown(m)
}

var xxx_messageInfo_Throttle proto.InternalMessageInfo

func (m *Throttle) GetReqNum() *TimedQuota {
	if m != nil {
		return m.ReqNum
	}
	return nil
}

func (m *Throttle) GetReqSize() *TimedQuota {
	if m != nil {
		return m.ReqSize
	}
	return nil
}

func (m *Throttle) GetWriteNum() *TimedQuota {
	if m != nil {
		return m.WriteNum
	}
	return nil
}

func (m *Throttle) GetWriteSize() *TimedQuota {
	if m != nil {
		return m.WriteSize
	}
	return nil
}

func (m *Throttle) GetReadNum() *TimedQuota {
	if m != nil {
		return m.ReadNum
	}
	return nil
}

func (m *Throttle) GetReadSize() *TimedQuota {
	if m != nil {
		return m.ReadSize
	}
	return nil
}

func (m *Throttle) GetReqCapacityUnit() *TimedQuota {
	if m != nil {
		return m.ReqCapacityUnit
	}
	return nil
}

func (m *Throttle) GetWriteCapacityUnit() *TimedQuota {
	if m != nil {
		return m.WriteCapacityUnit
	}
	return nil
}

func (m *Throttle) GetReadCapacityUnit() *TimedQuota {
	if m != nil {
		return m.ReadCapacityUnit
	}
	return nil
}

type ThrottleRequest struct {
	Type                 *ThrottleType `protobuf:"varint,1,opt,name=type,enum=hbase.pb.ThrottleType" json:"type,omitempty"`
	TimedQuota           *TimedQuota   `protobuf:"bytes,2,opt,name=timed_quota,json=timedQuota" json:"timed_quota,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ThrottleRequest) Reset()         { *m = ThrottleRequest{} }
func (m *ThrottleRequest) String() string { return proto.CompactTextString(m) }
func (*ThrottleRequest) ProtoMessage()    {}
func (*ThrottleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{2}
}

func (m *ThrottleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThrottleRequest.Unmarshal(m, b)
}
func (m *ThrottleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThrottleRequest.Marshal(b, m, deterministic)
}
func (m *ThrottleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThrottleRequest.Merge(m, src)
}
func (m *ThrottleRequest) XXX_Size() int {
	return xxx_messageInfo_ThrottleRequest.Size(m)
}
func (m *ThrottleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ThrottleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ThrottleRequest proto.InternalMessageInfo

func (m *ThrottleRequest) GetType() ThrottleType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ThrottleType_REQUEST_NUMBER
}

func (m *ThrottleRequest) GetTimedQuota() *TimedQuota {
	if m != nil {
		return m.TimedQuota
	}
	return nil
}

type Quotas struct {
	BypassGlobals        *bool       `protobuf:"varint,1,opt,name=bypass_globals,json=bypassGlobals,def=0" json:"bypass_globals,omitempty"`
	Throttle             *Throttle   `protobuf:"bytes,2,opt,name=throttle" json:"throttle,omitempty"`
	Space                *SpaceQuota `protobuf:"bytes,3,opt,name=space" json:"space,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Quotas) Reset()         { *m = Quotas{} }
func (m *Quotas) String() string { return proto.CompactTextString(m) }
func (*Quotas) ProtoMessage()    {}
func (*Quotas) Descriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{3}
}

func (m *Quotas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quotas.Unmarshal(m, b)
}
func (m *Quotas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quotas.Marshal(b, m, deterministic)
}
func (m *Quotas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quotas.Merge(m, src)
}
func (m *Quotas) XXX_Size() int {
	return xxx_messageInfo_Quotas.Size(m)
}
func (m *Quotas) XXX_DiscardUnknown() {
	xxx_messageInfo_Quotas.DiscardUnknown(m)
}

var xxx_messageInfo_Quotas proto.InternalMessageInfo

const Default_Quotas_BypassGlobals bool = false

func (m *Quotas) GetBypassGlobals() bool {
	if m != nil && m.BypassGlobals != nil {
		return *m.BypassGlobals
	}
	return Default_Quotas_BypassGlobals
}

func (m *Quotas) GetThrottle() *Throttle {
	if m != nil {
		return m.Throttle
	}
	return nil
}

func (m *Quotas) GetSpace() *SpaceQuota {
	if m != nil {
		return m.Space
	}
	return nil
}

type QuotaUsage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuotaUsage) Reset()         { *m = QuotaUsage{} }
func (m *QuotaUsage) String() string { return proto.CompactTextString(m) }
func (*QuotaUsage) ProtoMessage()    {}
func (*QuotaUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{4}
}

func (m *QuotaUsage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuotaUsage.Unmarshal(m, b)
}
func (m *QuotaUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuotaUsage.Marshal(b, m, deterministic)
}
func (m *QuotaUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuotaUsage.Merge(m, src)
}
func (m *QuotaUsage) XXX_Size() int {
	return xxx_messageInfo_QuotaUsage.Size(m)
}
func (m *QuotaUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_QuotaUsage.DiscardUnknown(m)
}

var xxx_messageInfo_QuotaUsage proto.InternalMessageInfo

// Defines a limit on the amount of filesystem space used by a table/namespace
type SpaceQuota struct {
	SoftLimit            *uint64               `protobuf:"varint,1,opt,name=soft_limit,json=softLimit" json:"soft_limit,omitempty"`
	ViolationPolicy      *SpaceViolationPolicy `protobuf:"varint,2,opt,name=violation_policy,json=violationPolicy,enum=hbase.pb.SpaceViolationPolicy" json:"violation_policy,omitempty"`
	Remove               *bool                 `protobuf:"varint,3,opt,name=remove,def=0" json:"remove,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SpaceQuota) Reset()         { *m = SpaceQuota{} }
func (m *SpaceQuota) String() string { return proto.CompactTextString(m) }
func (*SpaceQuota) ProtoMessage()    {}
func (*SpaceQuota) Descriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{5}
}

func (m *SpaceQuota) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceQuota.Unmarshal(m, b)
}
func (m *SpaceQuota) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceQuota.Marshal(b, m, deterministic)
}
func (m *SpaceQuota) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceQuota.Merge(m, src)
}
func (m *SpaceQuota) XXX_Size() int {
	return xxx_messageInfo_SpaceQuota.Size(m)
}
func (m *SpaceQuota) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceQuota.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceQuota proto.InternalMessageInfo

const Default_SpaceQuota_Remove bool = false

func (m *SpaceQuota) GetSoftLimit() uint64 {
	if m != nil && m.SoftLimit != nil {
		return *m.SoftLimit
	}
	return 0
}

func (m *SpaceQuota) GetViolationPolicy() SpaceViolationPolicy {
	if m != nil && m.ViolationPolicy != nil {
		return *m.ViolationPolicy
	}
	return SpaceViolationPolicy_DISABLE
}

func (m *SpaceQuota) GetRemove() bool {
	if m != nil && m.Remove != nil {
		return *m.Remove
	}
	return Default_SpaceQuota_Remove
}

// The Request to limit space usage (to allow for schema evolution not tied to SpaceQuota).
type SpaceLimitRequest struct {
	Quota                *SpaceQuota `protobuf:"bytes,1,opt,name=quota" json:"quota,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SpaceLimitRequest) Reset()         { *m = SpaceLimitRequest{} }
func (m *SpaceLimitRequest) String() string { return proto.CompactTextString(m) }
func (*SpaceLimitRequest) ProtoMessage()    {}
func (*SpaceLimitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{6}
}

func (m *SpaceLimitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceLimitRequest.Unmarshal(m, b)
}
func (m *SpaceLimitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceLimitRequest.Marshal(b, m, deterministic)
}
func (m *SpaceLimitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceLimitRequest.Merge(m, src)
}
func (m *SpaceLimitRequest) XXX_Size() int {
	return xxx_messageInfo_SpaceLimitRequest.Size(m)
}
func (m *SpaceLimitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceLimitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceLimitRequest proto.InternalMessageInfo

func (m *SpaceLimitRequest) GetQuota() *SpaceQuota {
	if m != nil {
		return m.Quota
	}
	return nil
}

// Represents the state of a quota on a table. Either the quota is not in violation
// or it is in violation there is a violation policy which should be in effect.
type SpaceQuotaStatus struct {
	ViolationPolicy      *SpaceViolationPolicy `protobuf:"varint,1,opt,name=violation_policy,json=violationPolicy,enum=hbase.pb.SpaceViolationPolicy" json:"violation_policy,omitempty"`
	InViolation          *bool                 `protobuf:"varint,2,opt,name=in_violation,json=inViolation" json:"in_violation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SpaceQuotaStatus) Reset()         { *m = SpaceQuotaStatus{} }
func (m *SpaceQuotaStatus) String() string { return proto.CompactTextString(m) }
func (*SpaceQuotaStatus) ProtoMessage()    {}
func (*SpaceQuotaStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{7}
}

func (m *SpaceQuotaStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceQuotaStatus.Unmarshal(m, b)
}
func (m *SpaceQuotaStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceQuotaStatus.Marshal(b, m, deterministic)
}
func (m *SpaceQuotaStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceQuotaStatus.Merge(m, src)
}
func (m *SpaceQuotaStatus) XXX_Size() int {
	return xxx_messageInfo_SpaceQuotaStatus.Size(m)
}
func (m *SpaceQuotaStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceQuotaStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceQuotaStatus proto.InternalMessageInfo

func (m *SpaceQuotaStatus) GetViolationPolicy() SpaceViolationPolicy {
	if m != nil && m.ViolationPolicy != nil {
		return *m.ViolationPolicy
	}
	return SpaceViolationPolicy_DISABLE
}

func (m *SpaceQuotaStatus) GetInViolation() bool {
	if m != nil && m.InViolation != nil {
		return *m.InViolation
	}
	return false
}

// Message stored in the value of hbase:quota table to denote the status of a table WRT
// the quota applicable to it.
type SpaceQuotaSnapshot struct {
	QuotaStatus          *SpaceQuotaStatus `protobuf:"bytes,1,opt,name=quota_status,json=quotaStatus" json:"quota_status,omitempty"`
	QuotaUsage           *uint64           `protobuf:"varint,2,opt,name=quota_usage,json=quotaUsage" json:"quota_usage,omitempty"`
	QuotaLimit           *uint64           `protobuf:"varint,3,opt,name=quota_limit,json=quotaLimit" json:"quota_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SpaceQuotaSnapshot) Reset()         { *m = SpaceQuotaSnapshot{} }
func (m *SpaceQuotaSnapshot) String() string { return proto.CompactTextString(m) }
func (*SpaceQuotaSnapshot) ProtoMessage()    {}
func (*SpaceQuotaSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{8}
}

func (m *SpaceQuotaSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpaceQuotaSnapshot.Unmarshal(m, b)
}
func (m *SpaceQuotaSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpaceQuotaSnapshot.Marshal(b, m, deterministic)
}
func (m *SpaceQuotaSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpaceQuotaSnapshot.Merge(m, src)
}
func (m *SpaceQuotaSnapshot) XXX_Size() int {
	return xxx_messageInfo_SpaceQuotaSnapshot.Size(m)
}
func (m *SpaceQuotaSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_SpaceQuotaSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_SpaceQuotaSnapshot proto.InternalMessageInfo

func (m *SpaceQuotaSnapshot) GetQuotaStatus() *SpaceQuotaStatus {
	if m != nil {
		return m.QuotaStatus
	}
	return nil
}

func (m *SpaceQuotaSnapshot) GetQuotaUsage() uint64 {
	if m != nil && m.QuotaUsage != nil {
		return *m.QuotaUsage
	}
	return 0
}

func (m *SpaceQuotaSnapshot) GetQuotaLimit() uint64 {
	if m != nil && m.QuotaLimit != nil {
		return *m.QuotaLimit
	}
	return 0
}

type GetSpaceQuotaRegionSizesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSpaceQuotaRegionSizesRequest) Reset()         { *m = GetSpaceQuotaRegionSizesRequest{} }
func (m *GetSpaceQuotaRegionSizesRequest) String() string { return proto.CompactTextString(m) }
func (*GetSpaceQuotaRegionSizesRequest) ProtoMessage()    {}
func (*GetSpaceQuotaRegionSizesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{9}
}

func (m *GetSpaceQuotaRegionSizesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpaceQuotaRegionSizesRequest.Unmarshal(m, b)
}
func (m *GetSpaceQuotaRegionSizesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpaceQuotaRegionSizesRequest.Marshal(b, m, deterministic)
}
func (m *GetSpaceQuotaRegionSizesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpaceQuotaRegionSizesRequest.Merge(m, src)
}
func (m *GetSpaceQuotaRegionSizesRequest) XXX_Size() int {
	return xxx_messageInfo_GetSpaceQuotaRegionSizesRequest.Size(m)
}
func (m *GetSpaceQuotaRegionSizesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpaceQuotaRegionSizesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpaceQuotaRegionSizesRequest proto.InternalMessageInfo

type GetSpaceQuotaRegionSizesResponse struct {
	Sizes                []*GetSpaceQuotaRegionSizesResponse_RegionSizes `protobuf:"bytes,1,rep,name=sizes" json:"sizes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                        `json:"-"`
	XXX_unrecognized     []byte                                          `json:"-"`
	XXX_sizecache        int32                                           `json:"-"`
}

func (m *GetSpaceQuotaRegionSizesResponse) Reset()         { *m = GetSpaceQuotaRegionSizesResponse{} }
func (m *GetSpaceQuotaRegionSizesResponse) String() string { return proto.CompactTextString(m) }
func (*GetSpaceQuotaRegionSizesResponse) ProtoMessage()    {}
func (*GetSpaceQuotaRegionSizesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{10}
}

func (m *GetSpaceQuotaRegionSizesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpaceQuotaRegionSizesResponse.Unmarshal(m, b)
}
func (m *GetSpaceQuotaRegionSizesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpaceQuotaRegionSizesResponse.Marshal(b, m, deterministic)
}
func (m *GetSpaceQuotaRegionSizesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpaceQuotaRegionSizesResponse.Merge(m, src)
}
func (m *GetSpaceQuotaRegionSizesResponse) XXX_Size() int {
	return xxx_messageInfo_GetSpaceQuotaRegionSizesResponse.Size(m)
}
func (m *GetSpaceQuotaRegionSizesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpaceQuotaRegionSizesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpaceQuotaRegionSizesResponse proto.InternalMessageInfo

func (m *GetSpaceQuotaRegionSizesResponse) GetSizes() []*GetSpaceQuotaRegionSizesResponse_RegionSizes {
	if m != nil {
		return m.Sizes
	}
	return nil
}

type GetSpaceQuotaRegionSizesResponse_RegionSizes struct {
	TableName            *TableName `protobuf:"bytes,1,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	Size                 *uint64    `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetSpaceQuotaRegionSizesResponse_RegionSizes) Reset() {
	*m = GetSpaceQuotaRegionSizesResponse_RegionSizes{}
}
func (m *GetSpaceQuotaRegionSizesResponse_RegionSizes) String() string {
	return proto.CompactTextString(m)
}
func (*GetSpaceQuotaRegionSizesResponse_RegionSizes) ProtoMessage() {}
func (*GetSpaceQuotaRegionSizesResponse_RegionSizes) Descriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{10, 0}
}

func (m *GetSpaceQuotaRegionSizesResponse_RegionSizes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpaceQuotaRegionSizesResponse_RegionSizes.Unmarshal(m, b)
}
func (m *GetSpaceQuotaRegionSizesResponse_RegionSizes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpaceQuotaRegionSizesResponse_RegionSizes.Marshal(b, m, deterministic)
}
func (m *GetSpaceQuotaRegionSizesResponse_RegionSizes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpaceQuotaRegionSizesResponse_RegionSizes.Merge(m, src)
}
func (m *GetSpaceQuotaRegionSizesResponse_RegionSizes) XXX_Size() int {
	return xxx_messageInfo_GetSpaceQuotaRegionSizesResponse_RegionSizes.Size(m)
}
func (m *GetSpaceQuotaRegionSizesResponse_RegionSizes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpaceQuotaRegionSizesResponse_RegionSizes.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpaceQuotaRegionSizesResponse_RegionSizes proto.InternalMessageInfo

func (m *GetSpaceQuotaRegionSizesResponse_RegionSizes) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *GetSpaceQuotaRegionSizesResponse_RegionSizes) GetSize() uint64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

type GetSpaceQuotaSnapshotsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSpaceQuotaSnapshotsRequest) Reset()         { *m = GetSpaceQuotaSnapshotsRequest{} }
func (m *GetSpaceQuotaSnapshotsRequest) String() string { return proto.CompactTextString(m) }
func (*GetSpaceQuotaSnapshotsRequest) ProtoMessage()    {}
func (*GetSpaceQuotaSnapshotsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{11}
}

func (m *GetSpaceQuotaSnapshotsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpaceQuotaSnapshotsRequest.Unmarshal(m, b)
}
func (m *GetSpaceQuotaSnapshotsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpaceQuotaSnapshotsRequest.Marshal(b, m, deterministic)
}
func (m *GetSpaceQuotaSnapshotsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpaceQuotaSnapshotsRequest.Merge(m, src)
}
func (m *GetSpaceQuotaSnapshotsRequest) XXX_Size() int {
	return xxx_messageInfo_GetSpaceQuotaSnapshotsRequest.Size(m)
}
func (m *GetSpaceQuotaSnapshotsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpaceQuotaSnapshotsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpaceQuotaSnapshotsRequest proto.InternalMessageInfo

type GetSpaceQuotaSnapshotsResponse struct {
	Snapshots            []*GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot `protobuf:"bytes,1,rep,name=snapshots" json:"snapshots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                             `json:"-"`
	XXX_unrecognized     []byte                                               `json:"-"`
	XXX_sizecache        int32                                                `json:"-"`
}

func (m *GetSpaceQuotaSnapshotsResponse) Reset()         { *m = GetSpaceQuotaSnapshotsResponse{} }
func (m *GetSpaceQuotaSnapshotsResponse) String() string { return proto.CompactTextString(m) }
func (*GetSpaceQuotaSnapshotsResponse) ProtoMessage()    {}
func (*GetSpaceQuotaSnapshotsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{12}
}

func (m *GetSpaceQuotaSnapshotsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpaceQuotaSnapshotsResponse.Unmarshal(m, b)
}
func (m *GetSpaceQuotaSnapshotsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpaceQuotaSnapshotsResponse.Marshal(b, m, deterministic)
}
func (m *GetSpaceQuotaSnapshotsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpaceQuotaSnapshotsResponse.Merge(m, src)
}
func (m *GetSpaceQuotaSnapshotsResponse) XXX_Size() int {
	return xxx_messageInfo_GetSpaceQuotaSnapshotsResponse.Size(m)
}
func (m *GetSpaceQuotaSnapshotsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpaceQuotaSnapshotsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpaceQuotaSnapshotsResponse proto.InternalMessageInfo

func (m *GetSpaceQuotaSnapshotsResponse) GetSnapshots() []*GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot {
	if m != nil {
		return m.Snapshots
	}
	return nil
}

// Cannot use TableName as a map key, do the repeated nested message by hand.
type GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot struct {
	TableName            *TableName          `protobuf:"bytes,1,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	Snapshot             *SpaceQuotaSnapshot `protobuf:"bytes,2,opt,name=snapshot" json:"snapshot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot) Reset() {
	*m = GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot{}
}
func (m *GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot) String() string {
	return proto.CompactTextString(m)
}
func (*GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot) ProtoMessage() {}
func (*GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{12, 0}
}

func (m *GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot.Unmarshal(m, b)
}
func (m *GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot.Marshal(b, m, deterministic)
}
func (m *GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot.Merge(m, src)
}
func (m *GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot) XXX_Size() int {
	return xxx_messageInfo_GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot.Size(m)
}
func (m *GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot proto.InternalMessageInfo

func (m *GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot) GetSnapshot() *SpaceQuotaSnapshot {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

type GetQuotaStatesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQuotaStatesRequest) Reset()         { *m = GetQuotaStatesRequest{} }
func (m *GetQuotaStatesRequest) String() string { return proto.CompactTextString(m) }
func (*GetQuotaStatesRequest) ProtoMessage()    {}
func (*GetQuotaStatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{13}
}

func (m *GetQuotaStatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuotaStatesRequest.Unmarshal(m, b)
}
func (m *GetQuotaStatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuotaStatesRequest.Marshal(b, m, deterministic)
}
func (m *GetQuotaStatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuotaStatesRequest.Merge(m, src)
}
func (m *GetQuotaStatesRequest) XXX_Size() int {
	return xxx_messageInfo_GetQuotaStatesRequest.Size(m)
}
func (m *GetQuotaStatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuotaStatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuotaStatesRequest proto.InternalMessageInfo

type GetQuotaStatesResponse struct {
	TableSnapshots       []*GetQuotaStatesResponse_TableQuotaSnapshot     `protobuf:"bytes,1,rep,name=table_snapshots,json=tableSnapshots" json:"table_snapshots,omitempty"`
	NsSnapshots          []*GetQuotaStatesResponse_NamespaceQuotaSnapshot `protobuf:"bytes,2,rep,name=ns_snapshots,json=nsSnapshots" json:"ns_snapshots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                         `json:"-"`
	XXX_unrecognized     []byte                                           `json:"-"`
	XXX_sizecache        int32                                            `json:"-"`
}

func (m *GetQuotaStatesResponse) Reset()         { *m = GetQuotaStatesResponse{} }
func (m *GetQuotaStatesResponse) String() string { return proto.CompactTextString(m) }
func (*GetQuotaStatesResponse) ProtoMessage()    {}
func (*GetQuotaStatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{14}
}

func (m *GetQuotaStatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuotaStatesResponse.Unmarshal(m, b)
}
func (m *GetQuotaStatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuotaStatesResponse.Marshal(b, m, deterministic)
}
func (m *GetQuotaStatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuotaStatesResponse.Merge(m, src)
}
func (m *GetQuotaStatesResponse) XXX_Size() int {
	return xxx_messageInfo_GetQuotaStatesResponse.Size(m)
}
func (m *GetQuotaStatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuotaStatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuotaStatesResponse proto.InternalMessageInfo

func (m *GetQuotaStatesResponse) GetTableSnapshots() []*GetQuotaStatesResponse_TableQuotaSnapshot {
	if m != nil {
		return m.TableSnapshots
	}
	return nil
}

func (m *GetQuotaStatesResponse) GetNsSnapshots() []*GetQuotaStatesResponse_NamespaceQuotaSnapshot {
	if m != nil {
		return m.NsSnapshots
	}
	return nil
}

type GetQuotaStatesResponse_TableQuotaSnapshot struct {
	TableName            *TableName          `protobuf:"bytes,1,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	Snapshot             *SpaceQuotaSnapshot `protobuf:"bytes,2,opt,name=snapshot" json:"snapshot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetQuotaStatesResponse_TableQuotaSnapshot) Reset() {
	*m = GetQuotaStatesResponse_TableQuotaSnapshot{}
}
func (m *GetQuotaStatesResponse_TableQuotaSnapshot) String() string {
	return proto.CompactTextString(m)
}
func (*GetQuotaStatesResponse_TableQuotaSnapshot) ProtoMessage() {}
func (*GetQuotaStatesResponse_TableQuotaSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{14, 0}
}

func (m *GetQuotaStatesResponse_TableQuotaSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuotaStatesResponse_TableQuotaSnapshot.Unmarshal(m, b)
}
func (m *GetQuotaStatesResponse_TableQuotaSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuotaStatesResponse_TableQuotaSnapshot.Marshal(b, m, deterministic)
}
func (m *GetQuotaStatesResponse_TableQuotaSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuotaStatesResponse_TableQuotaSnapshot.Merge(m, src)
}
func (m *GetQuotaStatesResponse_TableQuotaSnapshot) XXX_Size() int {
	return xxx_messageInfo_GetQuotaStatesResponse_TableQuotaSnapshot.Size(m)
}
func (m *GetQuotaStatesResponse_TableQuotaSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuotaStatesResponse_TableQuotaSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuotaStatesResponse_TableQuotaSnapshot proto.InternalMessageInfo

func (m *GetQuotaStatesResponse_TableQuotaSnapshot) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *GetQuotaStatesResponse_TableQuotaSnapshot) GetSnapshot() *SpaceQuotaSnapshot {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

type GetQuotaStatesResponse_NamespaceQuotaSnapshot struct {
	Namespace            *string             `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	Snapshot             *SpaceQuotaSnapshot `protobuf:"bytes,2,opt,name=snapshot" json:"snapshot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetQuotaStatesResponse_NamespaceQuotaSnapshot) Reset() {
	*m = GetQuotaStatesResponse_NamespaceQuotaSnapshot{}
}
func (m *GetQuotaStatesResponse_NamespaceQuotaSnapshot) String() string {
	return proto.CompactTextString(m)
}
func (*GetQuotaStatesResponse_NamespaceQuotaSnapshot) ProtoMessage() {}
func (*GetQuotaStatesResponse_NamespaceQuotaSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_826482451967f22b, []int{14, 1}
}

func (m *GetQuotaStatesResponse_NamespaceQuotaSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuotaStatesResponse_NamespaceQuotaSnapshot.Unmarshal(m, b)
}
func (m *GetQuotaStatesResponse_NamespaceQuotaSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuotaStatesResponse_NamespaceQuotaSnapshot.Marshal(b, m, deterministic)
}
func (m *GetQuotaStatesResponse_NamespaceQuotaSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuotaStatesResponse_NamespaceQuotaSnapshot.Merge(m, src)
}
func (m *GetQuotaStatesResponse_NamespaceQuotaSnapshot) XXX_Size() int {
	return xxx_messageInfo_GetQuotaStatesResponse_NamespaceQuotaSnapshot.Size(m)
}
func (m *GetQuotaStatesResponse_NamespaceQuotaSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuotaStatesResponse_NamespaceQuotaSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuotaStatesResponse_NamespaceQuotaSnapshot proto.InternalMessageInfo

func (m *GetQuotaStatesResponse_NamespaceQuotaSnapshot) GetNamespace() string {
	if m != nil && m.Namespace != nil {
		return *m.Namespace
	}
	return ""
}

func (m *GetQuotaStatesResponse_NamespaceQuotaSnapshot) GetSnapshot() *SpaceQuotaSnapshot {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

func init() {
	proto.RegisterEnum("hbase.pb.QuotaScope", QuotaScope_name, QuotaScope_value)
	proto.RegisterEnum("hbase.pb.ThrottleType", ThrottleType_name, ThrottleType_value)
	proto.RegisterEnum("hbase.pb.QuotaType", QuotaType_name, QuotaType_value)
	proto.RegisterEnum("hbase.pb.SpaceViolationPolicy", SpaceViolationPolicy_name, SpaceViolationPolicy_value)
	proto.RegisterType((*TimedQuota)(nil), "hbase.pb.TimedQuota")
	proto.RegisterType((*Throttle)(nil), "hbase.pb.Throttle")
	proto.RegisterType((*ThrottleRequest)(nil), "hbase.pb.ThrottleRequest")
	proto.RegisterType((*Quotas)(nil), "hbase.pb.Quotas")
	proto.RegisterType((*QuotaUsage)(nil), "hbase.pb.QuotaUsage")
	proto.RegisterType((*SpaceQuota)(nil), "hbase.pb.SpaceQuota")
	proto.RegisterType((*SpaceLimitRequest)(nil), "hbase.pb.SpaceLimitRequest")
	proto.RegisterType((*SpaceQuotaStatus)(nil), "hbase.pb.SpaceQuotaStatus")
	proto.RegisterType((*SpaceQuotaSnapshot)(nil), "hbase.pb.SpaceQuotaSnapshot")
	proto.RegisterType((*GetSpaceQuotaRegionSizesRequest)(nil), "hbase.pb.GetSpaceQuotaRegionSizesRequest")
	proto.RegisterType((*GetSpaceQuotaRegionSizesResponse)(nil), "hbase.pb.GetSpaceQuotaRegionSizesResponse")
	proto.RegisterType((*GetSpaceQuotaRegionSizesResponse_RegionSizes)(nil), "hbase.pb.GetSpaceQuotaRegionSizesResponse.RegionSizes")
	proto.RegisterType((*GetSpaceQuotaSnapshotsRequest)(nil), "hbase.pb.GetSpaceQuotaSnapshotsRequest")
	proto.RegisterType((*GetSpaceQuotaSnapshotsResponse)(nil), "hbase.pb.GetSpaceQuotaSnapshotsResponse")
	proto.RegisterType((*GetSpaceQuotaSnapshotsResponse_TableQuotaSnapshot)(nil), "hbase.pb.GetSpaceQuotaSnapshotsResponse.TableQuotaSnapshot")
	proto.RegisterType((*GetQuotaStatesRequest)(nil), "hbase.pb.GetQuotaStatesRequest")
	proto.RegisterType((*GetQuotaStatesResponse)(nil), "hbase.pb.GetQuotaStatesResponse")
	proto.RegisterType((*GetQuotaStatesResponse_TableQuotaSnapshot)(nil), "hbase.pb.GetQuotaStatesResponse.TableQuotaSnapshot")
	proto.RegisterType((*GetQuotaStatesResponse_NamespaceQuotaSnapshot)(nil), "hbase.pb.GetQuotaStatesResponse.NamespaceQuotaSnapshot")
}

func init() { proto.RegisterFile("Quota.proto", fileDescriptor_826482451967f22b) }

var fileDescriptor_826482451967f22b = []byte{
	// 1123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x5f, 0x6f, 0xdb, 0xb6,
	0x17, 0x05, 0xfd, 0x27, 0x91, 0xae, 0x5d, 0x47, 0x65, 0x93, 0x34, 0x0d, 0x9a, 0xc6, 0x15, 0x7e,
	0xf8, 0xc1, 0x08, 0x36, 0x17, 0x71, 0xb0, 0x3f, 0xe8, 0x30, 0x6c, 0xb6, 0x63, 0x24, 0x06, 0x12,
	0x27, 0xa5, 0xe4, 0x0d, 0x2d, 0x36, 0x08, 0x72, 0xcc, 0xc4, 0x02, 0x6c, 0x49, 0x36, 0xe9, 0x0c,
	0xe9, 0x53, 0xd1, 0xa7, 0x3d, 0x0f, 0xd8, 0xfb, 0xde, 0xf6, 0x3d, 0xf6, 0x32, 0xec, 0x5b, 0x0d,
	0x24, 0x25, 0x59, 0x4e, 0x1c, 0x17, 0xc8, 0xd3, 0xde, 0xe8, 0x7b, 0xcf, 0x3d, 0xf7, 0x9c, 0x4b,
	0x8a, 0x26, 0x14, 0xde, 0x4c, 0x03, 0xee, 0x56, 0xc3, 0x49, 0xc0, 0x03, 0xac, 0x0d, 0x7a, 0x2e,
	0xa3, 0xd5, 0xb0, 0xb7, 0x5d, 0x38, 0x6e, 0xc8, 0x95, 0x08, 0x9b, 0x7f, 0x22, 0x00, 0xdb, 0x1b,
	0xd1, 0xbe, 0xc4, 0xe2, 0x57, 0xa0, 0x73, 0x6f, 0x44, 0x9d, 0xa9, 0xef, 0xf1, 0x2d, 0x54, 0xce,
	0x54, 0x4a, 0x35, 0x5c, 0x8d, 0x2b, 0xab, 0x02, 0xd8, 0xf5, 0x3d, 0x4e, 0x34, 0x1e, 0xad, 0xf0,
	0x0e, 0x00, 0x0b, 0x2e, 0xb9, 0x33, 0xf4, 0x46, 0x1e, 0xdf, 0xca, 0x94, 0x51, 0x25, 0x47, 0x74,
	0x11, 0x39, 0x11, 0x01, 0xbc, 0x0e, 0x79, 0x36, 0x70, 0x27, 0x74, 0x2b, 0x5b, 0x46, 0x95, 0x0c,
	0x51, 0x3f, 0xf0, 0x01, 0xe4, 0xd9, 0x45, 0x10, 0xd2, 0xad, 0x5c, 0x19, 0x55, 0x4a, 0xb5, 0xf5,
	0x59, 0x07, 0xa9, 0xc2, 0x12, 0xb9, 0xd7, 0xab, 0xa7, 0xf5, 0xe6, 0x71, 0xbb, 0xd3, 0x22, 0x0a,
	0x6b, 0x7e, 0xcc, 0x81, 0x66, 0x0f, 0x26, 0x01, 0xe7, 0x43, 0x8a, 0x3f, 0x87, 0xd5, 0x09, 0x1d,
	0x3b, 0xfe, 0x74, 0xb4, 0x85, 0xca, 0xa8, 0x52, 0x48, 0x73, 0xcc, 0xec, 0x90, 0x95, 0x09, 0x1d,
	0x77, 0xa6, 0x23, 0xfc, 0x0a, 0x34, 0x01, 0x67, 0xde, 0x7b, 0x2a, 0x35, 0xde, 0x87, 0x17, 0xa4,
	0x96, 0xf7, 0x9e, 0xe2, 0x7d, 0xd0, 0x7f, 0x99, 0x78, 0x9c, 0xca, 0x0e, 0xd9, 0x25, 0x15, 0x9a,
	0x84, 0x89, 0x1e, 0x07, 0x00, 0xaa, 0x44, 0x76, 0xc9, 0x2d, 0xa9, 0x51, 0xd4, 0xb2, 0x8f, 0x14,
	0xe6, 0xf6, 0x65, 0x9b, 0xfc, 0x72, 0x61, 0x6e, 0x5f, 0x74, 0xd9, 0x07, 0x5d, 0x16, 0xc8, 0x26,
	0x2b, 0xcb, 0x84, 0x09, 0x98, 0xec, 0xf1, 0x3d, 0x3c, 0x16, 0xe6, 0x2f, 0xdc, 0xd0, 0xbd, 0xf0,
	0xf8, 0x8d, 0xda, 0xdb, 0xd5, 0x25, 0xa5, 0x6b, 0x13, 0x3a, 0x6e, 0x46, 0x68, 0xb9, 0xc9, 0x87,
	0xf0, 0x44, 0x59, 0x9b, 0xe7, 0xd0, 0x96, 0x70, 0x3c, 0x96, 0x05, 0x73, 0x2c, 0x0d, 0xc0, 0x52,
	0xfa, 0x3c, 0x89, 0xbe, 0x84, 0xc4, 0x10, 0xf8, 0x34, 0x87, 0xc9, 0x61, 0x2d, 0x3e, 0x03, 0x84,
	0x8e, 0xa7, 0x94, 0x71, 0xbc, 0x07, 0x39, 0x7e, 0x13, 0x52, 0x79, 0x0e, 0x4a, 0xb5, 0xcd, 0x14,
	0x51, 0x04, 0xb4, 0x6f, 0x42, 0x4a, 0x24, 0x06, 0x7f, 0x01, 0x05, 0x71, 0x72, 0xfb, 0xce, 0x58,
	0xf0, 0x2f, 0x3d, 0x0a, 0xc0, 0x93, 0xb5, 0xf9, 0x1b, 0x82, 0x15, 0xb9, 0x62, 0xf8, 0x33, 0x28,
	0xf5, 0x6e, 0x42, 0x97, 0x31, 0xe7, 0x6a, 0x18, 0xf4, 0xdc, 0x21, 0x93, 0x7d, 0xb5, 0xd7, 0xf9,
	0x4b, 0x77, 0xc8, 0x28, 0x79, 0xa4, 0x92, 0x47, 0x2a, 0x87, 0xab, 0xa0, 0xf1, 0x48, 0x45, 0xd4,
	0x0c, 0xdf, 0xd5, 0x47, 0x12, 0x0c, 0xde, 0x83, 0x3c, 0x0b, 0xdd, 0x0b, 0x7a, 0xf7, 0xc8, 0x59,
	0x22, 0xac, 0x94, 0x29, 0x88, 0x59, 0x04, 0x90, 0xbf, 0xbb, 0xcc, 0xbd, 0xa2, 0xe6, 0xef, 0x08,
	0x60, 0x86, 0xb9, 0xf5, 0x59, 0xa2, 0xdb, 0x9f, 0x65, 0x1b, 0x8c, 0x6b, 0x2f, 0x18, 0xba, 0xdc,
	0x0b, 0x7c, 0x27, 0x0c, 0x86, 0xde, 0xc5, 0x8d, 0xd4, 0x57, 0xaa, 0xbd, 0xb8, 0xd5, 0xf2, 0x87,
	0x18, 0x76, 0x2e, 0x51, 0x64, 0xed, 0x7a, 0x3e, 0x80, 0x77, 0x60, 0x65, 0x42, 0x47, 0xc1, 0xb5,
	0xd2, 0x9c, 0x0c, 0x22, 0x0a, 0x9a, 0xdf, 0xc1, 0x63, 0xc9, 0x23, 0xfb, 0xce, 0xb6, 0x2c, 0xaf,
	0x36, 0x00, 0x2d, 0xb3, 0x29, 0x21, 0xe6, 0x07, 0x04, 0xc6, 0x2c, 0x6a, 0x71, 0x97, 0x4f, 0xd9,
	0x42, 0xfd, 0xe8, 0x61, 0xfa, 0x5f, 0x42, 0xd1, 0xf3, 0x9d, 0x24, 0x2a, 0xc7, 0xa0, 0x91, 0x82,
	0xe7, 0x27, 0x95, 0x62, 0xb6, 0x38, 0x25, 0xc1, 0x77, 0x43, 0x36, 0x08, 0x38, 0xfe, 0x16, 0x8a,
	0x52, 0xa2, 0xc3, 0xa4, 0xa8, 0xc8, 0xcc, 0xf6, 0x22, 0x33, 0x4a, 0x36, 0x29, 0x8c, 0x53, 0x1e,
	0x76, 0x41, 0xfd, 0x74, 0xa6, 0x62, 0x03, 0xa3, 0xab, 0x13, 0xc6, 0xc9, 0x96, 0xce, 0x00, 0x6a,
	0x13, 0xb3, 0x29, 0x80, 0x9c, 0xa6, 0xf9, 0x12, 0x76, 0x8f, 0x28, 0x4f, 0x8d, 0x8c, 0x5e, 0x79,
	0x81, 0x2f, 0xbe, 0x79, 0x16, 0x4d, 0xda, 0xfc, 0x1b, 0x41, 0xf9, 0x7e, 0x0c, 0x0b, 0x03, 0x9f,
	0x51, 0x7c, 0x02, 0x79, 0x71, 0x9d, 0x08, 0x07, 0xd9, 0x4a, 0xa1, 0xf6, 0xe5, 0xcc, 0xc1, 0xa7,
	0x4a, 0xab, 0xe9, 0x98, 0x22, 0xd9, 0xee, 0x42, 0x21, 0x15, 0xc5, 0x35, 0x00, 0xee, 0xf6, 0x86,
	0xd4, 0xf1, 0xdd, 0x11, 0x8d, 0x66, 0xf4, 0x24, 0xf5, 0x11, 0x88, 0x5c, 0xc7, 0x1d, 0x51, 0xa2,
	0xf3, 0x78, 0x89, 0x31, 0xe4, 0x92, 0xab, 0x3a, 0x47, 0xe4, 0xda, 0xdc, 0x85, 0x9d, 0x39, 0x35,
	0xf1, 0x36, 0x24, 0x56, 0x3f, 0x64, 0xe0, 0xc5, 0x7d, 0x88, 0xc8, 0xe8, 0x5b, 0xd0, 0x59, 0x1c,
	0x8c, 0xcc, 0x7e, 0x73, 0x8f, 0xd9, 0x3b, 0xc5, 0x4a, 0xe9, 0x5c, 0x8e, 0xcc, 0xd8, 0xb6, 0x3f,
	0x22, 0xc0, 0x77, 0x11, 0x0f, 0x72, 0xff, 0x35, 0x68, 0x31, 0x6f, 0x74, 0x69, 0x3c, 0x5f, 0x78,
	0xa6, 0x62, 0x15, 0x09, 0xda, 0x7c, 0x0a, 0x1b, 0x47, 0x94, 0x27, 0x27, 0x6e, 0x76, 0x0c, 0xfe,
	0xc9, 0xc2, 0xe6, 0xed, 0x4c, 0x34, 0x93, 0x9f, 0x60, 0x4d, 0x29, 0xbc, 0x3d, 0x99, 0x83, 0xb9,
	0xc9, 0x2c, 0x28, 0x5d, 0x34, 0x91, 0x92, 0xe4, 0x4a, 0x86, 0x87, 0xdf, 0x41, 0xd1, 0x67, 0x29,
	0xea, 0x8c, 0xa4, 0xfe, 0xea, 0x93, 0xd4, 0x62, 0x10, 0xec, 0xae, 0xd5, 0x82, 0xcf, 0xac, 0xff,
	0xd4, 0xc8, 0xb7, 0x43, 0xd8, 0x5c, 0xac, 0x15, 0x3f, 0x07, 0xdd, 0x8f, 0x33, 0x52, 0x86, 0x4e,
	0x66, 0x81, 0x87, 0x77, 0xdc, 0xfb, 0x7f, 0x74, 0xef, 0xcb, 0x57, 0x12, 0x2e, 0xc0, 0x6a, 0xf3,
	0xa4, 0x6b, 0xd9, 0x2d, 0x62, 0x20, 0xf1, 0x23, 0x7a, 0x34, 0x19, 0x99, 0xbd, 0xbf, 0x10, 0x14,
	0xd3, 0x7f, 0x81, 0x18, 0x43, 0x89, 0xb4, 0xde, 0x74, 0x5b, 0x96, 0xed, 0x74, 0xba, 0xa7, 0x0d,
	0x59, 0x61, 0x40, 0x31, 0x8e, 0x59, 0xed, 0x77, 0x2d, 0x23, 0x23, 0x22, 0x3f, 0x92, 0xb6, 0xdd,
	0x8a, 0x31, 0x59, 0x5c, 0x02, 0x50, 0x11, 0x89, 0xc8, 0xe1, 0x35, 0x28, 0x90, 0x56, 0xfd, 0x30,
	0x06, 0xe4, 0xf1, 0x23, 0xd0, 0x65, 0x40, 0xe6, 0x57, 0xf0, 0x33, 0xd8, 0x88, 0x39, 0x9b, 0xf5,
	0xf3, 0x7a, 0xb3, 0x6d, 0xbf, 0x75, 0xba, 0x9d, 0xb6, 0x6d, 0xac, 0xe2, 0xa7, 0xf0, 0x44, 0x51,
	0xcd, 0x27, 0x34, 0xbc, 0x09, 0x58, 0x52, 0xcc, 0xc7, 0xf5, 0xbd, 0xff, 0x81, 0x2e, 0xcd, 0x4a,
	0x03, 0x45, 0xd0, 0xec, 0x63, 0x72, 0x66, 0xdb, 0x27, 0x2d, 0x03, 0x61, 0x1d, 0xf2, 0xd6, 0x79,
	0xbd, 0x29, 0xac, 0xfe, 0x0c, 0xeb, 0x8b, 0x2e, 0x7b, 0x31, 0x8f, 0xc3, 0xb6, 0x55, 0x6f, 0x48,
	0xfc, 0x33, 0xd8, 0xe8, 0x9c, 0x39, 0xb2, 0xbd, 0xe5, 0x34, 0xcf, 0x4e, 0xcf, 0xeb, 0x4d, 0xbb,
	0x7d, 0xd6, 0xb1, 0x8c, 0x8c, 0x30, 0x90, 0xa4, 0x94, 0xe1, 0xce, 0x99, 0xd3, 0xee, 0x58, 0x2d,
	0x62, 0x5b, 0x46, 0xae, 0x71, 0x0c, 0xfb, 0xc1, 0xe4, 0xaa, 0x2a, 0xde, 0x21, 0x03, 0x5a, 0x1d,
	0xb8, 0xfd, 0x20, 0x08, 0xa3, 0xcd, 0x62, 0x03, 0xb7, 0x4f, 0xfb, 0xea, 0x2d, 0xdd, 0x9b, 0x5e,
	0x56, 0xaf, 0xa8, 0x4f, 0x27, 0x2e, 0xa7, 0xfd, 0x86, 0x7a, 0x7c, 0x9f, 0x8b, 0x04, 0x3b, 0x46,
	0xbf, 0x22, 0xf4, 0x07, 0x42, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x87, 0xd3, 0x8c, 0x92,
	0x0b, 0x00, 0x00,
}
