// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Replication.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReplicationState_State int32

const (
	ReplicationState_ENABLED  ReplicationState_State = 0
	ReplicationState_DISABLED ReplicationState_State = 1
)

var ReplicationState_State_name = map[int32]string{
	0: "ENABLED",
	1: "DISABLED",
}

var ReplicationState_State_value = map[string]int32{
	"ENABLED":  0,
	"DISABLED": 1,
}

func (x ReplicationState_State) Enum() *ReplicationState_State {
	p := new(ReplicationState_State)
	*p = x
	return p
}

func (x ReplicationState_State) String() string {
	return proto.EnumName(ReplicationState_State_name, int32(x))
}

func (x *ReplicationState_State) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ReplicationState_State_value, data, "ReplicationState_State")
	if err != nil {
		return err
	}
	*x = ReplicationState_State(value)
	return nil
}

func (ReplicationState_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{2, 0}
}

type TableCF struct {
	TableName            *TableName `protobuf:"bytes,1,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	Families             [][]byte   `protobuf:"bytes,2,rep,name=families" json:"families,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TableCF) Reset()         { *m = TableCF{} }
func (m *TableCF) String() string { return proto.CompactTextString(m) }
func (*TableCF) ProtoMessage()    {}
func (*TableCF) Descriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{0}
}

func (m *TableCF) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableCF.Unmarshal(m, b)
}
func (m *TableCF) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableCF.Marshal(b, m, deterministic)
}
func (m *TableCF) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableCF.Merge(m, src)
}
func (m *TableCF) XXX_Size() int {
	return xxx_messageInfo_TableCF.Size(m)
}
func (m *TableCF) XXX_DiscardUnknown() {
	xxx_messageInfo_TableCF.DiscardUnknown(m)
}

var xxx_messageInfo_TableCF proto.InternalMessageInfo

func (m *TableCF) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *TableCF) GetFamilies() [][]byte {
	if m != nil {
		return m.Families
	}
	return nil
}

//*
// Used by replication. Holds a replication peer key.
type ReplicationPeer struct {
	// clusterkey is the concatenation of the slave cluster's
	// hbase.zookeeper.quorum:hbase.zookeeper.property.clientPort:zookeeper.znode.parent
	Clusterkey              *string           `protobuf:"bytes,1,opt,name=clusterkey" json:"clusterkey,omitempty"`
	ReplicationEndpointImpl *string           `protobuf:"bytes,2,opt,name=replicationEndpointImpl" json:"replicationEndpointImpl,omitempty"`
	Data                    []*BytesBytesPair `protobuf:"bytes,3,rep,name=data" json:"data,omitempty"`
	Configuration           []*NameStringPair `protobuf:"bytes,4,rep,name=configuration" json:"configuration,omitempty"`
	TableCfs                []*TableCF        `protobuf:"bytes,5,rep,name=table_cfs,json=tableCfs" json:"table_cfs,omitempty"`
	Namespaces              [][]byte          `protobuf:"bytes,6,rep,name=namespaces" json:"namespaces,omitempty"`
	Bandwidth               *int64            `protobuf:"varint,7,opt,name=bandwidth" json:"bandwidth,omitempty"`
	ReplicateAll            *bool             `protobuf:"varint,8,opt,name=replicate_all,json=replicateAll" json:"replicate_all,omitempty"`
	ExcludeTableCfs         []*TableCF        `protobuf:"bytes,9,rep,name=exclude_table_cfs,json=excludeTableCfs" json:"exclude_table_cfs,omitempty"`
	ExcludeNamespaces       [][]byte          `protobuf:"bytes,10,rep,name=exclude_namespaces,json=excludeNamespaces" json:"exclude_namespaces,omitempty"`
	Serial                  *bool             `protobuf:"varint,11,opt,name=serial" json:"serial,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}          `json:"-"`
	XXX_unrecognized        []byte            `json:"-"`
	XXX_sizecache           int32             `json:"-"`
}

func (m *ReplicationPeer) Reset()         { *m = ReplicationPeer{} }
func (m *ReplicationPeer) String() string { return proto.CompactTextString(m) }
func (*ReplicationPeer) ProtoMessage()    {}
func (*ReplicationPeer) Descriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{1}
}

func (m *ReplicationPeer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationPeer.Unmarshal(m, b)
}
func (m *ReplicationPeer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationPeer.Marshal(b, m, deterministic)
}
func (m *ReplicationPeer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationPeer.Merge(m, src)
}
func (m *ReplicationPeer) XXX_Size() int {
	return xxx_messageInfo_ReplicationPeer.Size(m)
}
func (m *ReplicationPeer) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationPeer.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationPeer proto.InternalMessageInfo

func (m *ReplicationPeer) GetClusterkey() string {
	if m != nil && m.Clusterkey != nil {
		return *m.Clusterkey
	}
	return ""
}

func (m *ReplicationPeer) GetReplicationEndpointImpl() string {
	if m != nil && m.ReplicationEndpointImpl != nil {
		return *m.ReplicationEndpointImpl
	}
	return ""
}

func (m *ReplicationPeer) GetData() []*BytesBytesPair {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ReplicationPeer) GetConfiguration() []*NameStringPair {
	if m != nil {
		return m.Configuration
	}
	return nil
}

func (m *ReplicationPeer) GetTableCfs() []*TableCF {
	if m != nil {
		return m.TableCfs
	}
	return nil
}

func (m *ReplicationPeer) GetNamespaces() [][]byte {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

func (m *ReplicationPeer) GetBandwidth() int64 {
	if m != nil && m.Bandwidth != nil {
		return *m.Bandwidth
	}
	return 0
}

func (m *ReplicationPeer) GetReplicateAll() bool {
	if m != nil && m.ReplicateAll != nil {
		return *m.ReplicateAll
	}
	return false
}

func (m *ReplicationPeer) GetExcludeTableCfs() []*TableCF {
	if m != nil {
		return m.ExcludeTableCfs
	}
	return nil
}

func (m *ReplicationPeer) GetExcludeNamespaces() [][]byte {
	if m != nil {
		return m.ExcludeNamespaces
	}
	return nil
}

func (m *ReplicationPeer) GetSerial() bool {
	if m != nil && m.Serial != nil {
		return *m.Serial
	}
	return false
}

//*
// Used by replication. Holds whether enabled or disabled
type ReplicationState struct {
	State                *ReplicationState_State `protobuf:"varint,1,req,name=state,enum=hbase.pb.ReplicationState_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ReplicationState) Reset()         { *m = ReplicationState{} }
func (m *ReplicationState) String() string { return proto.CompactTextString(m) }
func (*ReplicationState) ProtoMessage()    {}
func (*ReplicationState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{2}
}

func (m *ReplicationState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationState.Unmarshal(m, b)
}
func (m *ReplicationState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationState.Marshal(b, m, deterministic)
}
func (m *ReplicationState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationState.Merge(m, src)
}
func (m *ReplicationState) XXX_Size() int {
	return xxx_messageInfo_ReplicationState.Size(m)
}
func (m *ReplicationState) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationState.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationState proto.InternalMessageInfo

func (m *ReplicationState) GetState() ReplicationState_State {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ReplicationState_ENABLED
}

//*
// Used by replication. Description of the replication peer.
type ReplicationPeerDescription struct {
	Id                   *string           `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	State                *ReplicationState `protobuf:"bytes,2,req,name=state" json:"state,omitempty"`
	Config               *ReplicationPeer  `protobuf:"bytes,3,req,name=config" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReplicationPeerDescription) Reset()         { *m = ReplicationPeerDescription{} }
func (m *ReplicationPeerDescription) String() string { return proto.CompactTextString(m) }
func (*ReplicationPeerDescription) ProtoMessage()    {}
func (*ReplicationPeerDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{3}
}

func (m *ReplicationPeerDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationPeerDescription.Unmarshal(m, b)
}
func (m *ReplicationPeerDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationPeerDescription.Marshal(b, m, deterministic)
}
func (m *ReplicationPeerDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationPeerDescription.Merge(m, src)
}
func (m *ReplicationPeerDescription) XXX_Size() int {
	return xxx_messageInfo_ReplicationPeerDescription.Size(m)
}
func (m *ReplicationPeerDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationPeerDescription.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationPeerDescription proto.InternalMessageInfo

func (m *ReplicationPeerDescription) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *ReplicationPeerDescription) GetState() *ReplicationState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *ReplicationPeerDescription) GetConfig() *ReplicationPeer {
	if m != nil {
		return m.Config
	}
	return nil
}

//*
// Used by replication. Holds the current position in an WAL file.
type ReplicationHLogPosition struct {
	Position             *int64   `protobuf:"varint,1,req,name=position" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicationHLogPosition) Reset()         { *m = ReplicationHLogPosition{} }
func (m *ReplicationHLogPosition) String() string { return proto.CompactTextString(m) }
func (*ReplicationHLogPosition) ProtoMessage()    {}
func (*ReplicationHLogPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{4}
}

func (m *ReplicationHLogPosition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationHLogPosition.Unmarshal(m, b)
}
func (m *ReplicationHLogPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationHLogPosition.Marshal(b, m, deterministic)
}
func (m *ReplicationHLogPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationHLogPosition.Merge(m, src)
}
func (m *ReplicationHLogPosition) XXX_Size() int {
	return xxx_messageInfo_ReplicationHLogPosition.Size(m)
}
func (m *ReplicationHLogPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationHLogPosition.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationHLogPosition proto.InternalMessageInfo

func (m *ReplicationHLogPosition) GetPosition() int64 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

type AddReplicationPeerRequest struct {
	PeerId               *string           `protobuf:"bytes,1,req,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	PeerConfig           *ReplicationPeer  `protobuf:"bytes,2,req,name=peer_config,json=peerConfig" json:"peer_config,omitempty"`
	PeerState            *ReplicationState `protobuf:"bytes,3,req,name=peer_state,json=peerState" json:"peer_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AddReplicationPeerRequest) Reset()         { *m = AddReplicationPeerRequest{} }
func (m *AddReplicationPeerRequest) String() string { return proto.CompactTextString(m) }
func (*AddReplicationPeerRequest) ProtoMessage()    {}
func (*AddReplicationPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{5}
}

func (m *AddReplicationPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReplicationPeerRequest.Unmarshal(m, b)
}
func (m *AddReplicationPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReplicationPeerRequest.Marshal(b, m, deterministic)
}
func (m *AddReplicationPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReplicationPeerRequest.Merge(m, src)
}
func (m *AddReplicationPeerRequest) XXX_Size() int {
	return xxx_messageInfo_AddReplicationPeerRequest.Size(m)
}
func (m *AddReplicationPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReplicationPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddReplicationPeerRequest proto.InternalMessageInfo

func (m *AddReplicationPeerRequest) GetPeerId() string {
	if m != nil && m.PeerId != nil {
		return *m.PeerId
	}
	return ""
}

func (m *AddReplicationPeerRequest) GetPeerConfig() *ReplicationPeer {
	if m != nil {
		return m.PeerConfig
	}
	return nil
}

func (m *AddReplicationPeerRequest) GetPeerState() *ReplicationState {
	if m != nil {
		return m.PeerState
	}
	return nil
}

type AddReplicationPeerResponse struct {
	ProcId               *uint64  `protobuf:"varint,1,opt,name=proc_id,json=procId" json:"proc_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReplicationPeerResponse) Reset()         { *m = AddReplicationPeerResponse{} }
func (m *AddReplicationPeerResponse) String() string { return proto.CompactTextString(m) }
func (*AddReplicationPeerResponse) ProtoMessage()    {}
func (*AddReplicationPeerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{6}
}

func (m *AddReplicationPeerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReplicationPeerResponse.Unmarshal(m, b)
}
func (m *AddReplicationPeerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReplicationPeerResponse.Marshal(b, m, deterministic)
}
func (m *AddReplicationPeerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReplicationPeerResponse.Merge(m, src)
}
func (m *AddReplicationPeerResponse) XXX_Size() int {
	return xxx_messageInfo_AddReplicationPeerResponse.Size(m)
}
func (m *AddReplicationPeerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReplicationPeerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddReplicationPeerResponse proto.InternalMessageInfo

func (m *AddReplicationPeerResponse) GetProcId() uint64 {
	if m != nil && m.ProcId != nil {
		return *m.ProcId
	}
	return 0
}

type RemoveReplicationPeerRequest struct {
	PeerId               *string  `protobuf:"bytes,1,req,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveReplicationPeerRequest) Reset()         { *m = RemoveReplicationPeerRequest{} }
func (m *RemoveReplicationPeerRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveReplicationPeerRequest) ProtoMessage()    {}
func (*RemoveReplicationPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{7}
}

func (m *RemoveReplicationPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveReplicationPeerRequest.Unmarshal(m, b)
}
func (m *RemoveReplicationPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveReplicationPeerRequest.Marshal(b, m, deterministic)
}
func (m *RemoveReplicationPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveReplicationPeerRequest.Merge(m, src)
}
func (m *RemoveReplicationPeerRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveReplicationPeerRequest.Size(m)
}
func (m *RemoveReplicationPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveReplicationPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveReplicationPeerRequest proto.InternalMessageInfo

func (m *RemoveReplicationPeerRequest) GetPeerId() string {
	if m != nil && m.PeerId != nil {
		return *m.PeerId
	}
	return ""
}

type RemoveReplicationPeerResponse struct {
	ProcId               *uint64  `protobuf:"varint,1,opt,name=proc_id,json=procId" json:"proc_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveReplicationPeerResponse) Reset()         { *m = RemoveReplicationPeerResponse{} }
func (m *RemoveReplicationPeerResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveReplicationPeerResponse) ProtoMessage()    {}
func (*RemoveReplicationPeerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{8}
}

func (m *RemoveReplicationPeerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveReplicationPeerResponse.Unmarshal(m, b)
}
func (m *RemoveReplicationPeerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveReplicationPeerResponse.Marshal(b, m, deterministic)
}
func (m *RemoveReplicationPeerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveReplicationPeerResponse.Merge(m, src)
}
func (m *RemoveReplicationPeerResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveReplicationPeerResponse.Size(m)
}
func (m *RemoveReplicationPeerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveReplicationPeerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveReplicationPeerResponse proto.InternalMessageInfo

func (m *RemoveReplicationPeerResponse) GetProcId() uint64 {
	if m != nil && m.ProcId != nil {
		return *m.ProcId
	}
	return 0
}

type EnableReplicationPeerRequest struct {
	PeerId               *string  `protobuf:"bytes,1,req,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableReplicationPeerRequest) Reset()         { *m = EnableReplicationPeerRequest{} }
func (m *EnableReplicationPeerRequest) String() string { return proto.CompactTextString(m) }
func (*EnableReplicationPeerRequest) ProtoMessage()    {}
func (*EnableReplicationPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{9}
}

func (m *EnableReplicationPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableReplicationPeerRequest.Unmarshal(m, b)
}
func (m *EnableReplicationPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableReplicationPeerRequest.Marshal(b, m, deterministic)
}
func (m *EnableReplicationPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableReplicationPeerRequest.Merge(m, src)
}
func (m *EnableReplicationPeerRequest) XXX_Size() int {
	return xxx_messageInfo_EnableReplicationPeerRequest.Size(m)
}
func (m *EnableReplicationPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableReplicationPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnableReplicationPeerRequest proto.InternalMessageInfo

func (m *EnableReplicationPeerRequest) GetPeerId() string {
	if m != nil && m.PeerId != nil {
		return *m.PeerId
	}
	return ""
}

type EnableReplicationPeerResponse struct {
	ProcId               *uint64  `protobuf:"varint,1,opt,name=proc_id,json=procId" json:"proc_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableReplicationPeerResponse) Reset()         { *m = EnableReplicationPeerResponse{} }
func (m *EnableReplicationPeerResponse) String() string { return proto.CompactTextString(m) }
func (*EnableReplicationPeerResponse) ProtoMessage()    {}
func (*EnableReplicationPeerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{10}
}

func (m *EnableReplicationPeerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableReplicationPeerResponse.Unmarshal(m, b)
}
func (m *EnableReplicationPeerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableReplicationPeerResponse.Marshal(b, m, deterministic)
}
func (m *EnableReplicationPeerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableReplicationPeerResponse.Merge(m, src)
}
func (m *EnableReplicationPeerResponse) XXX_Size() int {
	return xxx_messageInfo_EnableReplicationPeerResponse.Size(m)
}
func (m *EnableReplicationPeerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableReplicationPeerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnableReplicationPeerResponse proto.InternalMessageInfo

func (m *EnableReplicationPeerResponse) GetProcId() uint64 {
	if m != nil && m.ProcId != nil {
		return *m.ProcId
	}
	return 0
}

type DisableReplicationPeerRequest struct {
	PeerId               *string  `protobuf:"bytes,1,req,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableReplicationPeerRequest) Reset()         { *m = DisableReplicationPeerRequest{} }
func (m *DisableReplicationPeerRequest) String() string { return proto.CompactTextString(m) }
func (*DisableReplicationPeerRequest) ProtoMessage()    {}
func (*DisableReplicationPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{11}
}

func (m *DisableReplicationPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableReplicationPeerRequest.Unmarshal(m, b)
}
func (m *DisableReplicationPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableReplicationPeerRequest.Marshal(b, m, deterministic)
}
func (m *DisableReplicationPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableReplicationPeerRequest.Merge(m, src)
}
func (m *DisableReplicationPeerRequest) XXX_Size() int {
	return xxx_messageInfo_DisableReplicationPeerRequest.Size(m)
}
func (m *DisableReplicationPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableReplicationPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisableReplicationPeerRequest proto.InternalMessageInfo

func (m *DisableReplicationPeerRequest) GetPeerId() string {
	if m != nil && m.PeerId != nil {
		return *m.PeerId
	}
	return ""
}

type DisableReplicationPeerResponse struct {
	ProcId               *uint64  `protobuf:"varint,1,opt,name=proc_id,json=procId" json:"proc_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableReplicationPeerResponse) Reset()         { *m = DisableReplicationPeerResponse{} }
func (m *DisableReplicationPeerResponse) String() string { return proto.CompactTextString(m) }
func (*DisableReplicationPeerResponse) ProtoMessage()    {}
func (*DisableReplicationPeerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{12}
}

func (m *DisableReplicationPeerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableReplicationPeerResponse.Unmarshal(m, b)
}
func (m *DisableReplicationPeerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableReplicationPeerResponse.Marshal(b, m, deterministic)
}
func (m *DisableReplicationPeerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableReplicationPeerResponse.Merge(m, src)
}
func (m *DisableReplicationPeerResponse) XXX_Size() int {
	return xxx_messageInfo_DisableReplicationPeerResponse.Size(m)
}
func (m *DisableReplicationPeerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableReplicationPeerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisableReplicationPeerResponse proto.InternalMessageInfo

func (m *DisableReplicationPeerResponse) GetProcId() uint64 {
	if m != nil && m.ProcId != nil {
		return *m.ProcId
	}
	return 0
}

type GetReplicationPeerConfigRequest struct {
	PeerId               *string  `protobuf:"bytes,1,req,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReplicationPeerConfigRequest) Reset()         { *m = GetReplicationPeerConfigRequest{} }
func (m *GetReplicationPeerConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetReplicationPeerConfigRequest) ProtoMessage()    {}
func (*GetReplicationPeerConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{13}
}

func (m *GetReplicationPeerConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReplicationPeerConfigRequest.Unmarshal(m, b)
}
func (m *GetReplicationPeerConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReplicationPeerConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetReplicationPeerConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReplicationPeerConfigRequest.Merge(m, src)
}
func (m *GetReplicationPeerConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetReplicationPeerConfigRequest.Size(m)
}
func (m *GetReplicationPeerConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReplicationPeerConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReplicationPeerConfigRequest proto.InternalMessageInfo

func (m *GetReplicationPeerConfigRequest) GetPeerId() string {
	if m != nil && m.PeerId != nil {
		return *m.PeerId
	}
	return ""
}

type GetReplicationPeerConfigResponse struct {
	PeerId               *string          `protobuf:"bytes,1,req,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	PeerConfig           *ReplicationPeer `protobuf:"bytes,2,req,name=peer_config,json=peerConfig" json:"peer_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetReplicationPeerConfigResponse) Reset()         { *m = GetReplicationPeerConfigResponse{} }
func (m *GetReplicationPeerConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetReplicationPeerConfigResponse) ProtoMessage()    {}
func (*GetReplicationPeerConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{14}
}

func (m *GetReplicationPeerConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReplicationPeerConfigResponse.Unmarshal(m, b)
}
func (m *GetReplicationPeerConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReplicationPeerConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetReplicationPeerConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReplicationPeerConfigResponse.Merge(m, src)
}
func (m *GetReplicationPeerConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetReplicationPeerConfigResponse.Size(m)
}
func (m *GetReplicationPeerConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReplicationPeerConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReplicationPeerConfigResponse proto.InternalMessageInfo

func (m *GetReplicationPeerConfigResponse) GetPeerId() string {
	if m != nil && m.PeerId != nil {
		return *m.PeerId
	}
	return ""
}

func (m *GetReplicationPeerConfigResponse) GetPeerConfig() *ReplicationPeer {
	if m != nil {
		return m.PeerConfig
	}
	return nil
}

type UpdateReplicationPeerConfigRequest struct {
	PeerId               *string          `protobuf:"bytes,1,req,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	PeerConfig           *ReplicationPeer `protobuf:"bytes,2,req,name=peer_config,json=peerConfig" json:"peer_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateReplicationPeerConfigRequest) Reset()         { *m = UpdateReplicationPeerConfigRequest{} }
func (m *UpdateReplicationPeerConfigRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateReplicationPeerConfigRequest) ProtoMessage()    {}
func (*UpdateReplicationPeerConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{15}
}

func (m *UpdateReplicationPeerConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReplicationPeerConfigRequest.Unmarshal(m, b)
}
func (m *UpdateReplicationPeerConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReplicationPeerConfigRequest.Marshal(b, m, deterministic)
}
func (m *UpdateReplicationPeerConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReplicationPeerConfigRequest.Merge(m, src)
}
func (m *UpdateReplicationPeerConfigRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateReplicationPeerConfigRequest.Size(m)
}
func (m *UpdateReplicationPeerConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReplicationPeerConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReplicationPeerConfigRequest proto.InternalMessageInfo

func (m *UpdateReplicationPeerConfigRequest) GetPeerId() string {
	if m != nil && m.PeerId != nil {
		return *m.PeerId
	}
	return ""
}

func (m *UpdateReplicationPeerConfigRequest) GetPeerConfig() *ReplicationPeer {
	if m != nil {
		return m.PeerConfig
	}
	return nil
}

type UpdateReplicationPeerConfigResponse struct {
	ProcId               *uint64  `protobuf:"varint,1,opt,name=proc_id,json=procId" json:"proc_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReplicationPeerConfigResponse) Reset()         { *m = UpdateReplicationPeerConfigResponse{} }
func (m *UpdateReplicationPeerConfigResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateReplicationPeerConfigResponse) ProtoMessage()    {}
func (*UpdateReplicationPeerConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{16}
}

func (m *UpdateReplicationPeerConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReplicationPeerConfigResponse.Unmarshal(m, b)
}
func (m *UpdateReplicationPeerConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReplicationPeerConfigResponse.Marshal(b, m, deterministic)
}
func (m *UpdateReplicationPeerConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReplicationPeerConfigResponse.Merge(m, src)
}
func (m *UpdateReplicationPeerConfigResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateReplicationPeerConfigResponse.Size(m)
}
func (m *UpdateReplicationPeerConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReplicationPeerConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReplicationPeerConfigResponse proto.InternalMessageInfo

func (m *UpdateReplicationPeerConfigResponse) GetProcId() uint64 {
	if m != nil && m.ProcId != nil {
		return *m.ProcId
	}
	return 0
}

type ListReplicationPeersRequest struct {
	Regex                *string  `protobuf:"bytes,1,opt,name=regex" json:"regex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReplicationPeersRequest) Reset()         { *m = ListReplicationPeersRequest{} }
func (m *ListReplicationPeersRequest) String() string { return proto.CompactTextString(m) }
func (*ListReplicationPeersRequest) ProtoMessage()    {}
func (*ListReplicationPeersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{17}
}

func (m *ListReplicationPeersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReplicationPeersRequest.Unmarshal(m, b)
}
func (m *ListReplicationPeersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReplicationPeersRequest.Marshal(b, m, deterministic)
}
func (m *ListReplicationPeersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReplicationPeersRequest.Merge(m, src)
}
func (m *ListReplicationPeersRequest) XXX_Size() int {
	return xxx_messageInfo_ListReplicationPeersRequest.Size(m)
}
func (m *ListReplicationPeersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReplicationPeersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListReplicationPeersRequest proto.InternalMessageInfo

func (m *ListReplicationPeersRequest) GetRegex() string {
	if m != nil && m.Regex != nil {
		return *m.Regex
	}
	return ""
}

type ListReplicationPeersResponse struct {
	PeerDesc             []*ReplicationPeerDescription `protobuf:"bytes,1,rep,name=peer_desc,json=peerDesc" json:"peer_desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ListReplicationPeersResponse) Reset()         { *m = ListReplicationPeersResponse{} }
func (m *ListReplicationPeersResponse) String() string { return proto.CompactTextString(m) }
func (*ListReplicationPeersResponse) ProtoMessage()    {}
func (*ListReplicationPeersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3074f200de73ae00, []int{18}
}

func (m *ListReplicationPeersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReplicationPeersResponse.Unmarshal(m, b)
}
func (m *ListReplicationPeersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReplicationPeersResponse.Marshal(b, m, deterministic)
}
func (m *ListReplicationPeersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReplicationPeersResponse.Merge(m, src)
}
func (m *ListReplicationPeersResponse) XXX_Size() int {
	return xxx_messageInfo_ListReplicationPeersResponse.Size(m)
}
func (m *ListReplicationPeersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReplicationPeersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListReplicationPeersResponse proto.InternalMessageInfo

func (m *ListReplicationPeersResponse) GetPeerDesc() []*ReplicationPeerDescription {
	if m != nil {
		return m.PeerDesc
	}
	return nil
}

func init() {
	proto.RegisterEnum("hbase.pb.ReplicationState_State", ReplicationState_State_name, ReplicationState_State_value)
	proto.RegisterType((*TableCF)(nil), "hbase.pb.TableCF")
	proto.RegisterType((*ReplicationPeer)(nil), "hbase.pb.ReplicationPeer")
	proto.RegisterType((*ReplicationState)(nil), "hbase.pb.ReplicationState")
	proto.RegisterType((*ReplicationPeerDescription)(nil), "hbase.pb.ReplicationPeerDescription")
	proto.RegisterType((*ReplicationHLogPosition)(nil), "hbase.pb.ReplicationHLogPosition")
	proto.RegisterType((*AddReplicationPeerRequest)(nil), "hbase.pb.AddReplicationPeerRequest")
	proto.RegisterType((*AddReplicationPeerResponse)(nil), "hbase.pb.AddReplicationPeerResponse")
	proto.RegisterType((*RemoveReplicationPeerRequest)(nil), "hbase.pb.RemoveReplicationPeerRequest")
	proto.RegisterType((*RemoveReplicationPeerResponse)(nil), "hbase.pb.RemoveReplicationPeerResponse")
	proto.RegisterType((*EnableReplicationPeerRequest)(nil), "hbase.pb.EnableReplicationPeerRequest")
	proto.RegisterType((*EnableReplicationPeerResponse)(nil), "hbase.pb.EnableReplicationPeerResponse")
	proto.RegisterType((*DisableReplicationPeerRequest)(nil), "hbase.pb.DisableReplicationPeerRequest")
	proto.RegisterType((*DisableReplicationPeerResponse)(nil), "hbase.pb.DisableReplicationPeerResponse")
	proto.RegisterType((*GetReplicationPeerConfigRequest)(nil), "hbase.pb.GetReplicationPeerConfigRequest")
	proto.RegisterType((*GetReplicationPeerConfigResponse)(nil), "hbase.pb.GetReplicationPeerConfigResponse")
	proto.RegisterType((*UpdateReplicationPeerConfigRequest)(nil), "hbase.pb.UpdateReplicationPeerConfigRequest")
	proto.RegisterType((*UpdateReplicationPeerConfigResponse)(nil), "hbase.pb.UpdateReplicationPeerConfigResponse")
	proto.RegisterType((*ListReplicationPeersRequest)(nil), "hbase.pb.ListReplicationPeersRequest")
	proto.RegisterType((*ListReplicationPeersResponse)(nil), "hbase.pb.ListReplicationPeersResponse")
}

func init() { proto.RegisterFile("Replication.proto", fileDescriptor_3074f200de73ae00) }

var fileDescriptor_3074f200de73ae00 = []byte{
	// 775 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x6e, 0xeb, 0x44,
	0x14, 0xc6, 0x76, 0x93, 0x38, 0x27, 0xbd, 0x3f, 0x1d, 0x10, 0xf5, 0x0d, 0xbd, 0x17, 0xcb, 0x97,
	0x85, 0x17, 0x60, 0x71, 0x83, 0x2e, 0xb4, 0x95, 0xa8, 0x94, 0xbf, 0xd2, 0x48, 0x55, 0x14, 0xb9,
	0x65, 0xc1, 0x2a, 0x9a, 0x78, 0x4e, 0x92, 0x11, 0x8e, 0x6d, 0x3c, 0x0e, 0x6d, 0xdf, 0x80, 0x2d,
	0x6f, 0xc0, 0x9e, 0xb7, 0xe3, 0x09, 0x90, 0xc7, 0x76, 0x62, 0xa2, 0x9a, 0x40, 0x61, 0x63, 0x9d,
	0x73, 0xe6, 0xfb, 0xe6, 0xfb, 0xce, 0x99, 0x89, 0x1d, 0x38, 0x72, 0x31, 0xf2, 0xb9, 0x47, 0x13,
	0x1e, 0x06, 0x4e, 0x14, 0x87, 0x49, 0x48, 0xf4, 0xe5, 0x8c, 0x0a, 0x74, 0xa2, 0x59, 0xbb, 0x75,
	0xd5, 0x93, 0x51, 0x5a, 0xb6, 0x7e, 0x80, 0xc6, 0x2d, 0x9d, 0xf9, 0xd8, 0xbf, 0x24, 0x1d, 0x80,
	0x24, 0x0d, 0xa7, 0x01, 0x5d, 0xa1, 0xa1, 0x98, 0x8a, 0xdd, 0xea, 0x7c, 0xe8, 0x14, 0x34, 0x47,
	0xc2, 0xc6, 0x74, 0x85, 0x6e, 0x33, 0x29, 0x42, 0xd2, 0x06, 0x7d, 0x4e, 0x57, 0xdc, 0xe7, 0x28,
	0x0c, 0xd5, 0xd4, 0xec, 0x43, 0x77, 0x93, 0x5b, 0x7f, 0x68, 0xf0, 0xa2, 0xe4, 0x63, 0x82, 0x18,
	0x93, 0x37, 0x00, 0x9e, 0xbf, 0x16, 0x09, 0xc6, 0x3f, 0xe2, 0x83, 0xd4, 0x68, 0xba, 0xa5, 0x0a,
	0x39, 0x85, 0xe3, 0x78, 0x4b, 0x19, 0x06, 0x2c, 0x0a, 0x79, 0x90, 0x8c, 0x56, 0x91, 0x6f, 0xa8,
	0x12, 0x5c, 0xb5, 0x4c, 0x3e, 0x87, 0x03, 0x46, 0x13, 0x6a, 0x68, 0xa6, 0x66, 0xb7, 0x3a, 0xc6,
	0xd6, 0x77, 0xef, 0x21, 0x41, 0x21, 0x1f, 0x13, 0xca, 0x63, 0x57, 0xa2, 0xc8, 0x05, 0x3c, 0xf3,
	0xc2, 0x60, 0xce, 0x17, 0xeb, 0x58, 0x6e, 0x65, 0x1c, 0xec, 0xd2, 0xd2, 0xf6, 0x6e, 0x92, 0x98,
	0x07, 0x0b, 0x49, 0xfb, 0x2b, 0x9c, 0x38, 0x90, 0x0d, 0x61, 0xea, 0xcd, 0x85, 0x51, 0x93, 0xdc,
	0xa3, 0x9d, 0x51, 0xf5, 0x2f, 0x5d, 0x5d, 0x62, 0xfa, 0x73, 0x91, 0xf6, 0x9d, 0x4e, 0x55, 0x44,
	0xd4, 0x43, 0x61, 0xd4, 0xe5, 0xa4, 0x4a, 0x15, 0x72, 0x02, 0xcd, 0x19, 0x0d, 0xd8, 0x1d, 0x67,
	0xc9, 0xd2, 0x68, 0x98, 0x8a, 0xad, 0xb9, 0xdb, 0x02, 0x79, 0x0b, 0xcf, 0x8a, 0xb6, 0x71, 0x4a,
	0x7d, 0xdf, 0xd0, 0x4d, 0xc5, 0xd6, 0xdd, 0xc3, 0x4d, 0xb1, 0xeb, 0xfb, 0xe4, 0x5b, 0x38, 0xc2,
	0x7b, 0xcf, 0x5f, 0x33, 0x9c, 0x6e, 0xad, 0x35, 0xab, 0xac, 0xbd, 0xc8, 0xb1, 0xb7, 0x85, 0xc3,
	0x2f, 0x80, 0x14, 0xf4, 0x92, 0x53, 0x90, 0x4e, 0x8b, 0x8d, 0xc7, 0x5b, 0xc3, 0x1f, 0x43, 0x5d,
	0x60, 0xcc, 0xa9, 0x6f, 0xb4, 0xa4, 0x97, 0x3c, 0xb3, 0x02, 0x78, 0x59, 0x3a, 0xf3, 0x9b, 0x84,
	0x26, 0x48, 0xbe, 0x86, 0x9a, 0x48, 0x03, 0x43, 0x31, 0x55, 0xfb, 0x79, 0xc7, 0xdc, 0xba, 0xd9,
	0x85, 0x3a, 0xf2, 0xe9, 0x66, 0x70, 0xcb, 0x82, 0x5a, 0xb6, 0x41, 0x0b, 0x1a, 0xc3, 0x71, 0xb7,
	0x77, 0x3d, 0x1c, 0xbc, 0xfc, 0x80, 0x1c, 0x82, 0x3e, 0x18, 0xdd, 0x64, 0x99, 0x62, 0xfd, 0xaa,
	0x40, 0x7b, 0xe7, 0x92, 0x0d, 0x50, 0x78, 0x31, 0x8f, 0xe4, 0x39, 0x3d, 0x07, 0x95, 0x33, 0xa9,
	0xdb, 0x74, 0x55, 0xce, 0xc8, 0x97, 0x85, 0x15, 0xd5, 0x54, 0xed, 0x56, 0xa7, 0x5d, 0x6d, 0x25,
	0x37, 0x41, 0xde, 0x41, 0x3d, 0x3b, 0x7a, 0x43, 0x93, 0x94, 0x57, 0x8f, 0x52, 0x52, 0x5d, 0x37,
	0x07, 0x5a, 0xef, 0xe1, 0xb8, 0xb4, 0x74, 0x75, 0x1d, 0x2e, 0x26, 0xa1, 0xe0, 0xd2, 0x4f, 0x1b,
	0xf4, 0x28, 0x8f, 0xa5, 0x2b, 0xcd, 0xdd, 0xe4, 0xd6, 0xef, 0x0a, 0xbc, 0xea, 0x32, 0xb6, 0xbb,
	0x2b, 0xfe, 0xb4, 0x46, 0x91, 0x90, 0x63, 0x68, 0x44, 0x88, 0xf1, 0x74, 0xd3, 0x4e, 0x3d, 0x4d,
	0x47, 0x8c, 0x9c, 0x43, 0x4b, 0x2e, 0xe4, 0x2e, 0xd5, 0x7d, 0x2e, 0x21, 0x45, 0xf7, 0x25, 0x98,
	0x9c, 0x81, 0xcc, 0xa6, 0xd9, 0x4c, 0xb4, 0xbd, 0x33, 0x69, 0xa6, 0x68, 0x19, 0x5a, 0xef, 0xa1,
	0xfd, 0x98, 0x59, 0x11, 0x85, 0x81, 0x40, 0xe9, 0x36, 0x0e, 0xbd, 0xcc, 0xad, 0x62, 0x1f, 0xb8,
	0xf5, 0x34, 0x1d, 0x31, 0xeb, 0x1b, 0x38, 0x71, 0x71, 0x15, 0xfe, 0x8c, 0xff, 0xb2, 0x4d, 0xeb,
	0x14, 0x5e, 0x57, 0x10, 0xff, 0x81, 0xe4, 0x30, 0x48, 0xaf, 0xf9, 0x13, 0x24, 0x2b, 0x88, 0xfb,
	0x24, 0x4f, 0xe1, 0xf5, 0x80, 0x8b, 0xa7, 0x68, 0x9e, 0xc1, 0x9b, 0x2a, 0xe6, 0x3e, 0xd1, 0x73,
	0xf8, 0xf4, 0x3b, 0x4c, 0x76, 0x68, 0xd9, 0x41, 0xef, 0x95, 0xbd, 0x03, 0xb3, 0x9a, 0x5b, 0x12,
	0xfe, 0xbf, 0x6f, 0xa0, 0xf5, 0x00, 0xd6, 0xf7, 0x11, 0x4b, 0xef, 0xd6, 0x53, 0x7c, 0xff, 0x27,
	0xe9, 0x0b, 0x78, 0xfb, 0xb7, 0xd2, 0xfb, 0xe6, 0xfd, 0x15, 0x7c, 0x72, 0xcd, 0xc5, 0xee, 0xd0,
	0x44, 0xe1, 0xf9, 0x23, 0xa8, 0xc5, 0xb8, 0xc0, 0xfb, 0xfc, 0x2b, 0x97, 0x25, 0x16, 0x85, 0x93,
	0xc7, 0x49, 0xb9, 0x5a, 0x17, 0xe4, 0x6f, 0x6c, 0xca, 0x50, 0x78, 0x86, 0x22, 0xdf, 0xde, 0x9f,
	0x55, 0xb6, 0x53, 0x7a, 0xd3, 0xb9, 0x7a, 0x94, 0x17, 0x7a, 0x63, 0x78, 0x17, 0xc6, 0x0b, 0x87,
	0x46, 0xd4, 0x5b, 0xa2, 0xb3, 0xa4, 0x2c, 0x0c, 0xa3, 0x7c, 0x0b, 0xb1, 0xa4, 0x0c, 0x59, 0xf6,
	0xe9, 0x9f, 0xad, 0xe7, 0xce, 0x02, 0x03, 0x8c, 0x69, 0x82, 0xac, 0x57, 0xfe, 0xc7, 0x30, 0x49,
	0x97, 0xc5, 0x95, 0xf2, 0x8b, 0xa2, 0xfc, 0xa6, 0x28, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x33,
	0xbb, 0x3b, 0xc2, 0x4d, 0x08, 0x00, 0x00,
}
