// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyRequestProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequestProto) Reset()         { *m = EmptyRequestProto{} }
func (m *EmptyRequestProto) String() string { return proto.CompactTextString(m) }
func (*EmptyRequestProto) ProtoMessage()    {}
func (*EmptyRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *EmptyRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequestProto.Unmarshal(m, b)
}
func (m *EmptyRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequestProto.Marshal(b, m, deterministic)
}
func (m *EmptyRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequestProto.Merge(m, src)
}
func (m *EmptyRequestProto) XXX_Size() int {
	return xxx_messageInfo_EmptyRequestProto.Size(m)
}
func (m *EmptyRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequestProto proto.InternalMessageInfo

type EmptyResponseProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponseProto) Reset()         { *m = EmptyResponseProto{} }
func (m *EmptyResponseProto) String() string { return proto.CompactTextString(m) }
func (*EmptyResponseProto) ProtoMessage()    {}
func (*EmptyResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *EmptyResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponseProto.Unmarshal(m, b)
}
func (m *EmptyResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponseProto.Marshal(b, m, deterministic)
}
func (m *EmptyResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponseProto.Merge(m, src)
}
func (m *EmptyResponseProto) XXX_Size() int {
	return xxx_messageInfo_EmptyResponseProto.Size(m)
}
func (m *EmptyResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponseProto proto.InternalMessageInfo

type EchoRequestProto struct {
	Message              *string  `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequestProto) Reset()         { *m = EchoRequestProto{} }
func (m *EchoRequestProto) String() string { return proto.CompactTextString(m) }
func (*EchoRequestProto) ProtoMessage()    {}
func (*EchoRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *EchoRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequestProto.Unmarshal(m, b)
}
func (m *EchoRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequestProto.Marshal(b, m, deterministic)
}
func (m *EchoRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequestProto.Merge(m, src)
}
func (m *EchoRequestProto) XXX_Size() int {
	return xxx_messageInfo_EchoRequestProto.Size(m)
}
func (m *EchoRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequestProto proto.InternalMessageInfo

func (m *EchoRequestProto) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type EchoResponseProto struct {
	Message              *string  `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoResponseProto) Reset()         { *m = EchoResponseProto{} }
func (m *EchoResponseProto) String() string { return proto.CompactTextString(m) }
func (*EchoResponseProto) ProtoMessage()    {}
func (*EchoResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{3}
}

func (m *EchoResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponseProto.Unmarshal(m, b)
}
func (m *EchoResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponseProto.Marshal(b, m, deterministic)
}
func (m *EchoResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponseProto.Merge(m, src)
}
func (m *EchoResponseProto) XXX_Size() int {
	return xxx_messageInfo_EchoResponseProto.Size(m)
}
func (m *EchoResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponseProto proto.InternalMessageInfo

func (m *EchoResponseProto) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type PauseRequestProto struct {
	Ms                   *uint32  `protobuf:"varint,1,req,name=ms" json:"ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PauseRequestProto) Reset()         { *m = PauseRequestProto{} }
func (m *PauseRequestProto) String() string { return proto.CompactTextString(m) }
func (*PauseRequestProto) ProtoMessage()    {}
func (*PauseRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{4}
}

func (m *PauseRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PauseRequestProto.Unmarshal(m, b)
}
func (m *PauseRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PauseRequestProto.Marshal(b, m, deterministic)
}
func (m *PauseRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PauseRequestProto.Merge(m, src)
}
func (m *PauseRequestProto) XXX_Size() int {
	return xxx_messageInfo_PauseRequestProto.Size(m)
}
func (m *PauseRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_PauseRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_PauseRequestProto proto.InternalMessageInfo

func (m *PauseRequestProto) GetMs() uint32 {
	if m != nil && m.Ms != nil {
		return *m.Ms
	}
	return 0
}

type AddrResponseProto struct {
	Addr                 *string  `protobuf:"bytes,1,req,name=addr" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddrResponseProto) Reset()         { *m = AddrResponseProto{} }
func (m *AddrResponseProto) String() string { return proto.CompactTextString(m) }
func (*AddrResponseProto) ProtoMessage()    {}
func (*AddrResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{5}
}

func (m *AddrResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddrResponseProto.Unmarshal(m, b)
}
func (m *AddrResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddrResponseProto.Marshal(b, m, deterministic)
}
func (m *AddrResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddrResponseProto.Merge(m, src)
}
func (m *AddrResponseProto) XXX_Size() int {
	return xxx_messageInfo_AddrResponseProto.Size(m)
}
func (m *AddrResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_AddrResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_AddrResponseProto proto.InternalMessageInfo

func (m *AddrResponseProto) GetAddr() string {
	if m != nil && m.Addr != nil {
		return *m.Addr
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyRequestProto)(nil), "EmptyRequestProto")
	proto.RegisterType((*EmptyResponseProto)(nil), "EmptyResponseProto")
	proto.RegisterType((*EchoRequestProto)(nil), "EchoRequestProto")
	proto.RegisterType((*EchoResponseProto)(nil), "EchoResponseProto")
	proto.RegisterType((*PauseRequestProto)(nil), "PauseRequestProto")
	proto.RegisterType((*AddrResponseProto)(nil), "AddrResponseProto")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xbd, 0x4a, 0xc4, 0x40,
	0x10, 0x80, 0x49, 0x10, 0xc4, 0x01, 0xc5, 0x8d, 0x16, 0x29, 0x25, 0x16, 0x5a, 0xe8, 0x76, 0x3e,
	0x80, 0x81, 0x58, 0x87, 0xe0, 0x0b, 0x4c, 0x32, 0x73, 0xd9, 0x2b, 0x36, 0xbb, 0xb7, 0xb3, 0x29,
	0xee, 0x6d, 0xee, 0x51, 0x0f, 0xf2, 0x03, 0x49, 0x73, 0xdd, 0xcc, 0xc7, 0xc7, 0x37, 0x30, 0x00,
	0x91, 0x25, 0x6a, 0x1f, 0x5c, 0x74, 0xc5, 0x0b, 0xa8, 0xca, 0xfa, 0x78, 0x6e, 0xf8, 0x34, 0xb2,
	0xc4, 0x7a, 0x82, 0xaf, 0x90, 0x2d, 0x50, 0xbc, 0x1b, 0x84, 0x67, 0xfa, 0x05, 0xcf, 0x55, 0x67,
	0xdc, 0xd6, 0xcc, 0x72, 0xb8, 0xb7, 0x2c, 0x82, 0x3d, 0xe7, 0xc9, 0x5b, 0xfa, 0xf9, 0xd0, 0xac,
	0x6b, 0xf1, 0x0d, 0x6a, 0xb6, 0x37, 0x89, 0x1b, 0xfa, 0x3b, 0xa8, 0x1a, 0x47, 0xe1, 0x5d, 0xfd,
	0x09, 0x52, 0x2b, 0x93, 0xf9, 0xd8, 0xa4, 0x56, 0x8a, 0x0f, 0x50, 0xbf, 0x44, 0x61, 0xdf, 0xcc,
	0xe0, 0x0e, 0x89, 0xc2, 0x12, 0x9c, 0xe6, 0xf2, 0x0f, 0x7e, 0x5c, 0xe8, 0x35, 0x7a, 0xec, 0x0c,
	0x6b, 0x83, 0xe4, 0x9c, 0xd7, 0xa6, 0x45, 0x61, 0x2d, 0x06, 0x89, 0x49, 0x1f, 0x7d, 0x37, 0x7f,
	0xa0, 0x1d, 0x0f, 0xba, 0xe7, 0x81, 0x03, 0x46, 0xa6, 0x12, 0xfe, 0xd7, 0xe3, 0x72, 0x49, 0x92,
	0x6b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xd6, 0x48, 0xde, 0x2a, 0x01, 0x00, 0x00,
}
